/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.agent.prompts;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.MediaTypes;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.core.PhenoMLApiException;
import com.phenoml.api.core.PhenoMLException;
import com.phenoml.api.core.PhenoMLHttpResponse;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.agent.errors.BadRequestError;
import com.phenoml.api.resources.agent.errors.ForbiddenError;
import com.phenoml.api.resources.agent.errors.InternalServerError;
import com.phenoml.api.resources.agent.errors.NotFoundError;
import com.phenoml.api.resources.agent.errors.UnauthorizedError;
import com.phenoml.api.resources.agent.prompts.requests.AgentPromptsCreateRequest;
import com.phenoml.api.resources.agent.prompts.requests.AgentPromptsUpdateRequest;
import com.phenoml.api.resources.agent.prompts.types.PromptsDeleteResponse;
import com.phenoml.api.resources.agent.prompts.types.PromptsListResponse;
import com.phenoml.api.resources.agent.types.AgentPromptsResponse;
import com.phenoml.api.resources.agent.types.JsonPatchOperation;
import com.phenoml.api.resources.agent.types.SuccessResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawPromptsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawPromptsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Creates a new agent prompt
   */
  public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> create(
      AgentPromptsCreateRequest request) {
    return create(request,null);
  }

  /**
   * Creates a new agent prompt
   */
  public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> create(
      AgentPromptsCreateRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("agent/prompts");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new PhenoMLException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AgentPromptsResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Retrieves a list of agent prompts belonging to the authenticated user
     */
    public CompletableFuture<PhenoMLHttpResponse<PromptsListResponse>> list() {
      return list(null);
    }

    /**
     * Retrieves a list of agent prompts belonging to the authenticated user
     */
    public CompletableFuture<PhenoMLHttpResponse<PromptsListResponse>> list(
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("agent/prompts/list");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PhenoMLHttpResponse<PromptsListResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PromptsListResponse.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Retrieves a specific prompt by its ID
       */
      public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> get(String id) {
        return get(id,null);
      }

      /**
       * Retrieves a specific prompt by its ID
       */
      public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> get(String id,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("agent/prompts")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AgentPromptsResponse.class), response));
                  return;
                }
                try {
                  switch (response.code()) {
                    case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * Updates an existing prompt
         */
        public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> update(String id) {
          return update(id,AgentPromptsUpdateRequest.builder().build());
        }

        /**
         * Updates an existing prompt
         */
        public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> update(String id,
            RequestOptions requestOptions) {
          return update(id,AgentPromptsUpdateRequest.builder().build(),requestOptions);
        }

        /**
         * Updates an existing prompt
         */
        public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> update(String id,
            AgentPromptsUpdateRequest request) {
          return update(id,request,null);
        }

        /**
         * Updates an existing prompt
         */
        public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> update(String id,
            AgentPromptsUpdateRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("agent/prompts")
            .addPathSegment(id);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new PhenoMLException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl.build())
              .method("PUT", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AgentPromptsResponse.class), response));
                    return;
                  }
                  try {
                    switch (response.code()) {
                      case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * Deletes a prompt
           */
          public CompletableFuture<PhenoMLHttpResponse<PromptsDeleteResponse>> delete(String id) {
            return delete(id,null);
          }

          /**
           * Deletes a prompt
           */
          public CompletableFuture<PhenoMLHttpResponse<PromptsDeleteResponse>> delete(String id,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("agent/prompts")
              .addPathSegment(id);if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              CompletableFuture<PhenoMLHttpResponse<PromptsDeleteResponse>> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PromptsDeleteResponse.class), response));
                      return;
                    }
                    try {
                      switch (response.code()) {
                        case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                        return;
                        case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                        return;
                        case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                        return;
                        case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                }
              });
              return future;
            }

            /**
             * Patches an existing prompt
             */
            public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> patch(String id,
                List<JsonPatchOperation> request) {
              return patch(id,request,null);
            }

            /**
             * Patches an existing prompt
             */
            public CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> patch(String id,
                List<JsonPatchOperation> request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("agent/prompts")
                .addPathSegment(id);if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaType.parse("application/json+patch"));
                }
                catch(JsonProcessingException e) {
                  throw new PhenoMLException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("PATCH", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json+patch")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                CompletableFuture<PhenoMLHttpResponse<AgentPromptsResponse>> future = new CompletableFuture<>();
                client.newCall(okhttpRequest).enqueue(new Callback() {
                  @Override
                  public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                    try (ResponseBody responseBody = response.body()) {
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AgentPromptsResponse.class), response));
                        return;
                      }
                      try {
                        switch (response.code()) {
                          case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                          case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                          case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                          case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                          case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                      return;
                    }
                    catch (IOException e) {
                      future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                    }
                  }

                  @Override
                  public void onFailure(@NotNull Call call, @NotNull IOException e) {
                    future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                  }
                });
                return future;
              }

              /**
               * Loads default agent prompts for the authenticated user
               */
              public CompletableFuture<PhenoMLHttpResponse<SuccessResponse>> loadDefaults() {
                return loadDefaults(null);
              }

              /**
               * Loads default agent prompts for the authenticated user
               */
              public CompletableFuture<PhenoMLHttpResponse<SuccessResponse>> loadDefaults(
                  RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("agent/prompts/load-defaults");if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  Request okhttpRequest = new Request.Builder()
                    .url(httpUrl.build())
                    .method("POST", RequestBody.create("", null))
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Accept", "application/json")
                    .build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  CompletableFuture<PhenoMLHttpResponse<SuccessResponse>> future = new CompletableFuture<>();
                  client.newCall(okhttpRequest).enqueue(new Callback() {
                    @Override
                    public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                      try (ResponseBody responseBody = response.body()) {
                        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                        if (response.isSuccessful()) {
                          future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class), response));
                          return;
                        }
                        try {
                          switch (response.code()) {
                            case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                            case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                            case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                          }
                        }
                        catch (JsonProcessingException ignored) {
                          // unable to map error response, throwing generic error
                        }
                        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                        future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                        return;
                      }
                      catch (IOException e) {
                        future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                      }
                    }

                    @Override
                    public void onFailure(@NotNull Call call, @NotNull IOException e) {
                      future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                    }
                  });
                  return future;
                }
              }
