/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.workflows.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExecuteWorkflowResponse.Builder.class)
public final class ExecuteWorkflowResponse {
    private final Optional<Boolean> success;

    private final Optional<String> message;

    private final Optional<Results> results;

    private final Map<String, Object> additionalProperties;

    private ExecuteWorkflowResponse(
            Optional<Boolean> success,
            Optional<String> message,
            Optional<Results> results,
            Map<String, Object> additionalProperties) {
        this.success = success;
        this.message = message;
        this.results = results;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether the workflow execution was successful
     */
    @JsonProperty("success")
    public Optional<Boolean> getSuccess() {
        return success;
    }

    /**
     * @return Status message with execution details
     */
    @JsonProperty("message")
    public Optional<String> getMessage() {
        return message;
    }

    @JsonProperty("results")
    public Optional<Results> getResults() {
        return results;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExecuteWorkflowResponse && equalTo((ExecuteWorkflowResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExecuteWorkflowResponse other) {
        return success.equals(other.success) && message.equals(other.message) && results.equals(other.results);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.message, this.results);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> success = Optional.empty();

        private Optional<String> message = Optional.empty();

        private Optional<Results> results = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ExecuteWorkflowResponse other) {
            success(other.getSuccess());
            message(other.getMessage());
            results(other.getResults());
            return this;
        }

        /**
         * <p>Whether the workflow execution was successful</p>
         */
        @JsonSetter(value = "success", nulls = Nulls.SKIP)
        public Builder success(Optional<Boolean> success) {
            this.success = success;
            return this;
        }

        public Builder success(Boolean success) {
            this.success = Optional.ofNullable(success);
            return this;
        }

        /**
         * <p>Status message with execution details</p>
         */
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public Builder message(Optional<String> message) {
            this.message = message;
            return this;
        }

        public Builder message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        @JsonSetter(value = "results", nulls = Nulls.SKIP)
        public Builder results(Optional<Results> results) {
            this.results = results;
            return this;
        }

        public Builder results(Results results) {
            this.results = Optional.ofNullable(results);
            return this;
        }

        public ExecuteWorkflowResponse build() {
            return new ExecuteWorkflowResponse(success, message, results, additionalProperties);
        }
    }

    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    @JsonDeserialize(builder = Results.Builder.class)
    public static final class Results {
        private final Optional<Map<String, Object>> steps;

        private final Map<String, Object> additionalProperties;

        private Results(Optional<Map<String, Object>> steps, Map<String, Object> additionalProperties) {
            this.steps = steps;
            this.additionalProperties = additionalProperties;
        }

        /**
         * @return Results for each executed workflow step, keyed by step ID
         */
        @JsonProperty("steps")
        public Optional<Map<String, Object>> getSteps() {
            return steps;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof Results && equalTo((Results) other);
        }

        @JsonAnyGetter
        public Map<String, Object> getAdditionalProperties() {
            return this.additionalProperties;
        }

        private boolean equalTo(Results other) {
            return steps.equals(other.steps);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.steps);
        }

        @java.lang.Override
        public String toString() {
            return ObjectMappers.stringify(this);
        }

        public static Builder builder() {
            return new Builder();
        }

        @JsonIgnoreProperties(ignoreUnknown = true)
        public static final class Builder {
            private Optional<Map<String, Object>> steps = Optional.empty();

            @JsonAnySetter
            private Map<String, Object> additionalProperties = new HashMap<>();

            private Builder() {}

            public Builder from(Results other) {
                steps(other.getSteps());
                return this;
            }

            /**
             * <p>Results for each executed workflow step, keyed by step ID</p>
             */
            @JsonSetter(value = "steps", nulls = Nulls.SKIP)
            public Builder steps(Optional<Map<String, Object>> steps) {
                this.steps = steps;
                return this;
            }

            public Builder steps(Map<String, Object> steps) {
                this.steps = Optional.ofNullable(steps);
                return this;
            }

            public Results build() {
                return new Results(steps, additionalProperties);
            }
        }
    }
}
