/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.workflows.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WorkflowResponseGraph.Builder.class
)
public final class WorkflowResponseGraph {
  private final Optional<List<WorkflowStepSummary>> steps;

  private final Map<String, Object> additionalProperties;

  private WorkflowResponseGraph(Optional<List<WorkflowStepSummary>> steps,
      Map<String, Object> additionalProperties) {
    this.steps = steps;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Simplified list of workflow steps without operation details
   */
  @JsonProperty("steps")
  public Optional<List<WorkflowStepSummary>> getSteps() {
    return steps;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WorkflowResponseGraph && equalTo((WorkflowResponseGraph) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WorkflowResponseGraph other) {
    return steps.equals(other.steps);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.steps);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<WorkflowStepSummary>> steps = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WorkflowResponseGraph other) {
      steps(other.getSteps());
      return this;
    }

    /**
     * <p>Simplified list of workflow steps without operation details</p>
     */
    @JsonSetter(
        value = "steps",
        nulls = Nulls.SKIP
    )
    public Builder steps(Optional<List<WorkflowStepSummary>> steps) {
      this.steps = steps;
      return this;
    }

    public Builder steps(List<WorkflowStepSummary> steps) {
      this.steps = Optional.ofNullable(steps);
      return this;
    }

    public WorkflowResponseGraph build() {
      return new WorkflowResponseGraph(steps, additionalProperties);
    }
  }
}
