/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.lang2fhir.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateMultiResponseBundle.Builder.class
)
public final class CreateMultiResponseBundle {
  private final Optional<String> resourceType;

  private final Optional<String> type;

  private final Optional<List<CreateMultiResponseBundleEntryItem>> entry;

  private final Map<String, Object> additionalProperties;

  private CreateMultiResponseBundle(Optional<String> resourceType, Optional<String> type,
      Optional<List<CreateMultiResponseBundleEntryItem>> entry,
      Map<String, Object> additionalProperties) {
    this.resourceType = resourceType;
    this.type = type;
    this.entry = entry;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("resourceType")
  public Optional<String> getResourceType() {
    return resourceType;
  }

  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  @JsonProperty("entry")
  public Optional<List<CreateMultiResponseBundleEntryItem>> getEntry() {
    return entry;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateMultiResponseBundle && equalTo((CreateMultiResponseBundle) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateMultiResponseBundle other) {
    return resourceType.equals(other.resourceType) && type.equals(other.type) && entry.equals(other.entry);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.resourceType, this.type, this.entry);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> resourceType = Optional.empty();

    private Optional<String> type = Optional.empty();

    private Optional<List<CreateMultiResponseBundleEntryItem>> entry = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateMultiResponseBundle other) {
      resourceType(other.getResourceType());
      type(other.getType());
      entry(other.getEntry());
      return this;
    }

    @JsonSetter(
        value = "resourceType",
        nulls = Nulls.SKIP
    )
    public Builder resourceType(Optional<String> resourceType) {
      this.resourceType = resourceType;
      return this;
    }

    public Builder resourceType(String resourceType) {
      this.resourceType = Optional.ofNullable(resourceType);
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "entry",
        nulls = Nulls.SKIP
    )
    public Builder entry(Optional<List<CreateMultiResponseBundleEntryItem>> entry) {
      this.entry = entry;
      return this;
    }

    public Builder entry(List<CreateMultiResponseBundleEntryItem> entry) {
      this.entry = Optional.ofNullable(entry);
      return this;
    }

    public CreateMultiResponseBundle build() {
      return new CreateMultiResponseBundle(resourceType, type, entry, additionalProperties);
    }
  }
}
