/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.lang2fhir.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateMultiResponseValidationPassesItemIssuesItemSeverity {
    public static final CreateMultiResponseValidationPassesItemIssuesItemSeverity FATAL =
            new CreateMultiResponseValidationPassesItemIssuesItemSeverity(Value.FATAL, "fatal");

    public static final CreateMultiResponseValidationPassesItemIssuesItemSeverity WARNING =
            new CreateMultiResponseValidationPassesItemIssuesItemSeverity(Value.WARNING, "warning");

    public static final CreateMultiResponseValidationPassesItemIssuesItemSeverity ERROR =
            new CreateMultiResponseValidationPassesItemIssuesItemSeverity(Value.ERROR, "error");

    public static final CreateMultiResponseValidationPassesItemIssuesItemSeverity INFORMATION =
            new CreateMultiResponseValidationPassesItemIssuesItemSeverity(Value.INFORMATION, "information");

    private final Value value;

    private final String string;

    CreateMultiResponseValidationPassesItemIssuesItemSeverity(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateMultiResponseValidationPassesItemIssuesItemSeverity
                        && this.string.equals(
                                ((CreateMultiResponseValidationPassesItemIssuesItemSeverity) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FATAL:
                return visitor.visitFatal();
            case WARNING:
                return visitor.visitWarning();
            case ERROR:
                return visitor.visitError();
            case INFORMATION:
                return visitor.visitInformation();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateMultiResponseValidationPassesItemIssuesItemSeverity valueOf(String value) {
        switch (value) {
            case "fatal":
                return FATAL;
            case "warning":
                return WARNING;
            case "error":
                return ERROR;
            case "information":
                return INFORMATION;
            default:
                return new CreateMultiResponseValidationPassesItemIssuesItemSeverity(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        FATAL,

        ERROR,

        WARNING,

        INFORMATION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitFatal();

        T visitError();

        T visitWarning();

        T visitInformation();

        T visitUnknown(String unknownType);
    }
}
