/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.lang2fhir.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResourceReviewResult.Builder.class)
public final class ResourceReviewResult {
    private final Optional<List<ResourceReviewFlagged>> flagged;

    private final Map<String, Object> additionalProperties;

    private ResourceReviewResult(
            Optional<List<ResourceReviewFlagged>> flagged, Map<String, Object> additionalProperties) {
        this.flagged = flagged;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Resources pulled from the bundle because a reviewed field was not supported by the source.
     */
    @JsonProperty("flagged")
    public Optional<List<ResourceReviewFlagged>> getFlagged() {
        return flagged;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ResourceReviewResult && equalTo((ResourceReviewResult) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ResourceReviewResult other) {
        return flagged.equals(other.flagged);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.flagged);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ResourceReviewFlagged>> flagged = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ResourceReviewResult other) {
            flagged(other.getFlagged());
            return this;
        }

        /**
         * <p>Resources pulled from the bundle because a reviewed field was not supported by the source.</p>
         */
        @JsonSetter(value = "flagged", nulls = Nulls.SKIP)
        public Builder flagged(Optional<List<ResourceReviewFlagged>> flagged) {
            this.flagged = flagged;
            return this;
        }

        public Builder flagged(List<ResourceReviewFlagged> flagged) {
            this.flagged = Optional.ofNullable(flagged);
            return this;
        }

        public ResourceReviewResult build() {
            return new ResourceReviewResult(flagged, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
