/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir2omop.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateOmopResponse.Builder.class)
public final class CreateOmopResponse {
    private final Optional<Boolean> success;

    private final Optional<String> message;

    private final Optional<String> mode;

    private final Optional<OmopTables> tables;

    private final Optional<List<MappingReportEntry>> report;

    private final Optional<ScanSummary> scanSummary;

    private final Map<String, Object> additionalProperties;

    private CreateOmopResponse(
            Optional<Boolean> success,
            Optional<String> message,
            Optional<String> mode,
            Optional<OmopTables> tables,
            Optional<List<MappingReportEntry>> report,
            Optional<ScanSummary> scanSummary,
            Map<String, Object> additionalProperties) {
        this.success = success;
        this.message = message;
        this.mode = mode;
        this.tables = tables;
        this.report = report;
        this.scanSummary = scanSummary;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("success")
    public Optional<Boolean> getSuccess() {
        return success;
    }

    @JsonProperty("message")
    public Optional<String> getMessage() {
        return message;
    }

    /**
     * @return Resolution mode. <code>resolved</code> (default) means clinical <code>concept_id</code>s were
     * filled by the concept-resolver service; <code>structural</code> means no resolver
     * was configured, so all clinical <code>concept_id</code>s are <code>0</code>. Reflects which
     * resolver is wired, not the path an individual coding took — per-coding
     * degradation is surfaced in <code>scan_summary</code>, not the mode.
     */
    @JsonProperty("mode")
    public Optional<String> getMode() {
        return mode;
    }

    @JsonProperty("tables")
    public Optional<OmopTables> getTables() {
        return tables;
    }

    /**
     * @return One Usagi-shaped entry per source coding routed through concept resolution.
     */
    @JsonProperty("report")
    public Optional<List<MappingReportEntry>> getReport() {
        return report;
    }

    @JsonProperty("scan_summary")
    public Optional<ScanSummary> getScanSummary() {
        return scanSummary;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateOmopResponse && equalTo((CreateOmopResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateOmopResponse other) {
        return success.equals(other.success)
                && message.equals(other.message)
                && mode.equals(other.mode)
                && tables.equals(other.tables)
                && report.equals(other.report)
                && scanSummary.equals(other.scanSummary);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.message, this.mode, this.tables, this.report, this.scanSummary);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> success = Optional.empty();

        private Optional<String> message = Optional.empty();

        private Optional<String> mode = Optional.empty();

        private Optional<OmopTables> tables = Optional.empty();

        private Optional<List<MappingReportEntry>> report = Optional.empty();

        private Optional<ScanSummary> scanSummary = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateOmopResponse other) {
            success(other.getSuccess());
            message(other.getMessage());
            mode(other.getMode());
            tables(other.getTables());
            report(other.getReport());
            scanSummary(other.getScanSummary());
            return this;
        }

        @JsonSetter(value = "success", nulls = Nulls.SKIP)
        public Builder success(Optional<Boolean> success) {
            this.success = success;
            return this;
        }

        public Builder success(Boolean success) {
            this.success = Optional.ofNullable(success);
            return this;
        }

        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public Builder message(Optional<String> message) {
            this.message = message;
            return this;
        }

        public Builder message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        /**
         * <p>Resolution mode. <code>resolved</code> (default) means clinical <code>concept_id</code>s were
         * filled by the concept-resolver service; <code>structural</code> means no resolver
         * was configured, so all clinical <code>concept_id</code>s are <code>0</code>. Reflects which
         * resolver is wired, not the path an individual coding took — per-coding
         * degradation is surfaced in <code>scan_summary</code>, not the mode.</p>
         */
        @JsonSetter(value = "mode", nulls = Nulls.SKIP)
        public Builder mode(Optional<String> mode) {
            this.mode = mode;
            return this;
        }

        public Builder mode(String mode) {
            this.mode = Optional.ofNullable(mode);
            return this;
        }

        @JsonSetter(value = "tables", nulls = Nulls.SKIP)
        public Builder tables(Optional<OmopTables> tables) {
            this.tables = tables;
            return this;
        }

        public Builder tables(OmopTables tables) {
            this.tables = Optional.ofNullable(tables);
            return this;
        }

        /**
         * <p>One Usagi-shaped entry per source coding routed through concept resolution.</p>
         */
        @JsonSetter(value = "report", nulls = Nulls.SKIP)
        public Builder report(Optional<List<MappingReportEntry>> report) {
            this.report = report;
            return this;
        }

        public Builder report(List<MappingReportEntry> report) {
            this.report = Optional.ofNullable(report);
            return this;
        }

        @JsonSetter(value = "scan_summary", nulls = Nulls.SKIP)
        public Builder scanSummary(Optional<ScanSummary> scanSummary) {
            this.scanSummary = scanSummary;
            return this;
        }

        public Builder scanSummary(ScanSummary scanSummary) {
            this.scanSummary = Optional.ofNullable(scanSummary);
            return this;
        }

        public CreateOmopResponse build() {
            return new CreateOmopResponse(success, message, mode, tables, report, scanSummary, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
