/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir2omop.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MappingEntry.Builder.class)
public final class MappingEntry {
    private final Optional<String> resourceType;

    private final Optional<String> resourceId;

    private final Optional<String> omopTable;

    private final Optional<Long> omopId;

    private final Optional<String> sourceSystem;

    private final Optional<String> sourceCode;

    private final Optional<String> sourceName;

    private final Optional<String> targetVocabulary;

    private final Optional<String> targetCode;

    private final Optional<String> targetName;

    private final Optional<String> mappingStatus;

    private final Optional<String> note;

    private final Map<String, Object> additionalProperties;

    private MappingEntry(
            Optional<String> resourceType,
            Optional<String> resourceId,
            Optional<String> omopTable,
            Optional<Long> omopId,
            Optional<String> sourceSystem,
            Optional<String> sourceCode,
            Optional<String> sourceName,
            Optional<String> targetVocabulary,
            Optional<String> targetCode,
            Optional<String> targetName,
            Optional<String> mappingStatus,
            Optional<String> note,
            Map<String, Object> additionalProperties) {
        this.resourceType = resourceType;
        this.resourceId = resourceId;
        this.omopTable = omopTable;
        this.omopId = omopId;
        this.sourceSystem = sourceSystem;
        this.sourceCode = sourceCode;
        this.sourceName = sourceName;
        this.targetVocabulary = targetVocabulary;
        this.targetCode = targetCode;
        this.targetName = targetName;
        this.mappingStatus = mappingStatus;
        this.note = note;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("resource_type")
    public Optional<String> getResourceType() {
        return resourceType;
    }

    @JsonProperty("resource_id")
    public Optional<String> getResourceId() {
        return resourceId;
    }

    @JsonProperty("omop_table")
    public Optional<String> getOmopTable() {
        return omopTable;
    }

    /**
     * @return The id of the OMOP row this coding produced (e.g. <code>condition_occurrence_id</code>),
     * within <code>omop_table</code>. A resource with multiple codings yields one entry
     * per coding, all sharing this id.
     */
    @JsonProperty("omop_id")
    public Optional<Long> getOmopId() {
        return omopId;
    }

    @JsonProperty("source_system")
    public Optional<String> getSourceSystem() {
        return sourceSystem;
    }

    @JsonProperty("source_code")
    public Optional<String> getSourceCode() {
        return sourceCode;
    }

    @JsonProperty("source_name")
    public Optional<String> getSourceName() {
        return sourceName;
    }

    @JsonProperty("target_vocabulary")
    public Optional<String> getTargetVocabulary() {
        return targetVocabulary;
    }

    /**
     * @return The standard concept's own code: the source code itself for an
     * ALREADY_STANDARD row, the standard concept's code for a MAPPED row,
     * or the suggested code for an UNCHECKED row. Omitted for UNMAPPED
     * rows.
     */
    @JsonProperty("target_code")
    public Optional<String> getTargetCode() {
        return targetCode;
    }

    @JsonProperty("target_name")
    public Optional<String> getTargetName() {
        return targetName;
    }

    /**
     * @return ALREADY_STANDARD (source coding is already a standard OMOP concept),
     * MAPPED (source coding was mapped to a standard concept), UNCHECKED (a
     * standard code was suggested — e.g. for a text-only resource — but not
     * verified against the OMOP vocabulary, so <code>concept_id</code> stays <code>0</code>), or
     * UNMAPPED (no standard concept found).
     */
    @JsonProperty("mapping_status")
    public Optional<String> getMappingStatus() {
        return mappingStatus;
    }

    @JsonProperty("note")
    public Optional<String> getNote() {
        return note;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MappingEntry && equalTo((MappingEntry) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MappingEntry other) {
        return resourceType.equals(other.resourceType)
                && resourceId.equals(other.resourceId)
                && omopTable.equals(other.omopTable)
                && omopId.equals(other.omopId)
                && sourceSystem.equals(other.sourceSystem)
                && sourceCode.equals(other.sourceCode)
                && sourceName.equals(other.sourceName)
                && targetVocabulary.equals(other.targetVocabulary)
                && targetCode.equals(other.targetCode)
                && targetName.equals(other.targetName)
                && mappingStatus.equals(other.mappingStatus)
                && note.equals(other.note);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.resourceType,
                this.resourceId,
                this.omopTable,
                this.omopId,
                this.sourceSystem,
                this.sourceCode,
                this.sourceName,
                this.targetVocabulary,
                this.targetCode,
                this.targetName,
                this.mappingStatus,
                this.note);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> resourceType = Optional.empty();

        private Optional<String> resourceId = Optional.empty();

        private Optional<String> omopTable = Optional.empty();

        private Optional<Long> omopId = Optional.empty();

        private Optional<String> sourceSystem = Optional.empty();

        private Optional<String> sourceCode = Optional.empty();

        private Optional<String> sourceName = Optional.empty();

        private Optional<String> targetVocabulary = Optional.empty();

        private Optional<String> targetCode = Optional.empty();

        private Optional<String> targetName = Optional.empty();

        private Optional<String> mappingStatus = Optional.empty();

        private Optional<String> note = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(MappingEntry other) {
            resourceType(other.getResourceType());
            resourceId(other.getResourceId());
            omopTable(other.getOmopTable());
            omopId(other.getOmopId());
            sourceSystem(other.getSourceSystem());
            sourceCode(other.getSourceCode());
            sourceName(other.getSourceName());
            targetVocabulary(other.getTargetVocabulary());
            targetCode(other.getTargetCode());
            targetName(other.getTargetName());
            mappingStatus(other.getMappingStatus());
            note(other.getNote());
            return this;
        }

        @JsonSetter(value = "resource_type", nulls = Nulls.SKIP)
        public Builder resourceType(Optional<String> resourceType) {
            this.resourceType = resourceType;
            return this;
        }

        public Builder resourceType(String resourceType) {
            this.resourceType = Optional.ofNullable(resourceType);
            return this;
        }

        @JsonSetter(value = "resource_id", nulls = Nulls.SKIP)
        public Builder resourceId(Optional<String> resourceId) {
            this.resourceId = resourceId;
            return this;
        }

        public Builder resourceId(String resourceId) {
            this.resourceId = Optional.ofNullable(resourceId);
            return this;
        }

        @JsonSetter(value = "omop_table", nulls = Nulls.SKIP)
        public Builder omopTable(Optional<String> omopTable) {
            this.omopTable = omopTable;
            return this;
        }

        public Builder omopTable(String omopTable) {
            this.omopTable = Optional.ofNullable(omopTable);
            return this;
        }

        /**
         * <p>The id of the OMOP row this coding produced (e.g. <code>condition_occurrence_id</code>),
         * within <code>omop_table</code>. A resource with multiple codings yields one entry
         * per coding, all sharing this id.</p>
         */
        @JsonSetter(value = "omop_id", nulls = Nulls.SKIP)
        public Builder omopId(Optional<Long> omopId) {
            this.omopId = omopId;
            return this;
        }

        public Builder omopId(Long omopId) {
            this.omopId = Optional.ofNullable(omopId);
            return this;
        }

        @JsonSetter(value = "source_system", nulls = Nulls.SKIP)
        public Builder sourceSystem(Optional<String> sourceSystem) {
            this.sourceSystem = sourceSystem;
            return this;
        }

        public Builder sourceSystem(String sourceSystem) {
            this.sourceSystem = Optional.ofNullable(sourceSystem);
            return this;
        }

        @JsonSetter(value = "source_code", nulls = Nulls.SKIP)
        public Builder sourceCode(Optional<String> sourceCode) {
            this.sourceCode = sourceCode;
            return this;
        }

        public Builder sourceCode(String sourceCode) {
            this.sourceCode = Optional.ofNullable(sourceCode);
            return this;
        }

        @JsonSetter(value = "source_name", nulls = Nulls.SKIP)
        public Builder sourceName(Optional<String> sourceName) {
            this.sourceName = sourceName;
            return this;
        }

        public Builder sourceName(String sourceName) {
            this.sourceName = Optional.ofNullable(sourceName);
            return this;
        }

        @JsonSetter(value = "target_vocabulary", nulls = Nulls.SKIP)
        public Builder targetVocabulary(Optional<String> targetVocabulary) {
            this.targetVocabulary = targetVocabulary;
            return this;
        }

        public Builder targetVocabulary(String targetVocabulary) {
            this.targetVocabulary = Optional.ofNullable(targetVocabulary);
            return this;
        }

        /**
         * <p>The standard concept's own code: the source code itself for an
         * ALREADY_STANDARD row, the standard concept's code for a MAPPED row,
         * or the suggested code for an UNCHECKED row. Omitted for UNMAPPED
         * rows.</p>
         */
        @JsonSetter(value = "target_code", nulls = Nulls.SKIP)
        public Builder targetCode(Optional<String> targetCode) {
            this.targetCode = targetCode;
            return this;
        }

        public Builder targetCode(String targetCode) {
            this.targetCode = Optional.ofNullable(targetCode);
            return this;
        }

        @JsonSetter(value = "target_name", nulls = Nulls.SKIP)
        public Builder targetName(Optional<String> targetName) {
            this.targetName = targetName;
            return this;
        }

        public Builder targetName(String targetName) {
            this.targetName = Optional.ofNullable(targetName);
            return this;
        }

        /**
         * <p>ALREADY_STANDARD (source coding is already a standard OMOP concept),
         * MAPPED (source coding was mapped to a standard concept), UNCHECKED (a
         * standard code was suggested — e.g. for a text-only resource — but not
         * verified against the OMOP vocabulary, so <code>concept_id</code> stays <code>0</code>), or
         * UNMAPPED (no standard concept found).</p>
         */
        @JsonSetter(value = "mapping_status", nulls = Nulls.SKIP)
        public Builder mappingStatus(Optional<String> mappingStatus) {
            this.mappingStatus = mappingStatus;
            return this;
        }

        public Builder mappingStatus(String mappingStatus) {
            this.mappingStatus = Optional.ofNullable(mappingStatus);
            return this;
        }

        @JsonSetter(value = "note", nulls = Nulls.SKIP)
        public Builder note(Optional<String> note) {
            this.note = note;
            return this;
        }

        public Builder note(String note) {
            this.note = Optional.ofNullable(note);
            return this;
        }

        public MappingEntry build() {
            return new MappingEntry(
                    resourceType,
                    resourceId,
                    omopTable,
                    omopId,
                    sourceSystem,
                    sourceCode,
                    sourceName,
                    targetVocabulary,
                    targetCode,
                    targetName,
                    mappingStatus,
                    note,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
