/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir2omop.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProviderRow.Builder.class)
public final class ProviderRow {
    private final Optional<Long> providerId;

    private final Optional<String> providerName;

    private final Optional<String> npi;

    private final Optional<String> dea;

    private final Optional<Long> specialtyConceptId;

    private final Optional<Long> careSiteId;

    private final Optional<Integer> yearOfBirth;

    private final Optional<Long> genderConceptId;

    private final Optional<String> providerSourceValue;

    private final Optional<String> specialtySourceValue;

    private final Optional<Long> specialtySourceConceptId;

    private final Optional<String> genderSourceValue;

    private final Optional<Long> genderSourceConceptId;

    private final Map<String, Object> additionalProperties;

    private ProviderRow(
            Optional<Long> providerId,
            Optional<String> providerName,
            Optional<String> npi,
            Optional<String> dea,
            Optional<Long> specialtyConceptId,
            Optional<Long> careSiteId,
            Optional<Integer> yearOfBirth,
            Optional<Long> genderConceptId,
            Optional<String> providerSourceValue,
            Optional<String> specialtySourceValue,
            Optional<Long> specialtySourceConceptId,
            Optional<String> genderSourceValue,
            Optional<Long> genderSourceConceptId,
            Map<String, Object> additionalProperties) {
        this.providerId = providerId;
        this.providerName = providerName;
        this.npi = npi;
        this.dea = dea;
        this.specialtyConceptId = specialtyConceptId;
        this.careSiteId = careSiteId;
        this.yearOfBirth = yearOfBirth;
        this.genderConceptId = genderConceptId;
        this.providerSourceValue = providerSourceValue;
        this.specialtySourceValue = specialtySourceValue;
        this.specialtySourceConceptId = specialtySourceConceptId;
        this.genderSourceValue = genderSourceValue;
        this.genderSourceConceptId = genderSourceConceptId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("provider_id")
    public Optional<Long> getProviderId() {
        return providerId;
    }

    @JsonProperty("provider_name")
    public Optional<String> getProviderName() {
        return providerName;
    }

    @JsonProperty("npi")
    public Optional<String> getNpi() {
        return npi;
    }

    @JsonProperty("dea")
    public Optional<String> getDea() {
        return dea;
    }

    @JsonProperty("specialty_concept_id")
    public Optional<Long> getSpecialtyConceptId() {
        return specialtyConceptId;
    }

    @JsonProperty("care_site_id")
    public Optional<Long> getCareSiteId() {
        return careSiteId;
    }

    @JsonProperty("year_of_birth")
    public Optional<Integer> getYearOfBirth() {
        return yearOfBirth;
    }

    @JsonProperty("gender_concept_id")
    public Optional<Long> getGenderConceptId() {
        return genderConceptId;
    }

    @JsonProperty("provider_source_value")
    public Optional<String> getProviderSourceValue() {
        return providerSourceValue;
    }

    @JsonProperty("specialty_source_value")
    public Optional<String> getSpecialtySourceValue() {
        return specialtySourceValue;
    }

    @JsonProperty("specialty_source_concept_id")
    public Optional<Long> getSpecialtySourceConceptId() {
        return specialtySourceConceptId;
    }

    @JsonProperty("gender_source_value")
    public Optional<String> getGenderSourceValue() {
        return genderSourceValue;
    }

    @JsonProperty("gender_source_concept_id")
    public Optional<Long> getGenderSourceConceptId() {
        return genderSourceConceptId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProviderRow && equalTo((ProviderRow) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProviderRow other) {
        return providerId.equals(other.providerId)
                && providerName.equals(other.providerName)
                && npi.equals(other.npi)
                && dea.equals(other.dea)
                && specialtyConceptId.equals(other.specialtyConceptId)
                && careSiteId.equals(other.careSiteId)
                && yearOfBirth.equals(other.yearOfBirth)
                && genderConceptId.equals(other.genderConceptId)
                && providerSourceValue.equals(other.providerSourceValue)
                && specialtySourceValue.equals(other.specialtySourceValue)
                && specialtySourceConceptId.equals(other.specialtySourceConceptId)
                && genderSourceValue.equals(other.genderSourceValue)
                && genderSourceConceptId.equals(other.genderSourceConceptId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.providerId,
                this.providerName,
                this.npi,
                this.dea,
                this.specialtyConceptId,
                this.careSiteId,
                this.yearOfBirth,
                this.genderConceptId,
                this.providerSourceValue,
                this.specialtySourceValue,
                this.specialtySourceConceptId,
                this.genderSourceValue,
                this.genderSourceConceptId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Long> providerId = Optional.empty();

        private Optional<String> providerName = Optional.empty();

        private Optional<String> npi = Optional.empty();

        private Optional<String> dea = Optional.empty();

        private Optional<Long> specialtyConceptId = Optional.empty();

        private Optional<Long> careSiteId = Optional.empty();

        private Optional<Integer> yearOfBirth = Optional.empty();

        private Optional<Long> genderConceptId = Optional.empty();

        private Optional<String> providerSourceValue = Optional.empty();

        private Optional<String> specialtySourceValue = Optional.empty();

        private Optional<Long> specialtySourceConceptId = Optional.empty();

        private Optional<String> genderSourceValue = Optional.empty();

        private Optional<Long> genderSourceConceptId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ProviderRow other) {
            providerId(other.getProviderId());
            providerName(other.getProviderName());
            npi(other.getNpi());
            dea(other.getDea());
            specialtyConceptId(other.getSpecialtyConceptId());
            careSiteId(other.getCareSiteId());
            yearOfBirth(other.getYearOfBirth());
            genderConceptId(other.getGenderConceptId());
            providerSourceValue(other.getProviderSourceValue());
            specialtySourceValue(other.getSpecialtySourceValue());
            specialtySourceConceptId(other.getSpecialtySourceConceptId());
            genderSourceValue(other.getGenderSourceValue());
            genderSourceConceptId(other.getGenderSourceConceptId());
            return this;
        }

        @JsonSetter(value = "provider_id", nulls = Nulls.SKIP)
        public Builder providerId(Optional<Long> providerId) {
            this.providerId = providerId;
            return this;
        }

        public Builder providerId(Long providerId) {
            this.providerId = Optional.ofNullable(providerId);
            return this;
        }

        @JsonSetter(value = "provider_name", nulls = Nulls.SKIP)
        public Builder providerName(Optional<String> providerName) {
            this.providerName = providerName;
            return this;
        }

        public Builder providerName(String providerName) {
            this.providerName = Optional.ofNullable(providerName);
            return this;
        }

        @JsonSetter(value = "npi", nulls = Nulls.SKIP)
        public Builder npi(Optional<String> npi) {
            this.npi = npi;
            return this;
        }

        public Builder npi(String npi) {
            this.npi = Optional.ofNullable(npi);
            return this;
        }

        @JsonSetter(value = "dea", nulls = Nulls.SKIP)
        public Builder dea(Optional<String> dea) {
            this.dea = dea;
            return this;
        }

        public Builder dea(String dea) {
            this.dea = Optional.ofNullable(dea);
            return this;
        }

        @JsonSetter(value = "specialty_concept_id", nulls = Nulls.SKIP)
        public Builder specialtyConceptId(Optional<Long> specialtyConceptId) {
            this.specialtyConceptId = specialtyConceptId;
            return this;
        }

        public Builder specialtyConceptId(Long specialtyConceptId) {
            this.specialtyConceptId = Optional.ofNullable(specialtyConceptId);
            return this;
        }

        @JsonSetter(value = "care_site_id", nulls = Nulls.SKIP)
        public Builder careSiteId(Optional<Long> careSiteId) {
            this.careSiteId = careSiteId;
            return this;
        }

        public Builder careSiteId(Long careSiteId) {
            this.careSiteId = Optional.ofNullable(careSiteId);
            return this;
        }

        @JsonSetter(value = "year_of_birth", nulls = Nulls.SKIP)
        public Builder yearOfBirth(Optional<Integer> yearOfBirth) {
            this.yearOfBirth = yearOfBirth;
            return this;
        }

        public Builder yearOfBirth(Integer yearOfBirth) {
            this.yearOfBirth = Optional.ofNullable(yearOfBirth);
            return this;
        }

        @JsonSetter(value = "gender_concept_id", nulls = Nulls.SKIP)
        public Builder genderConceptId(Optional<Long> genderConceptId) {
            this.genderConceptId = genderConceptId;
            return this;
        }

        public Builder genderConceptId(Long genderConceptId) {
            this.genderConceptId = Optional.ofNullable(genderConceptId);
            return this;
        }

        @JsonSetter(value = "provider_source_value", nulls = Nulls.SKIP)
        public Builder providerSourceValue(Optional<String> providerSourceValue) {
            this.providerSourceValue = providerSourceValue;
            return this;
        }

        public Builder providerSourceValue(String providerSourceValue) {
            this.providerSourceValue = Optional.ofNullable(providerSourceValue);
            return this;
        }

        @JsonSetter(value = "specialty_source_value", nulls = Nulls.SKIP)
        public Builder specialtySourceValue(Optional<String> specialtySourceValue) {
            this.specialtySourceValue = specialtySourceValue;
            return this;
        }

        public Builder specialtySourceValue(String specialtySourceValue) {
            this.specialtySourceValue = Optional.ofNullable(specialtySourceValue);
            return this;
        }

        @JsonSetter(value = "specialty_source_concept_id", nulls = Nulls.SKIP)
        public Builder specialtySourceConceptId(Optional<Long> specialtySourceConceptId) {
            this.specialtySourceConceptId = specialtySourceConceptId;
            return this;
        }

        public Builder specialtySourceConceptId(Long specialtySourceConceptId) {
            this.specialtySourceConceptId = Optional.ofNullable(specialtySourceConceptId);
            return this;
        }

        @JsonSetter(value = "gender_source_value", nulls = Nulls.SKIP)
        public Builder genderSourceValue(Optional<String> genderSourceValue) {
            this.genderSourceValue = genderSourceValue;
            return this;
        }

        public Builder genderSourceValue(String genderSourceValue) {
            this.genderSourceValue = Optional.ofNullable(genderSourceValue);
            return this;
        }

        @JsonSetter(value = "gender_source_concept_id", nulls = Nulls.SKIP)
        public Builder genderSourceConceptId(Optional<Long> genderSourceConceptId) {
            this.genderSourceConceptId = genderSourceConceptId;
            return this;
        }

        public Builder genderSourceConceptId(Long genderSourceConceptId) {
            this.genderSourceConceptId = Optional.ofNullable(genderSourceConceptId);
            return this;
        }

        public ProviderRow build() {
            return new ProviderRow(
                    providerId,
                    providerName,
                    npi,
                    dea,
                    specialtyConceptId,
                    careSiteId,
                    yearOfBirth,
                    genderConceptId,
                    providerSourceValue,
                    specialtySourceValue,
                    specialtySourceConceptId,
                    genderSourceValue,
                    genderSourceConceptId,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
