/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir2omop.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ScanSummary.Builder.class)
public final class ScanSummary {
    private final Optional<Integer> totalResources;

    private final Optional<Map<String, Integer>> resourceCounts;

    private final Optional<Map<String, Integer>> tablesPopulated;

    private final Optional<Map<String, Integer>> codingSystems;

    private final Optional<Integer> codesAlreadyStandard;

    private final Optional<Integer> codesNormalized;

    private final Optional<Integer> codesUnmapped;

    private final Optional<Double> offVocabRate;

    private final Optional<List<DroppedResource>> droppedResources;

    private final Optional<String> resolvedVocabVersion;

    private final Optional<String> conceptResolverNote;

    private final Optional<Integer> conceptsBridged;

    private final Optional<Integer> conceptCandidatesTruncated;

    private final Optional<Integer> construeResolutions;

    private final Map<String, Object> additionalProperties;

    private ScanSummary(
            Optional<Integer> totalResources,
            Optional<Map<String, Integer>> resourceCounts,
            Optional<Map<String, Integer>> tablesPopulated,
            Optional<Map<String, Integer>> codingSystems,
            Optional<Integer> codesAlreadyStandard,
            Optional<Integer> codesNormalized,
            Optional<Integer> codesUnmapped,
            Optional<Double> offVocabRate,
            Optional<List<DroppedResource>> droppedResources,
            Optional<String> resolvedVocabVersion,
            Optional<String> conceptResolverNote,
            Optional<Integer> conceptsBridged,
            Optional<Integer> conceptCandidatesTruncated,
            Optional<Integer> construeResolutions,
            Map<String, Object> additionalProperties) {
        this.totalResources = totalResources;
        this.resourceCounts = resourceCounts;
        this.tablesPopulated = tablesPopulated;
        this.codingSystems = codingSystems;
        this.codesAlreadyStandard = codesAlreadyStandard;
        this.codesNormalized = codesNormalized;
        this.codesUnmapped = codesUnmapped;
        this.offVocabRate = offVocabRate;
        this.droppedResources = droppedResources;
        this.resolvedVocabVersion = resolvedVocabVersion;
        this.conceptResolverNote = conceptResolverNote;
        this.conceptsBridged = conceptsBridged;
        this.conceptCandidatesTruncated = conceptCandidatesTruncated;
        this.construeResolutions = construeResolutions;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("total_resources")
    public Optional<Integer> getTotalResources() {
        return totalResources;
    }

    @JsonProperty("resource_counts")
    public Optional<Map<String, Integer>> getResourceCounts() {
        return resourceCounts;
    }

    @JsonProperty("tables_populated")
    public Optional<Map<String, Integer>> getTablesPopulated() {
        return tablesPopulated;
    }

    @JsonProperty("coding_systems")
    public Optional<Map<String, Integer>> getCodingSystems() {
        return codingSystems;
    }

    @JsonProperty("codes_already_standard")
    public Optional<Integer> getCodesAlreadyStandard() {
        return codesAlreadyStandard;
    }

    @JsonProperty("codes_normalized")
    public Optional<Integer> getCodesNormalized() {
        return codesNormalized;
    }

    @JsonProperty("codes_unmapped")
    public Optional<Integer> getCodesUnmapped() {
        return codesUnmapped;
    }

    @JsonProperty("off_vocab_rate")
    public Optional<Double> getOffVocabRate() {
        return offVocabRate;
    }

    @JsonProperty("dropped_resources")
    public Optional<List<DroppedResource>> getDroppedResources() {
        return droppedResources;
    }

    /**
     * @return OMOP vocabulary release the resolver mapped against (e.g. &quot;v20240229&quot;).
     * Resolved mode only; empty when no coded concept reached the service.
     */
    @JsonProperty("resolved_vocab_version")
    public Optional<String> getResolvedVocabVersion() {
        return resolvedVocabVersion;
    }

    /**
     * @return Set when concept resolution was degraded — the resolver was unavailable
     * for one or more codings, whose <code>concept_id</code>s fell back to the structural
     * (construe) tier. Empty when resolution was clean.
     */
    @JsonProperty("concept_resolver_note")
    public Optional<String> getConceptResolverNote() {
        return conceptResolverNote;
    }

    /**
     * @return Count of <code>concept_id</code>s chosen via the lower-confidence UMLS-CUI bridge
     * (no direct OMOP crosswalk existed). Resolved mode only.
     */
    @JsonProperty("concepts_bridged")
    public Optional<Integer> getConceptsBridged() {
        return conceptsBridged;
    }

    /**
     * @return Count of codings whose candidate list the resolver capped, so the best
     * concept may not have been among those returned.
     */
    @JsonProperty("concept_candidates_truncated")
    public Optional<Integer> getConceptCandidatesTruncated() {
        return conceptCandidatesTruncated;
    }

    /**
     * @return Count of codings resolved via the construe ML extractor — the text-only
     * or availability fallback path. A non-zero value bills the construe tier.
     */
    @JsonProperty("construe_resolutions")
    public Optional<Integer> getConstrueResolutions() {
        return construeResolutions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ScanSummary && equalTo((ScanSummary) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ScanSummary other) {
        return totalResources.equals(other.totalResources)
                && resourceCounts.equals(other.resourceCounts)
                && tablesPopulated.equals(other.tablesPopulated)
                && codingSystems.equals(other.codingSystems)
                && codesAlreadyStandard.equals(other.codesAlreadyStandard)
                && codesNormalized.equals(other.codesNormalized)
                && codesUnmapped.equals(other.codesUnmapped)
                && offVocabRate.equals(other.offVocabRate)
                && droppedResources.equals(other.droppedResources)
                && resolvedVocabVersion.equals(other.resolvedVocabVersion)
                && conceptResolverNote.equals(other.conceptResolverNote)
                && conceptsBridged.equals(other.conceptsBridged)
                && conceptCandidatesTruncated.equals(other.conceptCandidatesTruncated)
                && construeResolutions.equals(other.construeResolutions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.totalResources,
                this.resourceCounts,
                this.tablesPopulated,
                this.codingSystems,
                this.codesAlreadyStandard,
                this.codesNormalized,
                this.codesUnmapped,
                this.offVocabRate,
                this.droppedResources,
                this.resolvedVocabVersion,
                this.conceptResolverNote,
                this.conceptsBridged,
                this.conceptCandidatesTruncated,
                this.construeResolutions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> totalResources = Optional.empty();

        private Optional<Map<String, Integer>> resourceCounts = Optional.empty();

        private Optional<Map<String, Integer>> tablesPopulated = Optional.empty();

        private Optional<Map<String, Integer>> codingSystems = Optional.empty();

        private Optional<Integer> codesAlreadyStandard = Optional.empty();

        private Optional<Integer> codesNormalized = Optional.empty();

        private Optional<Integer> codesUnmapped = Optional.empty();

        private Optional<Double> offVocabRate = Optional.empty();

        private Optional<List<DroppedResource>> droppedResources = Optional.empty();

        private Optional<String> resolvedVocabVersion = Optional.empty();

        private Optional<String> conceptResolverNote = Optional.empty();

        private Optional<Integer> conceptsBridged = Optional.empty();

        private Optional<Integer> conceptCandidatesTruncated = Optional.empty();

        private Optional<Integer> construeResolutions = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ScanSummary other) {
            totalResources(other.getTotalResources());
            resourceCounts(other.getResourceCounts());
            tablesPopulated(other.getTablesPopulated());
            codingSystems(other.getCodingSystems());
            codesAlreadyStandard(other.getCodesAlreadyStandard());
            codesNormalized(other.getCodesNormalized());
            codesUnmapped(other.getCodesUnmapped());
            offVocabRate(other.getOffVocabRate());
            droppedResources(other.getDroppedResources());
            resolvedVocabVersion(other.getResolvedVocabVersion());
            conceptResolverNote(other.getConceptResolverNote());
            conceptsBridged(other.getConceptsBridged());
            conceptCandidatesTruncated(other.getConceptCandidatesTruncated());
            construeResolutions(other.getConstrueResolutions());
            return this;
        }

        @JsonSetter(value = "total_resources", nulls = Nulls.SKIP)
        public Builder totalResources(Optional<Integer> totalResources) {
            this.totalResources = totalResources;
            return this;
        }

        public Builder totalResources(Integer totalResources) {
            this.totalResources = Optional.ofNullable(totalResources);
            return this;
        }

        @JsonSetter(value = "resource_counts", nulls = Nulls.SKIP)
        public Builder resourceCounts(Optional<Map<String, Integer>> resourceCounts) {
            this.resourceCounts = resourceCounts;
            return this;
        }

        public Builder resourceCounts(Map<String, Integer> resourceCounts) {
            this.resourceCounts = Optional.ofNullable(resourceCounts);
            return this;
        }

        @JsonSetter(value = "tables_populated", nulls = Nulls.SKIP)
        public Builder tablesPopulated(Optional<Map<String, Integer>> tablesPopulated) {
            this.tablesPopulated = tablesPopulated;
            return this;
        }

        public Builder tablesPopulated(Map<String, Integer> tablesPopulated) {
            this.tablesPopulated = Optional.ofNullable(tablesPopulated);
            return this;
        }

        @JsonSetter(value = "coding_systems", nulls = Nulls.SKIP)
        public Builder codingSystems(Optional<Map<String, Integer>> codingSystems) {
            this.codingSystems = codingSystems;
            return this;
        }

        public Builder codingSystems(Map<String, Integer> codingSystems) {
            this.codingSystems = Optional.ofNullable(codingSystems);
            return this;
        }

        @JsonSetter(value = "codes_already_standard", nulls = Nulls.SKIP)
        public Builder codesAlreadyStandard(Optional<Integer> codesAlreadyStandard) {
            this.codesAlreadyStandard = codesAlreadyStandard;
            return this;
        }

        public Builder codesAlreadyStandard(Integer codesAlreadyStandard) {
            this.codesAlreadyStandard = Optional.ofNullable(codesAlreadyStandard);
            return this;
        }

        @JsonSetter(value = "codes_normalized", nulls = Nulls.SKIP)
        public Builder codesNormalized(Optional<Integer> codesNormalized) {
            this.codesNormalized = codesNormalized;
            return this;
        }

        public Builder codesNormalized(Integer codesNormalized) {
            this.codesNormalized = Optional.ofNullable(codesNormalized);
            return this;
        }

        @JsonSetter(value = "codes_unmapped", nulls = Nulls.SKIP)
        public Builder codesUnmapped(Optional<Integer> codesUnmapped) {
            this.codesUnmapped = codesUnmapped;
            return this;
        }

        public Builder codesUnmapped(Integer codesUnmapped) {
            this.codesUnmapped = Optional.ofNullable(codesUnmapped);
            return this;
        }

        @JsonSetter(value = "off_vocab_rate", nulls = Nulls.SKIP)
        public Builder offVocabRate(Optional<Double> offVocabRate) {
            this.offVocabRate = offVocabRate;
            return this;
        }

        public Builder offVocabRate(Double offVocabRate) {
            this.offVocabRate = Optional.ofNullable(offVocabRate);
            return this;
        }

        @JsonSetter(value = "dropped_resources", nulls = Nulls.SKIP)
        public Builder droppedResources(Optional<List<DroppedResource>> droppedResources) {
            this.droppedResources = droppedResources;
            return this;
        }

        public Builder droppedResources(List<DroppedResource> droppedResources) {
            this.droppedResources = Optional.ofNullable(droppedResources);
            return this;
        }

        /**
         * <p>OMOP vocabulary release the resolver mapped against (e.g. &quot;v20240229&quot;).
         * Resolved mode only; empty when no coded concept reached the service.</p>
         */
        @JsonSetter(value = "resolved_vocab_version", nulls = Nulls.SKIP)
        public Builder resolvedVocabVersion(Optional<String> resolvedVocabVersion) {
            this.resolvedVocabVersion = resolvedVocabVersion;
            return this;
        }

        public Builder resolvedVocabVersion(String resolvedVocabVersion) {
            this.resolvedVocabVersion = Optional.ofNullable(resolvedVocabVersion);
            return this;
        }

        /**
         * <p>Set when concept resolution was degraded — the resolver was unavailable
         * for one or more codings, whose <code>concept_id</code>s fell back to the structural
         * (construe) tier. Empty when resolution was clean.</p>
         */
        @JsonSetter(value = "concept_resolver_note", nulls = Nulls.SKIP)
        public Builder conceptResolverNote(Optional<String> conceptResolverNote) {
            this.conceptResolverNote = conceptResolverNote;
            return this;
        }

        public Builder conceptResolverNote(String conceptResolverNote) {
            this.conceptResolverNote = Optional.ofNullable(conceptResolverNote);
            return this;
        }

        /**
         * <p>Count of <code>concept_id</code>s chosen via the lower-confidence UMLS-CUI bridge
         * (no direct OMOP crosswalk existed). Resolved mode only.</p>
         */
        @JsonSetter(value = "concepts_bridged", nulls = Nulls.SKIP)
        public Builder conceptsBridged(Optional<Integer> conceptsBridged) {
            this.conceptsBridged = conceptsBridged;
            return this;
        }

        public Builder conceptsBridged(Integer conceptsBridged) {
            this.conceptsBridged = Optional.ofNullable(conceptsBridged);
            return this;
        }

        /**
         * <p>Count of codings whose candidate list the resolver capped, so the best
         * concept may not have been among those returned.</p>
         */
        @JsonSetter(value = "concept_candidates_truncated", nulls = Nulls.SKIP)
        public Builder conceptCandidatesTruncated(Optional<Integer> conceptCandidatesTruncated) {
            this.conceptCandidatesTruncated = conceptCandidatesTruncated;
            return this;
        }

        public Builder conceptCandidatesTruncated(Integer conceptCandidatesTruncated) {
            this.conceptCandidatesTruncated = Optional.ofNullable(conceptCandidatesTruncated);
            return this;
        }

        /**
         * <p>Count of codings resolved via the construe ML extractor — the text-only
         * or availability fallback path. A non-zero value bills the construe tier.</p>
         */
        @JsonSetter(value = "construe_resolutions", nulls = Nulls.SKIP)
        public Builder construeResolutions(Optional<Integer> construeResolutions) {
            this.construeResolutions = construeResolutions;
            return this;
        }

        public Builder construeResolutions(Integer construeResolutions) {
            this.construeResolutions = Optional.ofNullable(construeResolutions);
            return this;
        }

        public ScanSummary build() {
            return new ScanSummary(
                    totalResources,
                    resourceCounts,
                    tablesPopulated,
                    codingSystems,
                    codesAlreadyStandard,
                    codesNormalized,
                    codesUnmapped,
                    offVocabRate,
                    droppedResources,
                    resolvedVocabVersion,
                    conceptResolverNote,
                    conceptsBridged,
                    conceptCandidatesTruncated,
                    construeResolutions,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
