/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.authtoken;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.Suppliers;
import com.phenoml.api.resources.authtoken.auth.AuthClient;
import java.util.function.Supplier;

public class AuthtokenClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AuthClient> authClient;

  public AuthtokenClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.authClient = Suppliers.memoize(() -> new AuthClient(clientOptions));
  }

  public AuthClient auth() {
    return this.authClient.get();
  }
}
