/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.construe;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.construe.requests.ConstrueCohortRequest;
import com.phenoml.api.resources.construe.requests.ExtractRequest;
import com.phenoml.api.resources.construe.requests.UploadRequest;
import com.phenoml.api.resources.construe.types.ConstrueCohortResponse;
import com.phenoml.api.resources.construe.types.ConstrueUploadCodeSystemResponse;
import com.phenoml.api.resources.construe.types.ExtractCodesResult;
import java.util.concurrent.CompletableFuture;

public class AsyncConstrueClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawConstrueClient rawClient;

    public AsyncConstrueClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawConstrueClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawConstrueClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Upload a custom medical code system with codes and descriptions for use in code extraction.
     * Upon upload, construe generates embeddings for all of the codes in the code system and stores them in the vector database so you can
     * subsequently use the code system for construe/extract and lang2fhir/create (coming soon!)
     */
    public CompletableFuture<ConstrueUploadCodeSystemResponse> uploadCodeSystem(UploadRequest request) {
        return this.rawClient.uploadCodeSystem(request).thenApply(response -> response.body());
    }

    /**
     * Upload a custom medical code system with codes and descriptions for use in code extraction.
     * Upon upload, construe generates embeddings for all of the codes in the code system and stores them in the vector database so you can
     * subsequently use the code system for construe/extract and lang2fhir/create (coming soon!)
     */
    public CompletableFuture<ConstrueUploadCodeSystemResponse> uploadCodeSystem(
            UploadRequest request, RequestOptions requestOptions) {
        return this.rawClient.uploadCodeSystem(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Converts natural language text into structured medical codes
     */
    public CompletableFuture<ExtractCodesResult> extractCodes(ExtractRequest request) {
        return this.rawClient.extractCodes(request).thenApply(response -> response.body());
    }

    /**
     * Converts natural language text into structured medical codes
     */
    public CompletableFuture<ExtractCodesResult> extractCodes(ExtractRequest request, RequestOptions requestOptions) {
        return this.rawClient.extractCodes(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Creates a patient cohort based on a natural language description.
     * Translates the description into FHIR search queries and optional SQL queries.
     */
    public CompletableFuture<ConstrueCohortResponse> cohort(ConstrueCohortRequest request) {
        return this.rawClient.cohort(request).thenApply(response -> response.body());
    }

    /**
     * Creates a patient cohort based on a natural language description.
     * Translates the description into FHIR search queries and optional SQL queries.
     */
    public CompletableFuture<ConstrueCohortResponse> cohort(
            ConstrueCohortRequest request, RequestOptions requestOptions) {
        return this.rawClient.cohort(request, requestOptions).thenApply(response -> response.body());
    }
}
