/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.summary.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.resources.summary.types.CreateSummaryRequestMode;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateSummaryRequest.Builder.class)
public final class CreateSummaryRequest {
    private final Optional<CreateSummaryRequestMode> mode;

    private final Optional<String> templateId;

    private final Map<String, Object> fhirResources;

    private final Map<String, Object> additionalProperties;

    private CreateSummaryRequest(
            Optional<CreateSummaryRequestMode> mode,
            Optional<String> templateId,
            Map<String, Object> fhirResources,
            Map<String, Object> additionalProperties) {
        this.mode = mode;
        this.templateId = templateId;
        this.fhirResources = fhirResources;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Summary generation mode:
     * <ul>
     * <li>narrative: Substitute FHIR data into a template (requires template_id)</li>
     * <li>flatten: Flatten FHIR resources for RAG/search (no template needed)</li>
     * <li>ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG</li>
     * </ul>
     */
    @JsonProperty("mode")
    public Optional<CreateSummaryRequestMode> getMode() {
        return mode;
    }

    /**
     * @return ID of the template to use (required for narrative mode)
     */
    @JsonProperty("template_id")
    public Optional<String> getTemplateId() {
        return templateId;
    }

    /**
     * @return FHIR resources (single resource or Bundle).
     * For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
     * identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
     * if multiple Patients are present, or if the Patient has no identifiers. Resources are
     * automatically filtered to only include those referencing the patient.
     */
    @JsonProperty("fhir_resources")
    public Map<String, Object> getFhirResources() {
        return fhirResources;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateSummaryRequest && equalTo((CreateSummaryRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateSummaryRequest other) {
        return mode.equals(other.mode)
                && templateId.equals(other.templateId)
                && fhirResources.equals(other.fhirResources);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.mode, this.templateId, this.fhirResources);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CreateSummaryRequestMode> mode = Optional.empty();

        private Optional<String> templateId = Optional.empty();

        private Map<String, Object> fhirResources = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateSummaryRequest other) {
            mode(other.getMode());
            templateId(other.getTemplateId());
            fhirResources(other.getFhirResources());
            return this;
        }

        /**
         * <p>Summary generation mode:</p>
         * <ul>
         * <li>narrative: Substitute FHIR data into a template (requires template_id)</li>
         * <li>flatten: Flatten FHIR resources for RAG/search (no template needed)</li>
         * <li>ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG</li>
         * </ul>
         */
        @JsonSetter(value = "mode", nulls = Nulls.SKIP)
        public Builder mode(Optional<CreateSummaryRequestMode> mode) {
            this.mode = mode;
            return this;
        }

        public Builder mode(CreateSummaryRequestMode mode) {
            this.mode = Optional.ofNullable(mode);
            return this;
        }

        /**
         * <p>ID of the template to use (required for narrative mode)</p>
         */
        @JsonSetter(value = "template_id", nulls = Nulls.SKIP)
        public Builder templateId(Optional<String> templateId) {
            this.templateId = templateId;
            return this;
        }

        public Builder templateId(String templateId) {
            this.templateId = Optional.ofNullable(templateId);
            return this;
        }

        /**
         * <p>FHIR resources (single resource or Bundle).
         * For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
         * identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
         * if multiple Patients are present, or if the Patient has no identifiers. Resources are
         * automatically filtered to only include those referencing the patient.</p>
         */
        @JsonSetter(value = "fhir_resources", nulls = Nulls.SKIP)
        public Builder fhirResources(Map<String, Object> fhirResources) {
            this.fhirResources.clear();
            if (fhirResources != null) {
                this.fhirResources.putAll(fhirResources);
            }
            return this;
        }

        public Builder putAllFhirResources(Map<String, Object> fhirResources) {
            if (fhirResources != null) {
                this.fhirResources.putAll(fhirResources);
            }
            return this;
        }

        public Builder fhirResources(String key, Object value) {
            this.fhirResources.put(key, value);
            return this;
        }

        public CreateSummaryRequest build() {
            return new CreateSummaryRequest(mode, templateId, fhirResources, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
