/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.summary.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.resources.summary.types.CreateSummaryRequestFhirResources;
import com.phenoml.api.resources.summary.types.CreateSummaryRequestMode;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateSummaryRequest.Builder.class
)
public final class CreateSummaryRequest {
  private final Optional<CreateSummaryRequestMode> mode;

  private final Optional<String> templateId;

  private final CreateSummaryRequestFhirResources fhirResources;

  private final Map<String, Object> additionalProperties;

  private CreateSummaryRequest(Optional<CreateSummaryRequestMode> mode, Optional<String> templateId,
      CreateSummaryRequestFhirResources fhirResources, Map<String, Object> additionalProperties) {
    this.mode = mode;
    this.templateId = templateId;
    this.fhirResources = fhirResources;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Summary generation mode:
   * <ul>
   * <li>narrative: Substitute FHIR data into a template (requires template_id)</li>
   * <li>flatten: Flatten FHIR resources for RAG/search (no template needed)</li>
   * <li>ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG</li>
   * </ul>
   */
  @JsonProperty("mode")
  public Optional<CreateSummaryRequestMode> getMode() {
    return mode;
  }

  /**
   * @return ID of the template to use (required for narrative mode)
   */
  @JsonProperty("template_id")
  public Optional<String> getTemplateId() {
    return templateId;
  }

  /**
   * @return FHIR resources (single resource or Bundle).
   * For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
   * identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
   * if multiple Patients are present, or if the Patient has no identifiers. Resources are
   * automatically filtered to only include those referencing the patient.
   */
  @JsonProperty("fhir_resources")
  public CreateSummaryRequestFhirResources getFhirResources() {
    return fhirResources;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateSummaryRequest && equalTo((CreateSummaryRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateSummaryRequest other) {
    return mode.equals(other.mode) && templateId.equals(other.templateId) && fhirResources.equals(other.fhirResources);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mode, this.templateId, this.fhirResources);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FhirResourcesStage builder() {
    return new Builder();
  }

  public interface FhirResourcesStage {
    /**
     * <p>FHIR resources (single resource or Bundle).
     * For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
     * identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
     * if multiple Patients are present, or if the Patient has no identifiers. Resources are
     * automatically filtered to only include those referencing the patient.</p>
     */
    _FinalStage fhirResources(@NotNull CreateSummaryRequestFhirResources fhirResources);

    Builder from(CreateSummaryRequest other);
  }

  public interface _FinalStage {
    CreateSummaryRequest build();

    /**
     * <p>Summary generation mode:</p>
     * <ul>
     * <li>narrative: Substitute FHIR data into a template (requires template_id)</li>
     * <li>flatten: Flatten FHIR resources for RAG/search (no template needed)</li>
     * <li>ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG</li>
     * </ul>
     */
    _FinalStage mode(Optional<CreateSummaryRequestMode> mode);

    _FinalStage mode(CreateSummaryRequestMode mode);

    /**
     * <p>ID of the template to use (required for narrative mode)</p>
     */
    _FinalStage templateId(Optional<String> templateId);

    _FinalStage templateId(String templateId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FhirResourcesStage, _FinalStage {
    private CreateSummaryRequestFhirResources fhirResources;

    private Optional<String> templateId = Optional.empty();

    private Optional<CreateSummaryRequestMode> mode = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateSummaryRequest other) {
      mode(other.getMode());
      templateId(other.getTemplateId());
      fhirResources(other.getFhirResources());
      return this;
    }

    /**
     * <p>FHIR resources (single resource or Bundle).
     * For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
     * identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
     * if multiple Patients are present, or if the Patient has no identifiers. Resources are
     * automatically filtered to only include those referencing the patient.</p>
     * <p>FHIR resources (single resource or Bundle).
     * For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
     * identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
     * if multiple Patients are present, or if the Patient has no identifiers. Resources are
     * automatically filtered to only include those referencing the patient.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("fhir_resources")
    public _FinalStage fhirResources(@NotNull CreateSummaryRequestFhirResources fhirResources) {
      this.fhirResources = Objects.requireNonNull(fhirResources, "fhirResources must not be null");
      return this;
    }

    /**
     * <p>ID of the template to use (required for narrative mode)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage templateId(String templateId) {
      this.templateId = Optional.ofNullable(templateId);
      return this;
    }

    /**
     * <p>ID of the template to use (required for narrative mode)</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "template_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage templateId(Optional<String> templateId) {
      this.templateId = templateId;
      return this;
    }

    /**
     * <p>Summary generation mode:</p>
     * <ul>
     * <li>narrative: Substitute FHIR data into a template (requires template_id)</li>
     * <li>flatten: Flatten FHIR resources for RAG/search (no template needed)</li>
     * <li>ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG</li>
     * </ul>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage mode(CreateSummaryRequestMode mode) {
      this.mode = Optional.ofNullable(mode);
      return this;
    }

    /**
     * <p>Summary generation mode:</p>
     * <ul>
     * <li>narrative: Substitute FHIR data into a template (requires template_id)</li>
     * <li>flatten: Flatten FHIR resources for RAG/search (no template needed)</li>
     * <li>ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG</li>
     * </ul>
     */
    @java.lang.Override
    @JsonSetter(
        value = "mode",
        nulls = Nulls.SKIP
    )
    public _FinalStage mode(Optional<CreateSummaryRequestMode> mode) {
      this.mode = mode;
      return this;
    }

    @java.lang.Override
    public CreateSummaryRequest build() {
      return new CreateSummaryRequest(mode, templateId, fhirResources, additionalProperties);
    }
  }
}
