/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.voice;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.Suppliers;
import java.util.function.Supplier;

public class VoiceClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<com.phenoml.api.resources.voice.voice.VoiceClient> voiceClient;

    public VoiceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.voiceClient =
                Suppliers.memoize(() -> new com.phenoml.api.resources.voice.voice.VoiceClient(clientOptions));
    }

    public com.phenoml.api.resources.voice.voice.VoiceClient voice() {
        return this.voiceClient.get();
    }
}
