/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.fhir.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FhirBundle.Builder.class
)
public final class FhirBundle {
  private final Optional<Integer> total;

  private final List<FhirBundleEntryItem> entry;

  private final Map<String, Object> additionalProperties;

  private FhirBundle(Optional<Integer> total, List<FhirBundleEntryItem> entry,
      Map<String, Object> additionalProperties) {
    this.total = total;
    this.entry = entry;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Always &quot;Bundle&quot; for bundle resources
   */
  @JsonProperty("resourceType")
  public String getResourceType() {
    return "Bundle";
  }

  /**
   * @return Total number of resources that match the search criteria.
   * Optional field as not all FHIR servers include it (e.g., Medplum).
   */
  @JsonProperty("total")
  public Optional<Integer> getTotal() {
    return total;
  }

  /**
   * @return Array of bundle entries containing resources or operation results
   */
  @JsonProperty("entry")
  public List<FhirBundleEntryItem> getEntry() {
    return entry;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FhirBundle && equalTo((FhirBundle) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FhirBundle other) {
    return total.equals(other.total) && entry.equals(other.entry);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.total, this.entry);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> total = Optional.empty();

    private List<FhirBundleEntryItem> entry = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(FhirBundle other) {
      total(other.getTotal());
      entry(other.getEntry());
      return this;
    }

    /**
     * <p>Total number of resources that match the search criteria.
     * Optional field as not all FHIR servers include it (e.g., Medplum).</p>
     */
    @JsonSetter(
        value = "total",
        nulls = Nulls.SKIP
    )
    public Builder total(Optional<Integer> total) {
      this.total = total;
      return this;
    }

    public Builder total(Integer total) {
      this.total = Optional.ofNullable(total);
      return this;
    }

    /**
     * <p>Array of bundle entries containing resources or operation results</p>
     */
    @JsonSetter(
        value = "entry",
        nulls = Nulls.SKIP
    )
    public Builder entry(List<FhirBundleEntryItem> entry) {
      this.entry.clear();
      if (entry != null) {
        this.entry.addAll(entry);
      }
      return this;
    }

    public Builder addEntry(FhirBundleEntryItem entry) {
      this.entry.add(entry);
      return this;
    }

    public Builder addAllEntry(List<FhirBundleEntryItem> entry) {
      if (entry != null) {
        this.entry.addAll(entry);
      }
      return this;
    }

    public FhirBundle build() {
      return new FhirBundle(total, entry, additionalProperties);
    }
  }
}
