/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FhirPatchRequestBodyItem.Builder.class)
public final class FhirPatchRequestBodyItem {
    private final Op op;

    private final String path;

    private final Optional<Object> value;

    private final Optional<String> from;

    private final Map<String, Object> additionalProperties;

    private FhirPatchRequestBodyItem(
            Op op,
            String path,
            Optional<Object> value,
            Optional<String> from,
            Map<String, Object> additionalProperties) {
        this.op = op;
        this.path = path;
        this.value = value;
        this.from = from;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The operation to perform
     */
    @JsonProperty("op")
    public Op getOp() {
        return op;
    }

    /**
     * @return JSON Pointer to the target location
     */
    @JsonProperty("path")
    public String getPath() {
        return path;
    }

    @JsonProperty("value")
    public Optional<Object> getValue() {
        return value;
    }

    /**
     * @return Source location for move and copy operations (JSON Pointer)
     */
    @JsonProperty("from")
    public Optional<String> getFrom() {
        return from;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FhirPatchRequestBodyItem && equalTo((FhirPatchRequestBodyItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FhirPatchRequestBodyItem other) {
        return op.equals(other.op) && path.equals(other.path) && value.equals(other.value) && from.equals(other.from);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.op, this.path, this.value, this.from);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OpStage builder() {
        return new Builder();
    }

    public interface OpStage {
        /**
         * <p>The operation to perform</p>
         */
        PathStage op(@NotNull Op op);

        Builder from(FhirPatchRequestBodyItem other);
    }

    public interface PathStage {
        /**
         * <p>JSON Pointer to the target location</p>
         */
        _FinalStage path(@NotNull String path);
    }

    public interface _FinalStage {
        FhirPatchRequestBodyItem build();

        _FinalStage value(Optional<Object> value);

        _FinalStage value(Object value);

        /**
         * <p>Source location for move and copy operations (JSON Pointer)</p>
         */
        _FinalStage from(Optional<String> from);

        _FinalStage from(String from);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OpStage, PathStage, _FinalStage {
        private Op op;

        private String path;

        private Optional<String> from = Optional.empty();

        private Optional<Object> value = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FhirPatchRequestBodyItem other) {
            op(other.getOp());
            path(other.getPath());
            value(other.getValue());
            from(other.getFrom());
            return this;
        }

        /**
         * <p>The operation to perform</p>
         * <p>The operation to perform</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("op")
        public PathStage op(@NotNull Op op) {
            this.op = Objects.requireNonNull(op, "op must not be null");
            return this;
        }

        /**
         * <p>JSON Pointer to the target location</p>
         * <p>JSON Pointer to the target location</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("path")
        public _FinalStage path(@NotNull String path) {
            this.path = Objects.requireNonNull(path, "path must not be null");
            return this;
        }

        /**
         * <p>Source location for move and copy operations (JSON Pointer)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage from(String from) {
            this.from = Optional.ofNullable(from);
            return this;
        }

        /**
         * <p>Source location for move and copy operations (JSON Pointer)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "from", nulls = Nulls.SKIP)
        public _FinalStage from(Optional<String> from) {
            this.from = from;
            return this;
        }

        @java.lang.Override
        public _FinalStage value(Object value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public _FinalStage value(Optional<Object> value) {
            this.value = value;
            return this;
        }

        @java.lang.Override
        public FhirPatchRequestBodyItem build() {
            return new FhirPatchRequestBodyItem(op, path, value, from, additionalProperties);
        }
    }

    public static final class Op {
        public static final Op ADD = new Op(Value.ADD, "add");

        public static final Op REMOVE = new Op(Value.REMOVE, "remove");

        public static final Op TEST = new Op(Value.TEST, "test");

        public static final Op REPLACE = new Op(Value.REPLACE, "replace");

        public static final Op MOVE = new Op(Value.MOVE, "move");

        public static final Op COPY = new Op(Value.COPY, "copy");

        private final Value value;

        private final String string;

        Op(Value value, String string) {
            this.value = value;
            this.string = string;
        }

        public Value getEnumValue() {
            return value;
        }

        @java.lang.Override
        @JsonValue
        public String toString() {
            return this.string;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            return (this == other) || (other instanceof Op && this.string.equals(((Op) other).string));
        }

        @java.lang.Override
        public int hashCode() {
            return this.string.hashCode();
        }

        public <T> T visit(Visitor<T> visitor) {
            switch (value) {
                case ADD:
                    return visitor.visitAdd();
                case REMOVE:
                    return visitor.visitRemove();
                case TEST:
                    return visitor.visitTest();
                case REPLACE:
                    return visitor.visitReplace();
                case MOVE:
                    return visitor.visitMove();
                case COPY:
                    return visitor.visitCopy();
                case UNKNOWN:
                default:
                    return visitor.visitUnknown(string);
            }
        }

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public static Op valueOf(String value) {
            switch (value) {
                case "add":
                    return ADD;
                case "remove":
                    return REMOVE;
                case "test":
                    return TEST;
                case "replace":
                    return REPLACE;
                case "move":
                    return MOVE;
                case "copy":
                    return COPY;
                default:
                    return new Op(Value.UNKNOWN, value);
            }
        }

        public enum Value {
            ADD,

            REMOVE,

            REPLACE,

            MOVE,

            COPY,

            TEST,

            UNKNOWN
        }

        public interface Visitor<T> {
            T visitAdd();

            T visitRemove();

            T visitReplace();

            T visitMove();

            T visitCopy();

            T visitTest();

            T visitUnknown(String unknownType);
        }
    }
}
