/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.MediaTypes;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.core.PhenoMLApiException;
import com.phenoml.api.core.PhenoMLException;
import com.phenoml.api.core.PhenoMLHttpResponse;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.tools.errors.BadRequestError;
import com.phenoml.api.resources.tools.errors.FailedDependencyError;
import com.phenoml.api.resources.tools.errors.ForbiddenError;
import com.phenoml.api.resources.tools.errors.InternalServerError;
import com.phenoml.api.resources.tools.errors.UnauthorizedError;
import com.phenoml.api.resources.tools.requests.CohortRequest;
import com.phenoml.api.resources.tools.requests.Lang2FhirAndCreateMultiRequest;
import com.phenoml.api.resources.tools.requests.Lang2FhirAndCreateRequest;
import com.phenoml.api.resources.tools.requests.Lang2FhirAndSearchRequest;
import com.phenoml.api.resources.tools.types.CohortResponse;
import com.phenoml.api.resources.tools.types.Lang2FhirAndCreateMultiResponse;
import com.phenoml.api.resources.tools.types.Lang2FhirAndCreateResponse;
import com.phenoml.api.resources.tools.types.Lang2FhirAndSearchResponse;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawToolsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawToolsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Converts natural language to FHIR resource and optionally stores it in a FHIR server
   */
  public CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndCreateResponse>> createFhirResource(
      Lang2FhirAndCreateRequest request) {
    return createFhirResource(request,null);
  }

  /**
   * Converts natural language to FHIR resource and optionally stores it in a FHIR server
   */
  public CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndCreateResponse>> createFhirResource(
      Lang2FhirAndCreateRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("tools/lang2fhir-and-create");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      if (request.getPhenomlOnBehalfOf().isPresent()) {
        _requestBuilder.addHeader("X-Phenoml-On-Behalf-Of", request.getPhenomlOnBehalfOf().get());
      }
      if (request.getPhenomlFhirProvider().isPresent()) {
        _requestBuilder.addHeader("X-Phenoml-Fhir-Provider", request.getPhenomlFhirProvider().get());
      }
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndCreateResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Lang2FhirAndCreateResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 424:future.completeExceptionally(new FailedDependencyError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Extracts multiple FHIR resources from natural language text and stores them in a FHIR server.
     * Automatically detects Patient, Condition, MedicationRequest, Observation, and other resource types.
     * Resources are linked with proper references and submitted as a transaction bundle.
     * For FHIR servers that don't auto-resolve urn:uuid references, this endpoint will automatically
     * resolve them via PUT requests after the initial bundle creation.
     */
    public CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndCreateMultiResponse>> createFhirResourcesMulti(
        Lang2FhirAndCreateMultiRequest request) {
      return createFhirResourcesMulti(request,null);
    }

    /**
     * Extracts multiple FHIR resources from natural language text and stores them in a FHIR server.
     * Automatically detects Patient, Condition, MedicationRequest, Observation, and other resource types.
     * Resources are linked with proper references and submitted as a transaction bundle.
     * For FHIR servers that don't auto-resolve urn:uuid references, this endpoint will automatically
     * resolve them via PUT requests after the initial bundle creation.
     */
    public CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndCreateMultiResponse>> createFhirResourcesMulti(
        Lang2FhirAndCreateMultiRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("tools/lang2fhir-and-create-multi");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        if (request.getPhenomlOnBehalfOf().isPresent()) {
          _requestBuilder.addHeader("X-Phenoml-On-Behalf-Of", request.getPhenomlOnBehalfOf().get());
        }
        if (request.getPhenomlFhirProvider().isPresent()) {
          _requestBuilder.addHeader("X-Phenoml-Fhir-Provider", request.getPhenomlFhirProvider().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndCreateMultiResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Lang2FhirAndCreateMultiResponse.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 424:future.completeExceptionally(new FailedDependencyError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Converts natural language to FHIR search parameters and executes search in FHIR server
       */
      public CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndSearchResponse>> searchFhirResources(
          Lang2FhirAndSearchRequest request) {
        return searchFhirResources(request,null);
      }

      /**
       * Converts natural language to FHIR search parameters and executes search in FHIR server
       */
      public CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndSearchResponse>> searchFhirResources(
          Lang2FhirAndSearchRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("tools/lang2fhir-and-search");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(Exception e) {
            throw new RuntimeException(e);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json");
          if (request.getPhenomlOnBehalfOf().isPresent()) {
            _requestBuilder.addHeader("X-Phenoml-On-Behalf-Of", request.getPhenomlOnBehalfOf().get());
          }
          if (request.getPhenomlFhirProvider().isPresent()) {
            _requestBuilder.addHeader("X-Phenoml-Fhir-Provider", request.getPhenomlFhirProvider().get());
          }
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<PhenoMLHttpResponse<Lang2FhirAndSearchResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Lang2FhirAndSearchResponse.class), response));
                  return;
                }
                try {
                  switch (response.code()) {
                    case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 424:future.completeExceptionally(new FailedDependencyError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * Uses LLM to extract search concepts from natural language and builds patient cohorts with inclusion/exclusion criteria
         */
        public CompletableFuture<PhenoMLHttpResponse<CohortResponse>> analyzeCohort(
            CohortRequest request) {
          return analyzeCohort(request,null);
        }

        /**
         * Uses LLM to extract search concepts from natural language and builds patient cohorts with inclusion/exclusion criteria
         */
        public CompletableFuture<PhenoMLHttpResponse<CohortResponse>> analyzeCohort(
            CohortRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("tools/cohort");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(Exception e) {
              throw new RuntimeException(e);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json");
            if (request.getPhenomlOnBehalfOf().isPresent()) {
              _requestBuilder.addHeader("X-Phenoml-On-Behalf-Of", request.getPhenomlOnBehalfOf().get());
            }
            if (request.getPhenomlFhirProvider().isPresent()) {
              _requestBuilder.addHeader("X-Phenoml-Fhir-Provider", request.getPhenomlFhirProvider().get());
            }
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<PhenoMLHttpResponse<CohortResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new PhenoMLHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CohortResponse.class), response));
                    return;
                  }
                  try {
                    switch (response.code()) {
                      case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                      case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new PhenoMLApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PhenoMLException("Network error executing HTTP request", e));
              }
            });
            return future;
          }
        }
