/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.workflows;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.core.Suppliers;
import com.phenoml.api.resources.workflows.mcpserver.McpServerClient;
import java.util.function.Supplier;

public class WorkflowsClient {
    protected final ClientOptions clientOptions;

    private final RawWorkflowsClient rawClient;

    protected final Supplier<com.phenoml.api.resources.workflows.workflows.WorkflowsClient> workflowsClient;

    protected final Supplier<McpServerClient> mcpServerClient;

    public WorkflowsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawWorkflowsClient(clientOptions);
        this.workflowsClient = Suppliers.memoize(
                () -> new com.phenoml.api.resources.workflows.workflows.WorkflowsClient(clientOptions));
        this.mcpServerClient = Suppliers.memoize(() -> new McpServerClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawWorkflowsClient withRawResponse() {
        return this.rawClient;
    }

    public void createFhirResource() {
        this.rawClient.createFhirResource().body();
    }

    public void createFhirResource(RequestOptions requestOptions) {
        this.rawClient.createFhirResource(requestOptions).body();
    }

    public void searchFhirResources() {
        this.rawClient.searchFhirResources().body();
    }

    public void searchFhirResources(RequestOptions requestOptions) {
        this.rawClient.searchFhirResources(requestOptions).body();
    }

    public void analyzeCohort() {
        this.rawClient.analyzeCohort().body();
    }

    public void analyzeCohort(RequestOptions requestOptions) {
        this.rawClient.analyzeCohort(requestOptions).body();
    }

    public com.phenoml.api.resources.workflows.workflows.WorkflowsClient workflows() {
        return this.workflowsClient.get();
    }

    public McpServerClient mcpServer() {
        return this.mcpServerClient.get();
    }
}
