/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir2omop;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.fhir2omop.requests.CreateOmopRequest;
import com.phenoml.api.resources.fhir2omop.types.CreateOmopResponse;

public class Fhir2OmopClient {
    protected final ClientOptions clientOptions;

    private final RawFhir2OmopClient rawClient;

    public Fhir2OmopClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawFhir2OmopClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawFhir2OmopClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows
     * (person, visit_occurrence, condition_occurrence, drug_exposure,
     * procedure_occurrence, measurement, observation).
     * <p>Resource support is intentionally limited to the OMOP tables returned by
     * this endpoint:</p>
     * <ul>
     * <li><code>Patient</code> -&gt; <code>person</code></li>
     * <li><code>Encounter</code> -&gt; <code>visit_occurrence</code></li>
     * <li><code>Condition</code> -&gt; <code>condition_occurrence</code></li>
     * <li><code>Procedure</code> -&gt; <code>procedure_occurrence</code></li>
     * <li><code>MedicationRequest</code>, <code>MedicationStatement</code>, and
     * <code>MedicationAdministration</code> -&gt; <code>drug_exposure</code></li>
     * <li><code>Immunization</code> -&gt; <code>drug_exposure</code></li>
     * <li><code>Observation</code> with a numeric <code>valueQuantity</code>, <code>valueInteger</code>, or
     * numeric-looking <code>valueString</code> (for example <code>&quot;&lt;2&quot;</code>) -&gt; <code>measurement</code></li>
     * <li>non-numeric <code>Observation</code> -&gt; <code>observation</code></li>
     * <li><code>AllergyIntolerance</code> -&gt; <code>observation</code></li>
     * </ul>
     * <p><code>Medication</code> is supported only as reference data for medication
     * resources; it is not emitted as its own row because OMOP CDM has no
     * Medication table. Other reference/admin resources such as <code>Practitioner</code>,
     * <code>Organization</code>, <code>Location</code>, <code>Coverage</code>, and <code>Claim</code>, and clinical
     * workflow/document resources such as <code>DiagnosticReport</code>, <code>ServiceRequest</code>,
     * <code>CarePlan</code>, <code>DocumentReference</code>, <code>Composition</code>, <code>Specimen</code>, and
     * <code>DeviceUseStatement</code>, are currently accepted in a Bundle but are not
     * shaped into OMOP rows. Unsupported resource types are ignored rather than
     * listed under <code>dropped</code>; <code>dropped</code> is reserved for supported resource types
     * that were missing the subject/patient, code, or medication reference data
     * needed to produce a valid row.</p>
     * <p>Each resource's primary clinical coding is resolved to a standard OMOP
     * <code>concept_id</code>. Alongside the OMOP rows grouped by table (<code>tables</code>), the
     * response carries <code>mappings</code> (how each source coding resolved, linked back
     * to the row it produced), <code>dropped</code> (resources that could not be shaped
     * into a row), <code>vocab_version</code> (the OMOP vocabulary release codes were
     * resolved against), and a small <code>summary</code> of the resolution outcomes.</p>
     * <p>A <code>concept_id</code> of <code>0</code> is reported, not omitted (OMOP &quot;no matching
     * concept&quot; semantics): it covers both a coding with no standard match
     * (<code>UNMAPPED</code>) and an unverified suggestion for a text-only resource
     * (<code>UNCHECKED</code>). Only the primary clinical coding is resolved, so
     * <code>gender</code>/<code>race</code>/<code>ethnicity</code>/<code>visit</code>/<code>value</code>/<code>unit</code> <code>concept_id</code>s are
     * always <code>0</code>; the one populated non-resolved concept is measurement
     * <code>operator_concept_id</code>, set from a value comparator (<code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code>)
     * rather than the resolver. Each <code>*_source_value</code> carries the verbatim FHIR
     * coding (<code>system#code</code>), and <code>*_type_concept_id</code> is set to <code>32817</code> (EHR).</p>
     * <p>Medication codes are resolved whether they appear inline
     * (<code>medicationCodeableConcept</code>) or via a <code>medicationReference</code> to a contained,
     * relative (<code>Type/id</code>), or bundle-entry (<code>urn:uuid</code>) <code>Medication</code> resource.
     * Resources that cannot be shaped into a row — a medication with no usable
     * code, resolvable reference, or display, or any clinical resource whose
     * subject/patient reference cannot be tied to a person — are reported under
     * <code>dropped</code> rather than emitted as blank rows. The
     * bundle must contain at least one Patient resource.</p>
     */
    public CreateOmopResponse create(CreateOmopRequest request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows
     * (person, visit_occurrence, condition_occurrence, drug_exposure,
     * procedure_occurrence, measurement, observation).
     * <p>Resource support is intentionally limited to the OMOP tables returned by
     * this endpoint:</p>
     * <ul>
     * <li><code>Patient</code> -&gt; <code>person</code></li>
     * <li><code>Encounter</code> -&gt; <code>visit_occurrence</code></li>
     * <li><code>Condition</code> -&gt; <code>condition_occurrence</code></li>
     * <li><code>Procedure</code> -&gt; <code>procedure_occurrence</code></li>
     * <li><code>MedicationRequest</code>, <code>MedicationStatement</code>, and
     * <code>MedicationAdministration</code> -&gt; <code>drug_exposure</code></li>
     * <li><code>Immunization</code> -&gt; <code>drug_exposure</code></li>
     * <li><code>Observation</code> with a numeric <code>valueQuantity</code>, <code>valueInteger</code>, or
     * numeric-looking <code>valueString</code> (for example <code>&quot;&lt;2&quot;</code>) -&gt; <code>measurement</code></li>
     * <li>non-numeric <code>Observation</code> -&gt; <code>observation</code></li>
     * <li><code>AllergyIntolerance</code> -&gt; <code>observation</code></li>
     * </ul>
     * <p><code>Medication</code> is supported only as reference data for medication
     * resources; it is not emitted as its own row because OMOP CDM has no
     * Medication table. Other reference/admin resources such as <code>Practitioner</code>,
     * <code>Organization</code>, <code>Location</code>, <code>Coverage</code>, and <code>Claim</code>, and clinical
     * workflow/document resources such as <code>DiagnosticReport</code>, <code>ServiceRequest</code>,
     * <code>CarePlan</code>, <code>DocumentReference</code>, <code>Composition</code>, <code>Specimen</code>, and
     * <code>DeviceUseStatement</code>, are currently accepted in a Bundle but are not
     * shaped into OMOP rows. Unsupported resource types are ignored rather than
     * listed under <code>dropped</code>; <code>dropped</code> is reserved for supported resource types
     * that were missing the subject/patient, code, or medication reference data
     * needed to produce a valid row.</p>
     * <p>Each resource's primary clinical coding is resolved to a standard OMOP
     * <code>concept_id</code>. Alongside the OMOP rows grouped by table (<code>tables</code>), the
     * response carries <code>mappings</code> (how each source coding resolved, linked back
     * to the row it produced), <code>dropped</code> (resources that could not be shaped
     * into a row), <code>vocab_version</code> (the OMOP vocabulary release codes were
     * resolved against), and a small <code>summary</code> of the resolution outcomes.</p>
     * <p>A <code>concept_id</code> of <code>0</code> is reported, not omitted (OMOP &quot;no matching
     * concept&quot; semantics): it covers both a coding with no standard match
     * (<code>UNMAPPED</code>) and an unverified suggestion for a text-only resource
     * (<code>UNCHECKED</code>). Only the primary clinical coding is resolved, so
     * <code>gender</code>/<code>race</code>/<code>ethnicity</code>/<code>visit</code>/<code>value</code>/<code>unit</code> <code>concept_id</code>s are
     * always <code>0</code>; the one populated non-resolved concept is measurement
     * <code>operator_concept_id</code>, set from a value comparator (<code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code>)
     * rather than the resolver. Each <code>*_source_value</code> carries the verbatim FHIR
     * coding (<code>system#code</code>), and <code>*_type_concept_id</code> is set to <code>32817</code> (EHR).</p>
     * <p>Medication codes are resolved whether they appear inline
     * (<code>medicationCodeableConcept</code>) or via a <code>medicationReference</code> to a contained,
     * relative (<code>Type/id</code>), or bundle-entry (<code>urn:uuid</code>) <code>Medication</code> resource.
     * Resources that cannot be shaped into a row — a medication with no usable
     * code, resolvable reference, or display, or any clinical resource whose
     * subject/patient reference cannot be tied to a person — are reported under
     * <code>dropped</code> rather than emitted as blank rows. The
     * bundle must contain at least one Patient resource.</p>
     */
    public CreateOmopResponse create(CreateOmopRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }
}
