/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.construe.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CodeResponse.Builder.class)
public final class CodeResponse {
    private final String code;

    private final String description;

    private final Optional<String> definition;

    private final Map<String, Object> additionalProperties;

    private CodeResponse(
            String code, String description, Optional<String> definition, Map<String, Object> additionalProperties) {
        this.code = code;
        this.description = description;
        this.definition = definition;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The code identifier
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * @return Short description of the code
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return Extended definition of the code (if available)
     */
    @JsonProperty("definition")
    public Optional<String> getDefinition() {
        return definition;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CodeResponse && equalTo((CodeResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CodeResponse other) {
        return code.equals(other.code) && description.equals(other.description) && definition.equals(other.definition);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.code, this.description, this.definition);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CodeStage builder() {
        return new Builder();
    }

    public interface CodeStage {
        /**
         * <p>The code identifier</p>
         */
        DescriptionStage code(@NotNull String code);

        Builder from(CodeResponse other);
    }

    public interface DescriptionStage {
        /**
         * <p>Short description of the code</p>
         */
        _FinalStage description(@NotNull String description);
    }

    public interface _FinalStage {
        CodeResponse build();

        /**
         * <p>Extended definition of the code (if available)</p>
         */
        _FinalStage definition(Optional<String> definition);

        _FinalStage definition(String definition);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CodeStage, DescriptionStage, _FinalStage {
        private String code;

        private String description;

        private Optional<String> definition = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CodeResponse other) {
            code(other.getCode());
            description(other.getDescription());
            definition(other.getDefinition());
            return this;
        }

        /**
         * <p>The code identifier</p>
         * <p>The code identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code")
        public DescriptionStage code(@NotNull String code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        /**
         * <p>Short description of the code</p>
         * <p>Short description of the code</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public _FinalStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        /**
         * <p>Extended definition of the code (if available)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage definition(String definition) {
            this.definition = Optional.ofNullable(definition);
            return this;
        }

        /**
         * <p>Extended definition of the code (if available)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "definition", nulls = Nulls.SKIP)
        public _FinalStage definition(Optional<String> definition) {
            this.definition = definition;
            return this;
        }

        @java.lang.Override
        public CodeResponse build() {
            return new CodeResponse(code, description, definition, additionalProperties);
        }
    }
}
