/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.construe.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConstrueCohortResponse.Builder.class)
public final class ConstrueCohortResponse {
    private final Optional<List<QueriesItem>> queries;

    private final Optional<String> sql;

    private final Optional<String> cohortDescription;

    private final Map<String, Object> additionalProperties;

    private ConstrueCohortResponse(
            Optional<List<QueriesItem>> queries,
            Optional<String> sql,
            Optional<String> cohortDescription,
            Map<String, Object> additionalProperties) {
        this.queries = queries;
        this.sql = sql;
        this.cohortDescription = cohortDescription;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("queries")
    public Optional<List<QueriesItem>> getQueries() {
        return queries;
    }

    /**
     * @return Generated SQL query when <code>sql_syntax</code> is specified. Variables in curly braces need to be replaced with your actual table names.
     */
    @JsonProperty("sql")
    public Optional<String> getSql() {
        return sql;
    }

    /**
     * @return Echo of the input text description for reference.
     */
    @JsonProperty("cohortDescription")
    public Optional<String> getCohortDescription() {
        return cohortDescription;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConstrueCohortResponse && equalTo((ConstrueCohortResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConstrueCohortResponse other) {
        return queries.equals(other.queries)
                && sql.equals(other.sql)
                && cohortDescription.equals(other.cohortDescription);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.queries, this.sql, this.cohortDescription);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<QueriesItem>> queries = Optional.empty();

        private Optional<String> sql = Optional.empty();

        private Optional<String> cohortDescription = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConstrueCohortResponse other) {
            queries(other.getQueries());
            sql(other.getSql());
            cohortDescription(other.getCohortDescription());
            return this;
        }

        @JsonSetter(value = "queries", nulls = Nulls.SKIP)
        public Builder queries(Optional<List<QueriesItem>> queries) {
            this.queries = queries;
            return this;
        }

        public Builder queries(List<QueriesItem> queries) {
            this.queries = Optional.ofNullable(queries);
            return this;
        }

        /**
         * <p>Generated SQL query when <code>sql_syntax</code> is specified. Variables in curly braces need to be replaced with your actual table names.</p>
         */
        @JsonSetter(value = "sql", nulls = Nulls.SKIP)
        public Builder sql(Optional<String> sql) {
            this.sql = sql;
            return this;
        }

        public Builder sql(String sql) {
            this.sql = Optional.ofNullable(sql);
            return this;
        }

        /**
         * <p>Echo of the input text description for reference.</p>
         */
        @JsonSetter(value = "cohortDescription", nulls = Nulls.SKIP)
        public Builder cohortDescription(Optional<String> cohortDescription) {
            this.cohortDescription = cohortDescription;
            return this;
        }

        public Builder cohortDescription(String cohortDescription) {
            this.cohortDescription = Optional.ofNullable(cohortDescription);
            return this;
        }

        public ConstrueCohortResponse build() {
            return new ConstrueCohortResponse(queries, sql, cohortDescription, additionalProperties);
        }
    }

    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    @JsonDeserialize(builder = QueriesItem.Builder.class)
    public static final class QueriesItem {
        private final Optional<String> resource;

        private final Optional<String> searchParams;

        private final Optional<Boolean> exclude;

        private final Optional<String> rationale;

        private final Optional<List<CodeExtractResultsItem>> codeExtractResults;

        private final Map<String, Object> additionalProperties;

        private QueriesItem(
                Optional<String> resource,
                Optional<String> searchParams,
                Optional<Boolean> exclude,
                Optional<String> rationale,
                Optional<List<CodeExtractResultsItem>> codeExtractResults,
                Map<String, Object> additionalProperties) {
            this.resource = resource;
            this.searchParams = searchParams;
            this.exclude = exclude;
            this.rationale = rationale;
            this.codeExtractResults = codeExtractResults;
            this.additionalProperties = additionalProperties;
        }

        /**
         * @return FHIR resource type (e.g., &quot;Patient&quot;, &quot;Condition&quot;).
         */
        @JsonProperty("resource")
        public Optional<String> getResource() {
            return resource;
        }

        /**
         * @return FHIR search parameters.
         */
        @JsonProperty("searchParams")
        public Optional<String> getSearchParams() {
            return searchParams;
        }

        /**
         * @return Indicates if this is an exclusion criteria.
         */
        @JsonProperty("exclude")
        public Optional<Boolean> getExclude() {
            return exclude;
        }

        /**
         * @return AI-generated explanation for the query component.
         */
        @JsonProperty("rationale")
        public Optional<String> getRationale() {
            return rationale;
        }

        @JsonProperty("codeExtractResults")
        public Optional<List<CodeExtractResultsItem>> getCodeExtractResults() {
            return codeExtractResults;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof QueriesItem && equalTo((QueriesItem) other);
        }

        @JsonAnyGetter
        public Map<String, Object> getAdditionalProperties() {
            return this.additionalProperties;
        }

        private boolean equalTo(QueriesItem other) {
            return resource.equals(other.resource)
                    && searchParams.equals(other.searchParams)
                    && exclude.equals(other.exclude)
                    && rationale.equals(other.rationale)
                    && codeExtractResults.equals(other.codeExtractResults);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(
                    this.resource, this.searchParams, this.exclude, this.rationale, this.codeExtractResults);
        }

        @java.lang.Override
        public String toString() {
            return ObjectMappers.stringify(this);
        }

        public static Builder builder() {
            return new Builder();
        }

        @JsonIgnoreProperties(ignoreUnknown = true)
        public static final class Builder {
            private Optional<String> resource = Optional.empty();

            private Optional<String> searchParams = Optional.empty();

            private Optional<Boolean> exclude = Optional.empty();

            private Optional<String> rationale = Optional.empty();

            private Optional<List<CodeExtractResultsItem>> codeExtractResults = Optional.empty();

            @JsonAnySetter
            private Map<String, Object> additionalProperties = new HashMap<>();

            private Builder() {}

            public Builder from(QueriesItem other) {
                resource(other.getResource());
                searchParams(other.getSearchParams());
                exclude(other.getExclude());
                rationale(other.getRationale());
                codeExtractResults(other.getCodeExtractResults());
                return this;
            }

            /**
             * <p>FHIR resource type (e.g., &quot;Patient&quot;, &quot;Condition&quot;).</p>
             */
            @JsonSetter(value = "resource", nulls = Nulls.SKIP)
            public Builder resource(Optional<String> resource) {
                this.resource = resource;
                return this;
            }

            public Builder resource(String resource) {
                this.resource = Optional.ofNullable(resource);
                return this;
            }

            /**
             * <p>FHIR search parameters.</p>
             */
            @JsonSetter(value = "searchParams", nulls = Nulls.SKIP)
            public Builder searchParams(Optional<String> searchParams) {
                this.searchParams = searchParams;
                return this;
            }

            public Builder searchParams(String searchParams) {
                this.searchParams = Optional.ofNullable(searchParams);
                return this;
            }

            /**
             * <p>Indicates if this is an exclusion criteria.</p>
             */
            @JsonSetter(value = "exclude", nulls = Nulls.SKIP)
            public Builder exclude(Optional<Boolean> exclude) {
                this.exclude = exclude;
                return this;
            }

            public Builder exclude(Boolean exclude) {
                this.exclude = Optional.ofNullable(exclude);
                return this;
            }

            /**
             * <p>AI-generated explanation for the query component.</p>
             */
            @JsonSetter(value = "rationale", nulls = Nulls.SKIP)
            public Builder rationale(Optional<String> rationale) {
                this.rationale = rationale;
                return this;
            }

            public Builder rationale(String rationale) {
                this.rationale = Optional.ofNullable(rationale);
                return this;
            }

            @JsonSetter(value = "codeExtractResults", nulls = Nulls.SKIP)
            public Builder codeExtractResults(Optional<List<CodeExtractResultsItem>> codeExtractResults) {
                this.codeExtractResults = codeExtractResults;
                return this;
            }

            public Builder codeExtractResults(List<CodeExtractResultsItem> codeExtractResults) {
                this.codeExtractResults = Optional.ofNullable(codeExtractResults);
                return this;
            }

            public QueriesItem build() {
                return new QueriesItem(
                        resource, searchParams, exclude, rationale, codeExtractResults, additionalProperties);
            }
        }

        @JsonInclude(JsonInclude.Include.NON_ABSENT)
        @JsonDeserialize(builder = CodeExtractResultsItem.Builder.class)
        public static final class CodeExtractResultsItem {
            private final Optional<String> systemName;

            private final Optional<List<CodesItem>> codes;

            private final Map<String, Object> additionalProperties;

            private CodeExtractResultsItem(
                    Optional<String> systemName,
                    Optional<List<CodesItem>> codes,
                    Map<String, Object> additionalProperties) {
                this.systemName = systemName;
                this.codes = codes;
                this.additionalProperties = additionalProperties;
            }

            /**
             * @return Name of the coding system (e.g., &quot;SNOMED_CT_US_LITE&quot;).
             */
            @JsonProperty("systemName")
            public Optional<String> getSystemName() {
                return systemName;
            }

            @JsonProperty("codes")
            public Optional<List<CodesItem>> getCodes() {
                return codes;
            }

            @java.lang.Override
            public boolean equals(Object other) {
                if (this == other) return true;
                return other instanceof CodeExtractResultsItem && equalTo((CodeExtractResultsItem) other);
            }

            @JsonAnyGetter
            public Map<String, Object> getAdditionalProperties() {
                return this.additionalProperties;
            }

            private boolean equalTo(CodeExtractResultsItem other) {
                return systemName.equals(other.systemName) && codes.equals(other.codes);
            }

            @java.lang.Override
            public int hashCode() {
                return Objects.hash(this.systemName, this.codes);
            }

            @java.lang.Override
            public String toString() {
                return ObjectMappers.stringify(this);
            }

            public static Builder builder() {
                return new Builder();
            }

            @JsonIgnoreProperties(ignoreUnknown = true)
            public static final class Builder {
                private Optional<String> systemName = Optional.empty();

                private Optional<List<CodesItem>> codes = Optional.empty();

                @JsonAnySetter
                private Map<String, Object> additionalProperties = new HashMap<>();

                private Builder() {}

                public Builder from(CodeExtractResultsItem other) {
                    systemName(other.getSystemName());
                    codes(other.getCodes());
                    return this;
                }

                /**
                 * <p>Name of the coding system (e.g., &quot;SNOMED_CT_US_LITE&quot;).</p>
                 */
                @JsonSetter(value = "systemName", nulls = Nulls.SKIP)
                public Builder systemName(Optional<String> systemName) {
                    this.systemName = systemName;
                    return this;
                }

                public Builder systemName(String systemName) {
                    this.systemName = Optional.ofNullable(systemName);
                    return this;
                }

                @JsonSetter(value = "codes", nulls = Nulls.SKIP)
                public Builder codes(Optional<List<CodesItem>> codes) {
                    this.codes = codes;
                    return this;
                }

                public Builder codes(List<CodesItem> codes) {
                    this.codes = Optional.ofNullable(codes);
                    return this;
                }

                public CodeExtractResultsItem build() {
                    return new CodeExtractResultsItem(systemName, codes, additionalProperties);
                }
            }

            @JsonInclude(JsonInclude.Include.NON_ABSENT)
            @JsonDeserialize(builder = CodesItem.Builder.class)
            public static final class CodesItem {
                private final Optional<String> code;

                private final Optional<String> description;

                private final Optional<String> reason;

                private final Map<String, Object> additionalProperties;

                private CodesItem(
                        Optional<String> code,
                        Optional<String> description,
                        Optional<String> reason,
                        Map<String, Object> additionalProperties) {
                    this.code = code;
                    this.description = description;
                    this.reason = reason;
                    this.additionalProperties = additionalProperties;
                }

                /**
                 * @return Medical code.
                 */
                @JsonProperty("code")
                public Optional<String> getCode() {
                    return code;
                }

                /**
                 * @return Description of the medical code.
                 */
                @JsonProperty("description")
                public Optional<String> getDescription() {
                    return description;
                }

                /**
                 * @return Reason for selecting the code.
                 */
                @JsonProperty("reason")
                public Optional<String> getReason() {
                    return reason;
                }

                @java.lang.Override
                public boolean equals(Object other) {
                    if (this == other) return true;
                    return other instanceof CodesItem && equalTo((CodesItem) other);
                }

                @JsonAnyGetter
                public Map<String, Object> getAdditionalProperties() {
                    return this.additionalProperties;
                }

                private boolean equalTo(CodesItem other) {
                    return code.equals(other.code)
                            && description.equals(other.description)
                            && reason.equals(other.reason);
                }

                @java.lang.Override
                public int hashCode() {
                    return Objects.hash(this.code, this.description, this.reason);
                }

                @java.lang.Override
                public String toString() {
                    return ObjectMappers.stringify(this);
                }

                public static Builder builder() {
                    return new Builder();
                }

                @JsonIgnoreProperties(ignoreUnknown = true)
                public static final class Builder {
                    private Optional<String> code = Optional.empty();

                    private Optional<String> description = Optional.empty();

                    private Optional<String> reason = Optional.empty();

                    @JsonAnySetter
                    private Map<String, Object> additionalProperties = new HashMap<>();

                    private Builder() {}

                    public Builder from(CodesItem other) {
                        code(other.getCode());
                        description(other.getDescription());
                        reason(other.getReason());
                        return this;
                    }

                    /**
                     * <p>Medical code.</p>
                     */
                    @JsonSetter(value = "code", nulls = Nulls.SKIP)
                    public Builder code(Optional<String> code) {
                        this.code = code;
                        return this;
                    }

                    public Builder code(String code) {
                        this.code = Optional.ofNullable(code);
                        return this;
                    }

                    /**
                     * <p>Description of the medical code.</p>
                     */
                    @JsonSetter(value = "description", nulls = Nulls.SKIP)
                    public Builder description(Optional<String> description) {
                        this.description = description;
                        return this;
                    }

                    public Builder description(String description) {
                        this.description = Optional.ofNullable(description);
                        return this;
                    }

                    /**
                     * <p>Reason for selecting the code.</p>
                     */
                    @JsonSetter(value = "reason", nulls = Nulls.SKIP)
                    public Builder reason(Optional<String> reason) {
                        this.reason = reason;
                        return this;
                    }

                    public Builder reason(String reason) {
                        this.reason = Optional.ofNullable(reason);
                        return this;
                    }

                    public CodesItem build() {
                        return new CodesItem(code, description, reason, additionalProperties);
                    }
                }
            }
        }
    }
}
