/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.construe.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListCodeSystemsResponse.Builder.class)
public final class ListCodeSystemsResponse {
    private final List<CodeSystemDetails> systems;

    private final Map<String, Object> additionalProperties;

    private ListCodeSystemsResponse(List<CodeSystemDetails> systems, Map<String, Object> additionalProperties) {
        this.systems = systems;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("systems")
    public List<CodeSystemDetails> getSystems() {
        return systems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListCodeSystemsResponse && equalTo((ListCodeSystemsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListCodeSystemsResponse other) {
        return systems.equals(other.systems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.systems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<CodeSystemDetails> systems = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListCodeSystemsResponse other) {
            systems(other.getSystems());
            return this;
        }

        @JsonSetter(value = "systems", nulls = Nulls.SKIP)
        public Builder systems(List<CodeSystemDetails> systems) {
            this.systems.clear();
            this.systems.addAll(systems);
            return this;
        }

        public Builder addSystems(CodeSystemDetails systems) {
            this.systems.add(systems);
            return this;
        }

        public Builder addAllSystems(List<CodeSystemDetails> systems) {
            if (systems != null) {
                this.systems.addAll(systems);
            }
            return this;
        }

        public ListCodeSystemsResponse build() {
            return new ListCodeSystemsResponse(systems, additionalProperties);
        }
    }
}
