/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.construe.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UploadRequestCsv.Builder.class)
public final class UploadRequestCsv {
    private final String name;

    private final String version;

    private final Optional<Double> revision;

    private final String file;

    private final String codeCol;

    private final String descCol;

    private final Optional<String> defnCol;

    private final Optional<Boolean> replace;

    private final Map<String, Object> additionalProperties;

    private UploadRequestCsv(
            String name,
            String version,
            Optional<Double> revision,
            String file,
            String codeCol,
            String descCol,
            Optional<String> defnCol,
            Optional<Boolean> replace,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.version = version;
        this.revision = revision;
        this.file = file;
        this.codeCol = codeCol;
        this.descCol = descCol;
        this.defnCol = defnCol;
        this.replace = replace;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the code system. Names are case-insensitive and stored uppercase.
     * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
     * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Version of the code system
     */
    @JsonProperty("version")
    public String getVersion() {
        return version;
    }

    /**
     * @return Optional revision number
     */
    @JsonProperty("revision")
    public Optional<Double> getRevision() {
        return revision;
    }

    /**
     * @return The CSV file contents as a base64-encoded string.
     */
    @JsonProperty("file")
    public String getFile() {
        return file;
    }

    /**
     * @return Column name containing codes
     */
    @JsonProperty("code_col")
    public String getCodeCol() {
        return codeCol;
    }

    /**
     * @return Column name containing descriptions
     */
    @JsonProperty("desc_col")
    public String getDescCol() {
        return descCol;
    }

    /**
     * @return Optional column name containing long definitions
     */
    @JsonProperty("defn_col")
    public Optional<String> getDefnCol() {
        return defnCol;
    }

    /**
     * @return If true, replaces an existing code system with the same name and version.
     * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
     * When false (default), uploading a duplicate returns 409 Conflict.
     */
    @JsonProperty("replace")
    public Optional<Boolean> getReplace() {
        return replace;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UploadRequestCsv && equalTo((UploadRequestCsv) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UploadRequestCsv other) {
        return name.equals(other.name)
                && version.equals(other.version)
                && revision.equals(other.revision)
                && file.equals(other.file)
                && codeCol.equals(other.codeCol)
                && descCol.equals(other.descCol)
                && defnCol.equals(other.defnCol)
                && replace.equals(other.replace);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.name,
                this.version,
                this.revision,
                this.file,
                this.codeCol,
                this.descCol,
                this.defnCol,
                this.replace);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the code system. Names are case-insensitive and stored uppercase.
         * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
         * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.</p>
         */
        VersionStage name(@NotNull String name);

        Builder from(UploadRequestCsv other);
    }

    public interface VersionStage {
        /**
         * <p>Version of the code system</p>
         */
        FileStage version(@NotNull String version);
    }

    public interface FileStage {
        /**
         * <p>The CSV file contents as a base64-encoded string.</p>
         */
        CodeColStage file(@NotNull String file);
    }

    public interface CodeColStage {
        /**
         * <p>Column name containing codes</p>
         */
        DescColStage codeCol(@NotNull String codeCol);
    }

    public interface DescColStage {
        /**
         * <p>Column name containing descriptions</p>
         */
        _FinalStage descCol(@NotNull String descCol);
    }

    public interface _FinalStage {
        UploadRequestCsv build();

        /**
         * <p>Optional revision number</p>
         */
        _FinalStage revision(Optional<Double> revision);

        _FinalStage revision(Double revision);

        /**
         * <p>Optional column name containing long definitions</p>
         */
        _FinalStage defnCol(Optional<String> defnCol);

        _FinalStage defnCol(String defnCol);

        /**
         * <p>If true, replaces an existing code system with the same name and version.
         * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
         * When false (default), uploading a duplicate returns 409 Conflict.</p>
         */
        _FinalStage replace(Optional<Boolean> replace);

        _FinalStage replace(Boolean replace);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements NameStage, VersionStage, FileStage, CodeColStage, DescColStage, _FinalStage {
        private String name;

        private String version;

        private String file;

        private String codeCol;

        private String descCol;

        private Optional<Boolean> replace = Optional.empty();

        private Optional<String> defnCol = Optional.empty();

        private Optional<Double> revision = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UploadRequestCsv other) {
            name(other.getName());
            version(other.getVersion());
            revision(other.getRevision());
            file(other.getFile());
            codeCol(other.getCodeCol());
            descCol(other.getDescCol());
            defnCol(other.getDefnCol());
            replace(other.getReplace());
            return this;
        }

        /**
         * <p>Name of the code system. Names are case-insensitive and stored uppercase.
         * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
         * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.</p>
         * <p>Name of the code system. Names are case-insensitive and stored uppercase.
         * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
         * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public VersionStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Version of the code system</p>
         * <p>Version of the code system</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("version")
        public FileStage version(@NotNull String version) {
            this.version = Objects.requireNonNull(version, "version must not be null");
            return this;
        }

        /**
         * <p>The CSV file contents as a base64-encoded string.</p>
         * <p>The CSV file contents as a base64-encoded string.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("file")
        public CodeColStage file(@NotNull String file) {
            this.file = Objects.requireNonNull(file, "file must not be null");
            return this;
        }

        /**
         * <p>Column name containing codes</p>
         * <p>Column name containing codes</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code_col")
        public DescColStage codeCol(@NotNull String codeCol) {
            this.codeCol = Objects.requireNonNull(codeCol, "codeCol must not be null");
            return this;
        }

        /**
         * <p>Column name containing descriptions</p>
         * <p>Column name containing descriptions</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("desc_col")
        public _FinalStage descCol(@NotNull String descCol) {
            this.descCol = Objects.requireNonNull(descCol, "descCol must not be null");
            return this;
        }

        /**
         * <p>If true, replaces an existing code system with the same name and version.
         * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
         * When false (default), uploading a duplicate returns 409 Conflict.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage replace(Boolean replace) {
            this.replace = Optional.ofNullable(replace);
            return this;
        }

        /**
         * <p>If true, replaces an existing code system with the same name and version.
         * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
         * When false (default), uploading a duplicate returns 409 Conflict.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "replace", nulls = Nulls.SKIP)
        public _FinalStage replace(Optional<Boolean> replace) {
            this.replace = replace;
            return this;
        }

        /**
         * <p>Optional column name containing long definitions</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage defnCol(String defnCol) {
            this.defnCol = Optional.ofNullable(defnCol);
            return this;
        }

        /**
         * <p>Optional column name containing long definitions</p>
         */
        @java.lang.Override
        @JsonSetter(value = "defn_col", nulls = Nulls.SKIP)
        public _FinalStage defnCol(Optional<String> defnCol) {
            this.defnCol = defnCol;
            return this;
        }

        /**
         * <p>Optional revision number</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage revision(Double revision) {
            this.revision = Optional.ofNullable(revision);
            return this;
        }

        /**
         * <p>Optional revision number</p>
         */
        @java.lang.Override
        @JsonSetter(value = "revision", nulls = Nulls.SKIP)
        public _FinalStage revision(Optional<Double> revision) {
            this.revision = revision;
            return this;
        }

        @java.lang.Override
        public UploadRequestCsv build() {
            return new UploadRequestCsv(
                    name, version, revision, file, codeCol, descCol, defnCol, replace, additionalProperties);
        }
    }
}
