/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.construe.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UploadRequestJson.Builder.class)
public final class UploadRequestJson {
    private final String name;

    private final String version;

    private final Optional<Double> revision;

    private final Optional<String> file;

    private final Optional<List<CodeResponse>> codes;

    private final Optional<Boolean> replace;

    private final Optional<Boolean> async;

    private final Map<String, Object> additionalProperties;

    private UploadRequestJson(
            String name,
            String version,
            Optional<Double> revision,
            Optional<String> file,
            Optional<List<CodeResponse>> codes,
            Optional<Boolean> replace,
            Optional<Boolean> async,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.version = version;
        this.revision = revision;
        this.file = file;
        this.codes = codes;
        this.replace = replace;
        this.async = async;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the code system. Names are case-insensitive and stored uppercase.
     * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
     * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Version of the code system
     */
    @JsonProperty("version")
    public String getVersion() {
        return version;
    }

    /**
     * @return Optional revision number
     */
    @JsonProperty("revision")
    public Optional<Double> getRevision() {
        return revision;
    }

    /**
     * @return The file contents as a base64-encoded JSON array string.
     * Prefer using 'codes' instead to pass the array directly without base64 encoding.
     */
    @JsonProperty("file")
    public Optional<String> getFile() {
        return file;
    }

    /**
     * @return The codes to upload as a JSON array.
     * This is the preferred way to upload JSON codes, as it avoids unnecessary base64 encoding.
     * If both 'codes' and 'file' are provided, 'codes' takes precedence.
     */
    @JsonProperty("codes")
    public Optional<List<CodeResponse>> getCodes() {
        return codes;
    }

    /**
     * @return If true, replaces an existing code system with the same name and version.
     * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
     * When false (default), uploading a duplicate returns 409 Conflict.
     */
    @JsonProperty("replace")
    public Optional<Boolean> getReplace() {
        return replace;
    }

    /**
     * @return If true, returns 202 Accepted immediately after validation and starts processing
     * in the background. Poll GET /construe/codes/systems/{name}?version={version} to
     * check when status transitions from &quot;processing&quot; to &quot;ready&quot; or &quot;failed&quot;.
     */
    @JsonProperty("async")
    public Optional<Boolean> getAsync() {
        return async;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UploadRequestJson && equalTo((UploadRequestJson) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UploadRequestJson other) {
        return name.equals(other.name)
                && version.equals(other.version)
                && revision.equals(other.revision)
                && file.equals(other.file)
                && codes.equals(other.codes)
                && replace.equals(other.replace)
                && async.equals(other.async);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.version, this.revision, this.file, this.codes, this.replace, this.async);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the code system. Names are case-insensitive and stored uppercase.
         * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
         * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.</p>
         */
        VersionStage name(@NotNull String name);

        Builder from(UploadRequestJson other);
    }

    public interface VersionStage {
        /**
         * <p>Version of the code system</p>
         */
        _FinalStage version(@NotNull String version);
    }

    public interface _FinalStage {
        UploadRequestJson build();

        /**
         * <p>Optional revision number</p>
         */
        _FinalStage revision(Optional<Double> revision);

        _FinalStage revision(Double revision);

        /**
         * <p>The file contents as a base64-encoded JSON array string.
         * Prefer using 'codes' instead to pass the array directly without base64 encoding.</p>
         */
        _FinalStage file(Optional<String> file);

        _FinalStage file(String file);

        /**
         * <p>The codes to upload as a JSON array.
         * This is the preferred way to upload JSON codes, as it avoids unnecessary base64 encoding.
         * If both 'codes' and 'file' are provided, 'codes' takes precedence.</p>
         */
        _FinalStage codes(Optional<List<CodeResponse>> codes);

        _FinalStage codes(List<CodeResponse> codes);

        /**
         * <p>If true, replaces an existing code system with the same name and version.
         * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
         * When false (default), uploading a duplicate returns 409 Conflict.</p>
         */
        _FinalStage replace(Optional<Boolean> replace);

        _FinalStage replace(Boolean replace);

        /**
         * <p>If true, returns 202 Accepted immediately after validation and starts processing
         * in the background. Poll GET /construe/codes/systems/{name}?version={version} to
         * check when status transitions from &quot;processing&quot; to &quot;ready&quot; or &quot;failed&quot;.</p>
         */
        _FinalStage async(Optional<Boolean> async);

        _FinalStage async(Boolean async);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, VersionStage, _FinalStage {
        private String name;

        private String version;

        private Optional<Boolean> async = Optional.empty();

        private Optional<Boolean> replace = Optional.empty();

        private Optional<List<CodeResponse>> codes = Optional.empty();

        private Optional<String> file = Optional.empty();

        private Optional<Double> revision = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UploadRequestJson other) {
            name(other.getName());
            version(other.getVersion());
            revision(other.getRevision());
            file(other.getFile());
            codes(other.getCodes());
            replace(other.getReplace());
            async(other.getAsync());
            return this;
        }

        /**
         * <p>Name of the code system. Names are case-insensitive and stored uppercase.
         * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
         * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.</p>
         * <p>Name of the code system. Names are case-insensitive and stored uppercase.
         * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
         * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public VersionStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Version of the code system</p>
         * <p>Version of the code system</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("version")
        public _FinalStage version(@NotNull String version) {
            this.version = Objects.requireNonNull(version, "version must not be null");
            return this;
        }

        /**
         * <p>If true, returns 202 Accepted immediately after validation and starts processing
         * in the background. Poll GET /construe/codes/systems/{name}?version={version} to
         * check when status transitions from &quot;processing&quot; to &quot;ready&quot; or &quot;failed&quot;.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage async(Boolean async) {
            this.async = Optional.ofNullable(async);
            return this;
        }

        /**
         * <p>If true, returns 202 Accepted immediately after validation and starts processing
         * in the background. Poll GET /construe/codes/systems/{name}?version={version} to
         * check when status transitions from &quot;processing&quot; to &quot;ready&quot; or &quot;failed&quot;.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "async", nulls = Nulls.SKIP)
        public _FinalStage async(Optional<Boolean> async) {
            this.async = async;
            return this;
        }

        /**
         * <p>If true, replaces an existing code system with the same name and version.
         * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
         * When false (default), uploading a duplicate returns 409 Conflict.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage replace(Boolean replace) {
            this.replace = Optional.ofNullable(replace);
            return this;
        }

        /**
         * <p>If true, replaces an existing code system with the same name and version.
         * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
         * When false (default), uploading a duplicate returns 409 Conflict.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "replace", nulls = Nulls.SKIP)
        public _FinalStage replace(Optional<Boolean> replace) {
            this.replace = replace;
            return this;
        }

        /**
         * <p>The codes to upload as a JSON array.
         * This is the preferred way to upload JSON codes, as it avoids unnecessary base64 encoding.
         * If both 'codes' and 'file' are provided, 'codes' takes precedence.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage codes(List<CodeResponse> codes) {
            this.codes = Optional.ofNullable(codes);
            return this;
        }

        /**
         * <p>The codes to upload as a JSON array.
         * This is the preferred way to upload JSON codes, as it avoids unnecessary base64 encoding.
         * If both 'codes' and 'file' are provided, 'codes' takes precedence.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "codes", nulls = Nulls.SKIP)
        public _FinalStage codes(Optional<List<CodeResponse>> codes) {
            this.codes = codes;
            return this;
        }

        /**
         * <p>The file contents as a base64-encoded JSON array string.
         * Prefer using 'codes' instead to pass the array directly without base64 encoding.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage file(String file) {
            this.file = Optional.ofNullable(file);
            return this;
        }

        /**
         * <p>The file contents as a base64-encoded JSON array string.
         * Prefer using 'codes' instead to pass the array directly without base64 encoding.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "file", nulls = Nulls.SKIP)
        public _FinalStage file(Optional<String> file) {
            this.file = file;
            return this;
        }

        /**
         * <p>Optional revision number</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage revision(Double revision) {
            this.revision = Optional.ofNullable(revision);
            return this;
        }

        /**
         * <p>Optional revision number</p>
         */
        @java.lang.Override
        @JsonSetter(value = "revision", nulls = Nulls.SKIP)
        public _FinalStage revision(Optional<Double> revision) {
            this.revision = revision;
            return this;
        }

        @java.lang.Override
        public UploadRequestJson build() {
            return new UploadRequestJson(name, version, revision, file, codes, replace, async, additionalProperties);
        }
    }
}
