/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.agent;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.core.Suppliers;
import com.phenoml.api.resources.agent.chat.AsyncChatClient;
import com.phenoml.api.resources.agent.requests.AgentPromptsCreateRequest;
import com.phenoml.api.resources.agent.requests.AgentPromptsUpdateRequest;
import com.phenoml.api.resources.agent.types.AgentPromptsResponse;
import com.phenoml.api.resources.agent.types.JsonPatchOperation;
import com.phenoml.api.resources.agent.types.PromptsDeleteResponse;
import com.phenoml.api.resources.agent.types.PromptsListResponse;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncAgentClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAgentClient rawClient;

    protected final Supplier<AsyncChatClient> chatClient;

    public AsyncAgentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAgentClient(clientOptions);
        this.chatClient = Suppliers.memoize(() -> new AsyncChatClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAgentClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Creates a new agent prompt
     */
    public CompletableFuture<AgentPromptsResponse> create(AgentPromptsCreateRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Creates a new agent prompt
     */
    public CompletableFuture<AgentPromptsResponse> create(
            AgentPromptsCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a list of agent prompts belonging to the authenticated user
     */
    public CompletableFuture<PromptsListResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieves a list of agent prompts belonging to the authenticated user
     */
    public CompletableFuture<PromptsListResponse> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a specific prompt by its ID
     */
    public CompletableFuture<AgentPromptsResponse> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    /**
     * Retrieves a specific prompt by its ID
     */
    public CompletableFuture<AgentPromptsResponse> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates an existing prompt
     */
    public CompletableFuture<AgentPromptsResponse> update(String id) {
        return this.rawClient.update(id).thenApply(response -> response.body());
    }

    /**
     * Updates an existing prompt
     */
    public CompletableFuture<AgentPromptsResponse> update(String id, RequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates an existing prompt
     */
    public CompletableFuture<AgentPromptsResponse> update(String id, AgentPromptsUpdateRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Updates an existing prompt
     */
    public CompletableFuture<AgentPromptsResponse> update(
            String id, AgentPromptsUpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes a prompt
     */
    public CompletableFuture<PromptsDeleteResponse> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Deletes a prompt
     */
    public CompletableFuture<PromptsDeleteResponse> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Patches an existing prompt
     */
    public CompletableFuture<AgentPromptsResponse> patch(String id, List<JsonPatchOperation> request) {
        return this.rawClient.patch(id, request).thenApply(response -> response.body());
    }

    /**
     * Patches an existing prompt
     */
    public CompletableFuture<AgentPromptsResponse> patch(
            String id, List<JsonPatchOperation> request, RequestOptions requestOptions) {
        return this.rawClient.patch(id, request, requestOptions).thenApply(response -> response.body());
    }

    public AsyncChatClient chat() {
        return this.chatClient.get();
    }
}
