/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.agent.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentChatRequest.Builder.class)
public final class AgentChatRequest {
    private final String message;

    private final Optional<String> context;

    private final Optional<String> sessionId;

    private final String agentId;

    private final Map<String, Object> additionalProperties;

    private AgentChatRequest(
            String message,
            Optional<String> context,
            Optional<String> sessionId,
            String agentId,
            Map<String, Object> additionalProperties) {
        this.message = message;
        this.context = context;
        this.sessionId = sessionId;
        this.agentId = agentId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The message to send to the agent
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return Optional context for the conversation
     */
    @JsonProperty("context")
    public Optional<String> getContext() {
        return context;
    }

    /**
     * @return Optional session ID for conversation continuity
     */
    @JsonProperty("session_id")
    public Optional<String> getSessionId() {
        return sessionId;
    }

    /**
     * @return The ID of the agent to chat with
     */
    @JsonProperty("agent_id")
    public String getAgentId() {
        return agentId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentChatRequest && equalTo((AgentChatRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentChatRequest other) {
        return message.equals(other.message)
                && context.equals(other.context)
                && sessionId.equals(other.sessionId)
                && agentId.equals(other.agentId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.message, this.context, this.sessionId, this.agentId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MessageStage builder() {
        return new Builder();
    }

    public interface MessageStage {
        /**
         * <p>The message to send to the agent</p>
         */
        AgentIdStage message(@NotNull String message);

        Builder from(AgentChatRequest other);
    }

    public interface AgentIdStage {
        /**
         * <p>The ID of the agent to chat with</p>
         */
        _FinalStage agentId(@NotNull String agentId);
    }

    public interface _FinalStage {
        AgentChatRequest build();

        /**
         * <p>Optional context for the conversation</p>
         */
        _FinalStage context(Optional<String> context);

        _FinalStage context(String context);

        /**
         * <p>Optional session ID for conversation continuity</p>
         */
        _FinalStage sessionId(Optional<String> sessionId);

        _FinalStage sessionId(String sessionId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MessageStage, AgentIdStage, _FinalStage {
        private String message;

        private String agentId;

        private Optional<String> sessionId = Optional.empty();

        private Optional<String> context = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentChatRequest other) {
            message(other.getMessage());
            context(other.getContext());
            sessionId(other.getSessionId());
            agentId(other.getAgentId());
            return this;
        }

        /**
         * <p>The message to send to the agent</p>
         * <p>The message to send to the agent</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public AgentIdStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        /**
         * <p>The ID of the agent to chat with</p>
         * <p>The ID of the agent to chat with</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("agent_id")
        public _FinalStage agentId(@NotNull String agentId) {
            this.agentId = Objects.requireNonNull(agentId, "agentId must not be null");
            return this;
        }

        /**
         * <p>Optional session ID for conversation continuity</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sessionId(String sessionId) {
            this.sessionId = Optional.ofNullable(sessionId);
            return this;
        }

        /**
         * <p>Optional session ID for conversation continuity</p>
         */
        @java.lang.Override
        @JsonSetter(value = "session_id", nulls = Nulls.SKIP)
        public _FinalStage sessionId(Optional<String> sessionId) {
            this.sessionId = sessionId;
            return this;
        }

        /**
         * <p>Optional context for the conversation</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage context(String context) {
            this.context = Optional.ofNullable(context);
            return this;
        }

        /**
         * <p>Optional context for the conversation</p>
         */
        @java.lang.Override
        @JsonSetter(value = "context", nulls = Nulls.SKIP)
        public _FinalStage context(Optional<String> context) {
            this.context = context;
            return this;
        }

        @java.lang.Override
        public AgentChatRequest build() {
            return new AgentChatRequest(message, context, sessionId, agentId, additionalProperties);
        }
    }
}
