/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.lang2fhir.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.resources.lang2fhir.types.DocumentMultiRequestDetectionEffort;
import com.phenoml.api.resources.lang2fhir.types.DocumentMultiRequestValidationMethod;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocumentMultiRequest.Builder.class)
public final class DocumentMultiRequest {
    private final String version;

    private final String content;

    private final Optional<String> provider;

    private final Optional<String> implementationGuide;

    private final Optional<DocumentMultiRequestDetectionEffort> detectionEffort;

    private final Optional<DocumentMultiRequestValidationMethod> validationMethod;

    private final Map<String, Object> additionalProperties;

    private DocumentMultiRequest(
            String version,
            String content,
            Optional<String> provider,
            Optional<String> implementationGuide,
            Optional<DocumentMultiRequestDetectionEffort> detectionEffort,
            Optional<DocumentMultiRequestValidationMethod> validationMethod,
            Map<String, Object> additionalProperties) {
        this.version = version;
        this.content = content;
        this.provider = provider;
        this.implementationGuide = implementationGuide;
        this.detectionEffort = detectionEffort;
        this.validationMethod = validationMethod;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return FHIR version to use
     */
    @JsonProperty("version")
    public String getVersion() {
        return version;
    }

    /**
     * @return Base64 encoded file content.
     * Supported file types: PDF (application/pdf), PNG (image/png), JPEG (image/jpeg).
     * File type is auto-detected from content magic bytes.
     */
    @JsonProperty("content")
    public String getContent() {
        return content;
    }

    /**
     * @return Optional FHIR provider name for provider-specific profiles
     */
    @JsonProperty("provider")
    public Optional<String> getProvider() {
        return provider;
    }

    /**
     * @return Custom Implementation Guide name. When specified, profiles from this IG are included alongside US Core profiles during resource detection. US Core is always the base layer; custom IG profiles are additive.
     */
    @JsonProperty("implementation_guide")
    public Optional<String> getImplementationGuide() {
        return implementationGuide;
    }

    /**
     * @return Detection effort. 'standard' runs detection once, 'deep' runs detection multiple times for higher recall.
     */
    @JsonProperty("detection_effort")
    public Optional<DocumentMultiRequestDetectionEffort> getDetectionEffort() {
        return detectionEffort;
    }

    /**
     * @return FHIR validation method to apply to the generated bundle. 'none' skips validation (default). 'check' runs the bundle through a FHIR structure validator and includes the results in the response. 'fix' runs validation and attempts to auto-correct errors using an LLM (up to 3 validation passes). The response includes results from each pass. Warning: 'fix' can significantly increase latency due to multiple LLM and validation round-trips.
     */
    @JsonProperty("validation_method")
    public Optional<DocumentMultiRequestValidationMethod> getValidationMethod() {
        return validationMethod;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocumentMultiRequest && equalTo((DocumentMultiRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocumentMultiRequest other) {
        return version.equals(other.version)
                && content.equals(other.content)
                && provider.equals(other.provider)
                && implementationGuide.equals(other.implementationGuide)
                && detectionEffort.equals(other.detectionEffort)
                && validationMethod.equals(other.validationMethod);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.version,
                this.content,
                this.provider,
                this.implementationGuide,
                this.detectionEffort,
                this.validationMethod);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static VersionStage builder() {
        return new Builder();
    }

    public interface VersionStage {
        /**
         * <p>FHIR version to use</p>
         */
        ContentStage version(@NotNull String version);

        Builder from(DocumentMultiRequest other);
    }

    public interface ContentStage {
        /**
         * <p>Base64 encoded file content.
         * Supported file types: PDF (application/pdf), PNG (image/png), JPEG (image/jpeg).
         * File type is auto-detected from content magic bytes.</p>
         */
        _FinalStage content(@NotNull String content);
    }

    public interface _FinalStage {
        DocumentMultiRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Optional FHIR provider name for provider-specific profiles</p>
         */
        _FinalStage provider(Optional<String> provider);

        _FinalStage provider(String provider);

        /**
         * <p>Custom Implementation Guide name. When specified, profiles from this IG are included alongside US Core profiles during resource detection. US Core is always the base layer; custom IG profiles are additive.</p>
         */
        _FinalStage implementationGuide(Optional<String> implementationGuide);

        _FinalStage implementationGuide(String implementationGuide);

        /**
         * <p>Detection effort. 'standard' runs detection once, 'deep' runs detection multiple times for higher recall.</p>
         */
        _FinalStage detectionEffort(Optional<DocumentMultiRequestDetectionEffort> detectionEffort);

        _FinalStage detectionEffort(DocumentMultiRequestDetectionEffort detectionEffort);

        /**
         * <p>FHIR validation method to apply to the generated bundle. 'none' skips validation (default). 'check' runs the bundle through a FHIR structure validator and includes the results in the response. 'fix' runs validation and attempts to auto-correct errors using an LLM (up to 3 validation passes). The response includes results from each pass. Warning: 'fix' can significantly increase latency due to multiple LLM and validation round-trips.</p>
         */
        _FinalStage validationMethod(Optional<DocumentMultiRequestValidationMethod> validationMethod);

        _FinalStage validationMethod(DocumentMultiRequestValidationMethod validationMethod);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements VersionStage, ContentStage, _FinalStage {
        private String version;

        private String content;

        private Optional<DocumentMultiRequestValidationMethod> validationMethod = Optional.empty();

        private Optional<DocumentMultiRequestDetectionEffort> detectionEffort = Optional.empty();

        private Optional<String> implementationGuide = Optional.empty();

        private Optional<String> provider = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocumentMultiRequest other) {
            version(other.getVersion());
            content(other.getContent());
            provider(other.getProvider());
            implementationGuide(other.getImplementationGuide());
            detectionEffort(other.getDetectionEffort());
            validationMethod(other.getValidationMethod());
            return this;
        }

        /**
         * <p>FHIR version to use</p>
         * <p>FHIR version to use</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("version")
        public ContentStage version(@NotNull String version) {
            this.version = Objects.requireNonNull(version, "version must not be null");
            return this;
        }

        /**
         * <p>Base64 encoded file content.
         * Supported file types: PDF (application/pdf), PNG (image/png), JPEG (image/jpeg).
         * File type is auto-detected from content magic bytes.</p>
         * <p>Base64 encoded file content.
         * Supported file types: PDF (application/pdf), PNG (image/png), JPEG (image/jpeg).
         * File type is auto-detected from content magic bytes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("content")
        public _FinalStage content(@NotNull String content) {
            this.content = Objects.requireNonNull(content, "content must not be null");
            return this;
        }

        /**
         * <p>FHIR validation method to apply to the generated bundle. 'none' skips validation (default). 'check' runs the bundle through a FHIR structure validator and includes the results in the response. 'fix' runs validation and attempts to auto-correct errors using an LLM (up to 3 validation passes). The response includes results from each pass. Warning: 'fix' can significantly increase latency due to multiple LLM and validation round-trips.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage validationMethod(DocumentMultiRequestValidationMethod validationMethod) {
            this.validationMethod = Optional.ofNullable(validationMethod);
            return this;
        }

        /**
         * <p>FHIR validation method to apply to the generated bundle. 'none' skips validation (default). 'check' runs the bundle through a FHIR structure validator and includes the results in the response. 'fix' runs validation and attempts to auto-correct errors using an LLM (up to 3 validation passes). The response includes results from each pass. Warning: 'fix' can significantly increase latency due to multiple LLM and validation round-trips.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "validation_method", nulls = Nulls.SKIP)
        public _FinalStage validationMethod(Optional<DocumentMultiRequestValidationMethod> validationMethod) {
            this.validationMethod = validationMethod;
            return this;
        }

        /**
         * <p>Detection effort. 'standard' runs detection once, 'deep' runs detection multiple times for higher recall.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage detectionEffort(DocumentMultiRequestDetectionEffort detectionEffort) {
            this.detectionEffort = Optional.ofNullable(detectionEffort);
            return this;
        }

        /**
         * <p>Detection effort. 'standard' runs detection once, 'deep' runs detection multiple times for higher recall.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "detection_effort", nulls = Nulls.SKIP)
        public _FinalStage detectionEffort(Optional<DocumentMultiRequestDetectionEffort> detectionEffort) {
            this.detectionEffort = detectionEffort;
            return this;
        }

        /**
         * <p>Custom Implementation Guide name. When specified, profiles from this IG are included alongside US Core profiles during resource detection. US Core is always the base layer; custom IG profiles are additive.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage implementationGuide(String implementationGuide) {
            this.implementationGuide = Optional.ofNullable(implementationGuide);
            return this;
        }

        /**
         * <p>Custom Implementation Guide name. When specified, profiles from this IG are included alongside US Core profiles during resource detection. US Core is always the base layer; custom IG profiles are additive.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "implementation_guide", nulls = Nulls.SKIP)
        public _FinalStage implementationGuide(Optional<String> implementationGuide) {
            this.implementationGuide = implementationGuide;
            return this;
        }

        /**
         * <p>Optional FHIR provider name for provider-specific profiles</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage provider(String provider) {
            this.provider = Optional.ofNullable(provider);
            return this;
        }

        /**
         * <p>Optional FHIR provider name for provider-specific profiles</p>
         */
        @java.lang.Override
        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public _FinalStage provider(Optional<String> provider) {
            this.provider = provider;
            return this;
        }

        @java.lang.Override
        public DocumentMultiRequest build() {
            return new DocumentMultiRequest(
                    version,
                    content,
                    provider,
                    implementationGuide,
                    detectionEffort,
                    validationMethod,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
