/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FhirSearchRequest.Builder.class)
public final class FhirSearchRequest {
    private final Optional<String> phenomlOnBehalfOf;

    private final Optional<String> phenomlFhirProvider;

    private final Optional<Map<String, Optional<String>>> queryParameters;

    private final Map<String, Object> additionalProperties;

    private FhirSearchRequest(
            Optional<String> phenomlOnBehalfOf,
            Optional<String> phenomlFhirProvider,
            Optional<Map<String, Optional<String>>> queryParameters,
            Map<String, Object> additionalProperties) {
        this.phenomlOnBehalfOf = phenomlOnBehalfOf;
        this.phenomlFhirProvider = phenomlFhirProvider;
        this.queryParameters = queryParameters;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
     * Must be in the format: Patient/{uuid} or Practitioner/{uuid}
     */
    @JsonProperty("X-Phenoml-On-Behalf-Of")
    public Optional<String> getPhenomlOnBehalfOf() {
        return phenomlOnBehalfOf;
    }

    /**
     * @return Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
     * Multiple FHIR provider integrations can be provided as comma-separated values.
     */
    @JsonProperty("X-Phenoml-Fhir-Provider")
    public Optional<String> getPhenomlFhirProvider() {
        return phenomlFhirProvider;
    }

    /**
     * @return FHIR-compliant query parameters for search operations. Supports standard FHIR search parameters including:
     * <ul>
     * <li>Resource-specific search parameters (e.g., name for Patient, status for Observation)</li>
     * <li>Common search parameters (_id, _lastUpdated, _tag, _profile, _security, _text, _content, _filter)</li>
     * <li>Result parameters (_count, _offset, _sort, _include, _revinclude, _summary, _elements)</li>
     * <li>Search prefixes for dates, numbers, quantities (eq, ne, gt, ge, lt, le, sa, eb, ap)</li>
     * </ul>
     */
    @JsonProperty("query_parameters")
    public Optional<Map<String, Optional<String>>> getQueryParameters() {
        return queryParameters;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FhirSearchRequest && equalTo((FhirSearchRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FhirSearchRequest other) {
        return phenomlOnBehalfOf.equals(other.phenomlOnBehalfOf)
                && phenomlFhirProvider.equals(other.phenomlFhirProvider)
                && queryParameters.equals(other.queryParameters);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.phenomlOnBehalfOf, this.phenomlFhirProvider, this.queryParameters);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> phenomlOnBehalfOf = Optional.empty();

        private Optional<String> phenomlFhirProvider = Optional.empty();

        private Optional<Map<String, Optional<String>>> queryParameters = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FhirSearchRequest other) {
            phenomlOnBehalfOf(other.getPhenomlOnBehalfOf());
            phenomlFhirProvider(other.getPhenomlFhirProvider());
            queryParameters(other.getQueryParameters());
            return this;
        }

        /**
         * <p>Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
         * Must be in the format: Patient/{uuid} or Practitioner/{uuid}</p>
         */
        @JsonSetter(value = "X-Phenoml-On-Behalf-Of", nulls = Nulls.SKIP)
        public Builder phenomlOnBehalfOf(Optional<String> phenomlOnBehalfOf) {
            this.phenomlOnBehalfOf = phenomlOnBehalfOf;
            return this;
        }

        public Builder phenomlOnBehalfOf(String phenomlOnBehalfOf) {
            this.phenomlOnBehalfOf = Optional.ofNullable(phenomlOnBehalfOf);
            return this;
        }

        /**
         * <p>Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
         * Multiple FHIR provider integrations can be provided as comma-separated values.</p>
         */
        @JsonSetter(value = "X-Phenoml-Fhir-Provider", nulls = Nulls.SKIP)
        public Builder phenomlFhirProvider(Optional<String> phenomlFhirProvider) {
            this.phenomlFhirProvider = phenomlFhirProvider;
            return this;
        }

        public Builder phenomlFhirProvider(String phenomlFhirProvider) {
            this.phenomlFhirProvider = Optional.ofNullable(phenomlFhirProvider);
            return this;
        }

        /**
         * <p>FHIR-compliant query parameters for search operations. Supports standard FHIR search parameters including:</p>
         * <ul>
         * <li>Resource-specific search parameters (e.g., name for Patient, status for Observation)</li>
         * <li>Common search parameters (_id, _lastUpdated, _tag, _profile, _security, _text, _content, _filter)</li>
         * <li>Result parameters (_count, _offset, _sort, _include, _revinclude, _summary, _elements)</li>
         * <li>Search prefixes for dates, numbers, quantities (eq, ne, gt, ge, lt, le, sa, eb, ap)</li>
         * </ul>
         */
        @JsonSetter(value = "query_parameters", nulls = Nulls.SKIP)
        public Builder queryParameters(Optional<Map<String, Optional<String>>> queryParameters) {
            this.queryParameters = queryParameters;
            return this;
        }

        public Builder queryParameters(Map<String, Optional<String>> queryParameters) {
            this.queryParameters = Optional.ofNullable(queryParameters);
            return this;
        }

        public FhirSearchRequest build() {
            return new FhirSearchRequest(phenomlOnBehalfOf, phenomlFhirProvider, queryParameters, additionalProperties);
        }
    }
}
