/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.profiles.profiles;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.profiles.profiles.requests.ListRequest;
import com.phenoml.api.resources.profiles.types.ProfileGetResponse;
import com.phenoml.api.resources.profiles.types.ProfileListResponse;
import com.phenoml.api.resources.profiles.types.ProfileSummary;
import com.phenoml.api.resources.profiles.types.ProfileUploadRequest;

public class ProfilesClient {
    protected final ClientOptions clientOptions;

    private final RawProfilesClient rawClient;

    public ProfilesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawProfilesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawProfilesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns metadata for every custom (uploaded) FHIR profile on this
     * instance, across all implementation guides. The full StructureDefinition
     * JSON is omitted from each entry; fetch a single profile by id to retrieve it.
     * <p>The <code>url</code> query parameter filters by canonical URL. The canonical URL is the
     * stable key other platform features use to reference a profile (FHIR's
     * <code>meta.profile</code>, <code>baseDefinition</code>), since StructureDefinition ids are only
     * unique within a package. A non-matching filter returns an empty list, not a 404.</p>
     */
    public ProfileListResponse list() {
        return this.rawClient.list().body();
    }

    /**
     * Returns metadata for every custom (uploaded) FHIR profile on this
     * instance, across all implementation guides. The full StructureDefinition
     * JSON is omitted from each entry; fetch a single profile by id to retrieve it.
     * <p>The <code>url</code> query parameter filters by canonical URL. The canonical URL is the
     * stable key other platform features use to reference a profile (FHIR's
     * <code>meta.profile</code>, <code>baseDefinition</code>), since StructureDefinition ids are only
     * unique within a package. A non-matching filter returns an empty list, not a 404.</p>
     */
    public ProfileListResponse list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Returns metadata for every custom (uploaded) FHIR profile on this
     * instance, across all implementation guides. The full StructureDefinition
     * JSON is omitted from each entry; fetch a single profile by id to retrieve it.
     * <p>The <code>url</code> query parameter filters by canonical URL. The canonical URL is the
     * stable key other platform features use to reference a profile (FHIR's
     * <code>meta.profile</code>, <code>baseDefinition</code>), since StructureDefinition ids are only
     * unique within a package. A non-matching filter returns an empty list, not a 404.</p>
     */
    public ProfileListResponse list(ListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Returns metadata for every custom (uploaded) FHIR profile on this
     * instance, across all implementation guides. The full StructureDefinition
     * JSON is omitted from each entry; fetch a single profile by id to retrieve it.
     * <p>The <code>url</code> query parameter filters by canonical URL. The canonical URL is the
     * stable key other platform features use to reference a profile (FHIR's
     * <code>meta.profile</code>, <code>baseDefinition</code>), since StructureDefinition ids are only
     * unique within a package. A non-matching filter returns an empty list, not a 404.</p>
     */
    public ProfileListResponse list(ListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Creates a custom profile from a FHIR StructureDefinition supplied as a JSON
     * object. All metadata (version, resource type, id, url) is derived from the
     * StructureDefinition; the lowercase StructureDefinition id becomes the
     * profile's lookup key. Code system configuration is auto-extracted from the
     * snapshot. Optionally group the profile under a named implementation guide.
     */
    public ProfileSummary create(ProfileUploadRequest request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Creates a custom profile from a FHIR StructureDefinition supplied as a JSON
     * object. All metadata (version, resource type, id, url) is derived from the
     * StructureDefinition; the lowercase StructureDefinition id becomes the
     * profile's lookup key. Code system configuration is auto-extracted from the
     * snapshot. Optionally group the profile under a named implementation guide.
     */
    public ProfileSummary create(ProfileUploadRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Returns a single custom profile by id, including its full StructureDefinition JSON.
     */
    public ProfileGetResponse get(String id) {
        return this.rawClient.get(id).body();
    }

    /**
     * Returns a single custom profile by id, including its full StructureDefinition JSON.
     */
    public ProfileGetResponse get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }

    /**
     * Replaces an existing custom profile with a new StructureDefinition. The
     * <code>id</code> path parameter is authoritative: if the StructureDefinition includes
     * an <code>id</code> it must match the path parameter, and if it omits one the path
     * parameter is used. The FHIR resource type of the profile cannot change.
     * Code system configuration is
     * re-derived from the new StructureDefinition. When <code>implementation_guide</code> is
     * omitted, the profile keeps its existing implementation guide. The instance
     * stores a single version per canonical URL, so this replaces it in place.
     */
    public ProfileSummary update(String id, ProfileUploadRequest request) {
        return this.rawClient.update(id, request).body();
    }

    /**
     * Replaces an existing custom profile with a new StructureDefinition. The
     * <code>id</code> path parameter is authoritative: if the StructureDefinition includes
     * an <code>id</code> it must match the path parameter, and if it omits one the path
     * parameter is used. The FHIR resource type of the profile cannot change.
     * Code system configuration is
     * re-derived from the new StructureDefinition. When <code>implementation_guide</code> is
     * omitted, the profile keeps its existing implementation guide. The instance
     * stores a single version per canonical URL, so this replaces it in place.
     */
    public ProfileSummary update(String id, ProfileUploadRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).body();
    }

    /**
     * Permanently deletes a custom profile by id.
     */
    public void delete(String id) {
        this.rawClient.delete(id).body();
    }

    /**
     * Permanently deletes a custom profile by id.
     */
    public void delete(String id, RequestOptions requestOptions) {
        this.rawClient.delete(id, requestOptions).body();
    }
}
