/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.profiles.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProfileListResponse.Builder.class)
public final class ProfileListResponse {
    private final Optional<List<ProfileSummary>> profiles;

    private final Map<String, Object> additionalProperties;

    private ProfileListResponse(Optional<List<ProfileSummary>> profiles, Map<String, Object> additionalProperties) {
        this.profiles = profiles;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("profiles")
    public Optional<List<ProfileSummary>> getProfiles() {
        return profiles;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProfileListResponse && equalTo((ProfileListResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProfileListResponse other) {
        return profiles.equals(other.profiles);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.profiles);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ProfileSummary>> profiles = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ProfileListResponse other) {
            profiles(other.getProfiles());
            return this;
        }

        @JsonSetter(value = "profiles", nulls = Nulls.SKIP)
        public Builder profiles(Optional<List<ProfileSummary>> profiles) {
            this.profiles = profiles;
            return this;
        }

        public Builder profiles(List<ProfileSummary> profiles) {
            this.profiles = Optional.ofNullable(profiles);
            return this;
        }

        public ProfileListResponse build() {
            return new ProfileListResponse(profiles, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
