/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.agent.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = JsonPatchOperation.Builder.class
)
public final class JsonPatchOperation {
  private final JsonPatchOperationOp op;

  private final String path;

  private final Optional<Object> value;

  private final Optional<String> from;

  private final Map<String, Object> additionalProperties;

  private JsonPatchOperation(JsonPatchOperationOp op, String path, Optional<Object> value,
      Optional<String> from, Map<String, Object> additionalProperties) {
    this.op = op;
    this.path = path;
    this.value = value;
    this.from = from;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The operation to be performed
   */
  @JsonProperty("op")
  public JsonPatchOperationOp getOp() {
    return op;
  }

  /**
   * @return A JSON Pointer string specifying a location within the target document
   */
  @JsonProperty("path")
  public String getPath() {
    return path;
  }

  /**
   * @return The value to be used within the operations
   */
  @JsonProperty("value")
  public Optional<Object> getValue() {
    return value;
  }

  /**
   * @return A JSON Pointer string specifying the location in the target document to move the value from (used with move and copy operations)
   */
  @JsonProperty("from")
  public Optional<String> getFrom() {
    return from;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof JsonPatchOperation && equalTo((JsonPatchOperation) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(JsonPatchOperation other) {
    return op.equals(other.op) && path.equals(other.path) && value.equals(other.value) && from.equals(other.from);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.op, this.path, this.value, this.from);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static OpStage builder() {
    return new Builder();
  }

  public interface OpStage {
    /**
     * <p>The operation to be performed</p>
     */
    PathStage op(@NotNull JsonPatchOperationOp op);

    Builder from(JsonPatchOperation other);
  }

  public interface PathStage {
    /**
     * <p>A JSON Pointer string specifying a location within the target document</p>
     */
    _FinalStage path(@NotNull String path);
  }

  public interface _FinalStage {
    JsonPatchOperation build();

    /**
     * <p>The value to be used within the operations</p>
     */
    _FinalStage value(Optional<Object> value);

    _FinalStage value(Object value);

    /**
     * <p>A JSON Pointer string specifying the location in the target document to move the value from (used with move and copy operations)</p>
     */
    _FinalStage from(Optional<String> from);

    _FinalStage from(String from);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements OpStage, PathStage, _FinalStage {
    private JsonPatchOperationOp op;

    private String path;

    private Optional<String> from = Optional.empty();

    private Optional<Object> value = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(JsonPatchOperation other) {
      op(other.getOp());
      path(other.getPath());
      value(other.getValue());
      from(other.getFrom());
      return this;
    }

    /**
     * <p>The operation to be performed</p>
     * <p>The operation to be performed</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("op")
    public PathStage op(@NotNull JsonPatchOperationOp op) {
      this.op = Objects.requireNonNull(op, "op must not be null");
      return this;
    }

    /**
     * <p>A JSON Pointer string specifying a location within the target document</p>
     * <p>A JSON Pointer string specifying a location within the target document</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("path")
    public _FinalStage path(@NotNull String path) {
      this.path = Objects.requireNonNull(path, "path must not be null");
      return this;
    }

    /**
     * <p>A JSON Pointer string specifying the location in the target document to move the value from (used with move and copy operations)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage from(String from) {
      this.from = Optional.ofNullable(from);
      return this;
    }

    /**
     * <p>A JSON Pointer string specifying the location in the target document to move the value from (used with move and copy operations)</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "from",
        nulls = Nulls.SKIP
    )
    public _FinalStage from(Optional<String> from) {
      this.from = from;
      return this;
    }

    /**
     * <p>The value to be used within the operations</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage value(Object value) {
      this.value = Optional.ofNullable(value);
      return this;
    }

    /**
     * <p>The value to be used within the operations</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "value",
        nulls = Nulls.SKIP
    )
    public _FinalStage value(Optional<Object> value) {
      this.value = value;
      return this;
    }

    @java.lang.Override
    public JsonPatchOperation build() {
      return new JsonPatchOperation(op, path, value, from, additionalProperties);
    }
  }
}
