/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.fhirprovider.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = JsonWebKey.Builder.class
)
public final class JsonWebKey {
  private final Optional<String> kty;

  private final Optional<String> use;

  private final Optional<String> kid;

  private final Optional<String> alg;

  private final Optional<String> n;

  private final Optional<String> e;

  private final Map<String, Object> additionalProperties;

  private JsonWebKey(Optional<String> kty, Optional<String> use, Optional<String> kid,
      Optional<String> alg, Optional<String> n, Optional<String> e,
      Map<String, Object> additionalProperties) {
    this.kty = kty;
    this.use = use;
    this.kid = kid;
    this.alg = alg;
    this.n = n;
    this.e = e;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Key Type
   */
  @JsonProperty("kty")
  public Optional<String> getKty() {
    return kty;
  }

  /**
   * @return Usage (sig for signature)
   */
  @JsonProperty("use")
  public Optional<String> getUse() {
    return use;
  }

  /**
   * @return Key ID - SHA256 hash of the public key PEM (including headers) encoded as base64url. Generated by taking the public key in PEM format, hashing with SHA256, then base64url encoding (replacing + with -, / with _, and removing padding).
   */
  @JsonProperty("kid")
  public Optional<String> getKid() {
    return kid;
  }

  /**
   * @return Algorithm used for JWT signing (RSA with SHA-384)
   */
  @JsonProperty("alg")
  public Optional<String> getAlg() {
    return alg;
  }

  /**
   * @return RSA Modulus (base64url encoded)
   */
  @JsonProperty("n")
  public Optional<String> getN() {
    return n;
  }

  /**
   * @return RSA Exponent (base64url encoded)
   */
  @JsonProperty("e")
  public Optional<String> getE() {
    return e;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof JsonWebKey && equalTo((JsonWebKey) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(JsonWebKey other) {
    return kty.equals(other.kty) && use.equals(other.use) && kid.equals(other.kid) && alg.equals(other.alg) && n.equals(other.n) && e.equals(other.e);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.kty, this.use, this.kid, this.alg, this.n, this.e);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> kty = Optional.empty();

    private Optional<String> use = Optional.empty();

    private Optional<String> kid = Optional.empty();

    private Optional<String> alg = Optional.empty();

    private Optional<String> n = Optional.empty();

    private Optional<String> e = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(JsonWebKey other) {
      kty(other.getKty());
      use(other.getUse());
      kid(other.getKid());
      alg(other.getAlg());
      n(other.getN());
      e(other.getE());
      return this;
    }

    /**
     * <p>Key Type</p>
     */
    @JsonSetter(
        value = "kty",
        nulls = Nulls.SKIP
    )
    public Builder kty(Optional<String> kty) {
      this.kty = kty;
      return this;
    }

    public Builder kty(String kty) {
      this.kty = Optional.ofNullable(kty);
      return this;
    }

    /**
     * <p>Usage (sig for signature)</p>
     */
    @JsonSetter(
        value = "use",
        nulls = Nulls.SKIP
    )
    public Builder use(Optional<String> use) {
      this.use = use;
      return this;
    }

    public Builder use(String use) {
      this.use = Optional.ofNullable(use);
      return this;
    }

    /**
     * <p>Key ID - SHA256 hash of the public key PEM (including headers) encoded as base64url. Generated by taking the public key in PEM format, hashing with SHA256, then base64url encoding (replacing + with -, / with _, and removing padding).</p>
     */
    @JsonSetter(
        value = "kid",
        nulls = Nulls.SKIP
    )
    public Builder kid(Optional<String> kid) {
      this.kid = kid;
      return this;
    }

    public Builder kid(String kid) {
      this.kid = Optional.ofNullable(kid);
      return this;
    }

    /**
     * <p>Algorithm used for JWT signing (RSA with SHA-384)</p>
     */
    @JsonSetter(
        value = "alg",
        nulls = Nulls.SKIP
    )
    public Builder alg(Optional<String> alg) {
      this.alg = alg;
      return this;
    }

    public Builder alg(String alg) {
      this.alg = Optional.ofNullable(alg);
      return this;
    }

    /**
     * <p>RSA Modulus (base64url encoded)</p>
     */
    @JsonSetter(
        value = "n",
        nulls = Nulls.SKIP
    )
    public Builder n(Optional<String> n) {
      this.n = n;
      return this;
    }

    public Builder n(String n) {
      this.n = Optional.ofNullable(n);
      return this;
    }

    /**
     * <p>RSA Exponent (base64url encoded)</p>
     */
    @JsonSetter(
        value = "e",
        nulls = Nulls.SKIP
    )
    public Builder e(Optional<String> e) {
      this.e = e;
      return this;
    }

    public Builder e(String e) {
      this.e = Optional.ofNullable(e);
      return this;
    }

    public JsonWebKey build() {
      return new JsonWebKey(kty, use, kid, alg, n, e, additionalProperties);
    }
  }
}
