/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhirprovider.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class Role {
    public static final Role WRITE = new Role(Value.WRITE, "write");

    public static final Role ADMIN = new Role(Value.ADMIN, "admin");

    public static final Role READ = new Role(Value.READ, "read");

    private final Value value;

    private final String string;

    Role(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof Role && this.string.equals(((Role) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WRITE:
                return visitor.visitWrite();
            case ADMIN:
                return visitor.visitAdmin();
            case READ:
                return visitor.visitRead();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Role valueOf(String value) {
        switch (value) {
            case "write":
                return WRITE;
            case "admin":
                return ADMIN;
            case "read":
                return READ;
            default:
                return new Role(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ADMIN,

        READ,

        WRITE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdmin();

        T visitRead();

        T visitWrite();

        T visitUnknown(String unknownType);
    }
}
