/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.fhirprovider.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class Role {
  public static final Role CERNER_SMART_V2READ = new Role(Value.CERNER_SMART_V2READ, "CernerSmartV2Read");

  public static final Role USCDI_SMART_V2READ = new Role(Value.USCDI_SMART_V2READ, "USCDISmartV2Read");

  public static final Role USCDI_SMART_V2WRITE = new Role(Value.USCDI_SMART_V2WRITE, "USCDISmartV2Write");

  public static final Role CERNER_SMART_V1READ = new Role(Value.CERNER_SMART_V1READ, "CernerSmartV1Read");

  public static final Role USCDI_SMART_V1READ = new Role(Value.USCDI_SMART_V1READ, "USCDISmartV1Read");

  public static final Role USCDI_SMART_V2ADMIN = new Role(Value.USCDI_SMART_V2ADMIN, "USCDISmartV2Admin");

  public static final Role USCDI_SMART_V1WRITE = new Role(Value.USCDI_SMART_V1WRITE, "USCDISmartV1Write");

  public static final Role CERNER_SMART_V2WRITE = new Role(Value.CERNER_SMART_V2WRITE, "CernerSmartV2Write");

  public static final Role USCDI_SMART_V1ADMIN = new Role(Value.USCDI_SMART_V1ADMIN, "USCDISmartV1Admin");

  public static final Role CERNER_SMART_V2ADMIN = new Role(Value.CERNER_SMART_V2ADMIN, "CernerSmartV2Admin");

  public static final Role SMART_V2WRITE = new Role(Value.SMART_V2WRITE, "SmartV2Write");

  public static final Role CERNER_SMART_V1WRITE = new Role(Value.CERNER_SMART_V1WRITE, "CernerSmartV1Write");

  public static final Role SMART_V2ADMIN = new Role(Value.SMART_V2ADMIN, "SmartV2Admin");

  public static final Role CERNER_SMART_V1ADMIN = new Role(Value.CERNER_SMART_V1ADMIN, "CernerSmartV1Admin");

  public static final Role SMART_V2READ = new Role(Value.SMART_V2READ, "SmartV2Read");

  public static final Role SMART_V1WRITE = new Role(Value.SMART_V1WRITE, "SmartV1Write");

  public static final Role SMART_V1ADMIN = new Role(Value.SMART_V1ADMIN, "SmartV1Admin");

  public static final Role SMART_V1READ = new Role(Value.SMART_V1READ, "SmartV1Read");

  private final Value value;

  private final String string;

  Role(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof Role && this.string.equals(((Role) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CERNER_SMART_V2READ:
        return visitor.visitCernerSmartV2Read();
      case USCDI_SMART_V2READ:
        return visitor.visitUscdiSmartV2Read();
      case USCDI_SMART_V2WRITE:
        return visitor.visitUscdiSmartV2Write();
      case CERNER_SMART_V1READ:
        return visitor.visitCernerSmartV1Read();
      case USCDI_SMART_V1READ:
        return visitor.visitUscdiSmartV1Read();
      case USCDI_SMART_V2ADMIN:
        return visitor.visitUscdiSmartV2Admin();
      case USCDI_SMART_V1WRITE:
        return visitor.visitUscdiSmartV1Write();
      case CERNER_SMART_V2WRITE:
        return visitor.visitCernerSmartV2Write();
      case USCDI_SMART_V1ADMIN:
        return visitor.visitUscdiSmartV1Admin();
      case CERNER_SMART_V2ADMIN:
        return visitor.visitCernerSmartV2Admin();
      case SMART_V2WRITE:
        return visitor.visitSmartV2Write();
      case CERNER_SMART_V1WRITE:
        return visitor.visitCernerSmartV1Write();
      case SMART_V2ADMIN:
        return visitor.visitSmartV2Admin();
      case CERNER_SMART_V1ADMIN:
        return visitor.visitCernerSmartV1Admin();
      case SMART_V2READ:
        return visitor.visitSmartV2Read();
      case SMART_V1WRITE:
        return visitor.visitSmartV1Write();
      case SMART_V1ADMIN:
        return visitor.visitSmartV1Admin();
      case SMART_V1READ:
        return visitor.visitSmartV1Read();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static Role valueOf(String value) {
    switch (value) {
      case "CernerSmartV2Read":
        return CERNER_SMART_V2READ;
      case "USCDISmartV2Read":
        return USCDI_SMART_V2READ;
      case "USCDISmartV2Write":
        return USCDI_SMART_V2WRITE;
      case "CernerSmartV1Read":
        return CERNER_SMART_V1READ;
      case "USCDISmartV1Read":
        return USCDI_SMART_V1READ;
      case "USCDISmartV2Admin":
        return USCDI_SMART_V2ADMIN;
      case "USCDISmartV1Write":
        return USCDI_SMART_V1WRITE;
      case "CernerSmartV2Write":
        return CERNER_SMART_V2WRITE;
      case "USCDISmartV1Admin":
        return USCDI_SMART_V1ADMIN;
      case "CernerSmartV2Admin":
        return CERNER_SMART_V2ADMIN;
      case "SmartV2Write":
        return SMART_V2WRITE;
      case "CernerSmartV1Write":
        return CERNER_SMART_V1WRITE;
      case "SmartV2Admin":
        return SMART_V2ADMIN;
      case "CernerSmartV1Admin":
        return CERNER_SMART_V1ADMIN;
      case "SmartV2Read":
        return SMART_V2READ;
      case "SmartV1Write":
        return SMART_V1WRITE;
      case "SmartV1Admin":
        return SMART_V1ADMIN;
      case "SmartV1Read":
        return SMART_V1READ;
      default:
        return new Role(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    SMART_V1ADMIN,

    SMART_V1READ,

    SMART_V1WRITE,

    SMART_V2ADMIN,

    SMART_V2READ,

    SMART_V2WRITE,

    USCDI_SMART_V1ADMIN,

    USCDI_SMART_V1READ,

    USCDI_SMART_V1WRITE,

    USCDI_SMART_V2ADMIN,

    USCDI_SMART_V2READ,

    USCDI_SMART_V2WRITE,

    CERNER_SMART_V1ADMIN,

    CERNER_SMART_V1READ,

    CERNER_SMART_V1WRITE,

    CERNER_SMART_V2ADMIN,

    CERNER_SMART_V2READ,

    CERNER_SMART_V2WRITE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitSmartV1Admin();

    T visitSmartV1Read();

    T visitSmartV1Write();

    T visitSmartV2Admin();

    T visitSmartV2Read();

    T visitSmartV2Write();

    T visitUscdiSmartV1Admin();

    T visitUscdiSmartV1Read();

    T visitUscdiSmartV1Write();

    T visitUscdiSmartV2Admin();

    T visitUscdiSmartV2Read();

    T visitUscdiSmartV2Write();

    T visitCernerSmartV1Admin();

    T visitCernerSmartV1Read();

    T visitCernerSmartV1Write();

    T visitCernerSmartV2Admin();

    T visitCernerSmartV2Read();

    T visitCernerSmartV2Write();

    T visitUnknown(String unknownType);
  }
}
