/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.implementationguides.implementationguides;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.implementationguides.implementationguides.requests.UpdateImplementationGuideRequest;
import com.phenoml.api.resources.implementationguides.types.ImplementationGuideDetail;
import com.phenoml.api.resources.implementationguides.types.ImplementationGuideListResponse;
import com.phenoml.api.resources.implementationguides.types.ImplementationGuideSummary;
import java.util.concurrent.CompletableFuture;

public class AsyncImplementationGuidesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawImplementationGuidesClient rawClient;

    public AsyncImplementationGuidesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawImplementationGuidesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawImplementationGuidesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns every implementation guide on this instance — both guides that
     * have stored metadata (a profile_context) and guides referenced by at
     * least one custom profile — with the number of profiles in each.
     */
    public CompletableFuture<ImplementationGuideListResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns every implementation guide on this instance — both guides that
     * have stored metadata (a profile_context) and guides referenced by at
     * least one custom profile — with the number of profiles in each.
     */
    public CompletableFuture<ImplementationGuideListResponse> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single implementation guide, including its profile_context and
     * the ids of the profiles that belong to it.
     */
    public CompletableFuture<ImplementationGuideDetail> get(String name) {
        return this.rawClient.get(name).thenApply(response -> response.body());
    }

    /**
     * Returns a single implementation guide, including its profile_context and
     * the ids of the profiles that belong to it.
     */
    public CompletableFuture<ImplementationGuideDetail> get(String name, RequestOptions requestOptions) {
        return this.rawClient.get(name, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public CompletableFuture<ImplementationGuideSummary> update(String name) {
        return this.rawClient.update(name).thenApply(response -> response.body());
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public CompletableFuture<ImplementationGuideSummary> update(String name, RequestOptions requestOptions) {
        return this.rawClient.update(name, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public CompletableFuture<ImplementationGuideSummary> update(String name, UpdateImplementationGuideRequest request) {
        return this.rawClient.update(name, request).thenApply(response -> response.body());
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public CompletableFuture<ImplementationGuideSummary> update(
            String name, UpdateImplementationGuideRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(name, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes the stored metadata for an implementation guide — its
     * profile_context and timestamps. Member profiles keep their
     * implementation_guide assignment, so a guide still referenced by at least
     * one profile continues to appear in listings, just without context or
     * timestamps.
     */
    public CompletableFuture<Void> delete(String name) {
        return this.rawClient.delete(name).thenApply(response -> response.body());
    }

    /**
     * Deletes the stored metadata for an implementation guide — its
     * profile_context and timestamps. Member profiles keep their
     * implementation_guide assignment, so a guide still referenced by at least
     * one profile continues to appear in listings, just without context or
     * timestamps.
     */
    public CompletableFuture<Void> delete(String name, RequestOptions requestOptions) {
        return this.rawClient.delete(name, requestOptions).thenApply(response -> response.body());
    }
}
