/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.implementationguides.implementationguides;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.MediaTypes;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.core.PhenomlClientApiException;
import com.phenoml.api.core.PhenomlClientException;
import com.phenoml.api.core.PhenomlClientHttpResponse;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.core.RetryInterceptor;
import com.phenoml.api.resources.implementationguides.errors.BadRequestError;
import com.phenoml.api.resources.implementationguides.errors.ForbiddenError;
import com.phenoml.api.resources.implementationguides.errors.InternalServerError;
import com.phenoml.api.resources.implementationguides.errors.NotFoundError;
import com.phenoml.api.resources.implementationguides.errors.UnauthorizedError;
import com.phenoml.api.resources.implementationguides.implementationguides.requests.UpdateImplementationGuideRequest;
import com.phenoml.api.resources.implementationguides.types.ImplementationGuideDetail;
import com.phenoml.api.resources.implementationguides.types.ImplementationGuideListResponse;
import com.phenoml.api.resources.implementationguides.types.ImplementationGuideSummary;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawImplementationGuidesClient {
    protected final ClientOptions clientOptions;

    public RawImplementationGuidesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns every implementation guide on this instance — both guides that
     * have stored metadata (a profile_context) and guides referenced by at
     * least one custom profile — with the number of profiles in each.
     */
    public PhenomlClientHttpResponse<ImplementationGuideListResponse> list() {
        return list(null);
    }

    /**
     * Returns every implementation guide on this instance — both guides that
     * have stored metadata (a profile_context) and guides referenced by at
     * least one custom profile — with the number of profiles in each.
     */
    public PhenomlClientHttpResponse<ImplementationGuideListResponse> list(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("fhir/implementation-guides");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PhenomlClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ImplementationGuideListResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PhenomlClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new PhenomlClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a single implementation guide, including its profile_context and
     * the ids of the profiles that belong to it.
     */
    public PhenomlClientHttpResponse<ImplementationGuideDetail> get(String name) {
        return get(name, null);
    }

    /**
     * Returns a single implementation guide, including its profile_context and
     * the ids of the profiles that belong to it.
     */
    public PhenomlClientHttpResponse<ImplementationGuideDetail> get(String name, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("fhir/implementation-guides")
                .addPathSegment(name);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PhenomlClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ImplementationGuideDetail.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PhenomlClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new PhenomlClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public PhenomlClientHttpResponse<ImplementationGuideSummary> update(String name) {
        return update(name, UpdateImplementationGuideRequest.builder().build());
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public PhenomlClientHttpResponse<ImplementationGuideSummary> update(String name, RequestOptions requestOptions) {
        return update(name, UpdateImplementationGuideRequest.builder().build(), requestOptions);
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public PhenomlClientHttpResponse<ImplementationGuideSummary> update(
            String name, UpdateImplementationGuideRequest request) {
        return update(name, request, null);
    }

    /**
     * Sets (or clears, with an empty value) the natural-language profile_context
     * for an implementation guide. The context is injected into the LLM during
     * resource detection to help select the right profiles from this guide.
     * It applies to every profile in the guide.
     */
    public PhenomlClientHttpResponse<ImplementationGuideSummary> update(
            String name, UpdateImplementationGuideRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("fhir/implementation-guides")
                .addPathSegment(name);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PhenomlClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ImplementationGuideSummary.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PhenomlClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new PhenomlClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Deletes the stored metadata for an implementation guide — its
     * profile_context and timestamps. Member profiles keep their
     * implementation_guide assignment, so a guide still referenced by at least
     * one profile continues to appear in listings, just without context or
     * timestamps.
     */
    public PhenomlClientHttpResponse<Void> delete(String name) {
        return delete(name, null);
    }

    /**
     * Deletes the stored metadata for an implementation guide — its
     * profile_context and timestamps. Member profiles keep their
     * implementation_guide assignment, so a guide still referenced by at least
     * one profile continues to appear in listings, just without context or
     * timestamps.
     */
    public PhenomlClientHttpResponse<Void> delete(String name, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("fhir/implementation-guides")
                .addPathSegment(name);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhenomlClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PhenomlClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new PhenomlClientException("Network error executing HTTP request", e);
        }
    }
}
