/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.tools.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.resources.tools.types.FhirClientConfig;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Lang2FhirAndCreateRequest.Builder.class)
public final class Lang2FhirAndCreateRequest {
    private final Resource resource;

    private final String text;

    private final Optional<Provider> provider;

    private final Optional<FhirClientConfig> meta;

    private final Map<String, Object> additionalProperties;

    private Lang2FhirAndCreateRequest(
            Resource resource,
            String text,
            Optional<Provider> provider,
            Optional<FhirClientConfig> meta,
            Map<String, Object> additionalProperties) {
        this.resource = resource;
        this.text = text;
        this.provider = provider;
        this.meta = meta;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.
     */
    @JsonProperty("resource")
    public Resource getResource() {
        return resource;
    }

    /**
     * @return Natural language text to convert to FHIR resource
     */
    @JsonProperty("text")
    public String getText() {
        return text;
    }

    /**
     * @return FHIR provider to use for storing the resource
     */
    @JsonProperty("provider")
    public Optional<Provider> getProvider() {
        return provider;
    }

    @JsonProperty("meta")
    public Optional<FhirClientConfig> getMeta() {
        return meta;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Lang2FhirAndCreateRequest && equalTo((Lang2FhirAndCreateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Lang2FhirAndCreateRequest other) {
        return resource.equals(other.resource)
                && text.equals(other.text)
                && provider.equals(other.provider)
                && meta.equals(other.meta);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.resource, this.text, this.provider, this.meta);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ResourceStage builder() {
        return new Builder();
    }

    public interface ResourceStage {
        /**
         * <p>Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.</p>
         */
        TextStage resource(@NotNull Resource resource);

        Builder from(Lang2FhirAndCreateRequest other);
    }

    public interface TextStage {
        /**
         * <p>Natural language text to convert to FHIR resource</p>
         */
        _FinalStage text(@NotNull String text);
    }

    public interface _FinalStage {
        Lang2FhirAndCreateRequest build();

        /**
         * <p>FHIR provider to use for storing the resource</p>
         */
        _FinalStage provider(Optional<Provider> provider);

        _FinalStage provider(Provider provider);

        _FinalStage meta(Optional<FhirClientConfig> meta);

        _FinalStage meta(FhirClientConfig meta);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ResourceStage, TextStage, _FinalStage {
        private Resource resource;

        private String text;

        private Optional<FhirClientConfig> meta = Optional.empty();

        private Optional<Provider> provider = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Lang2FhirAndCreateRequest other) {
            resource(other.getResource());
            text(other.getText());
            provider(other.getProvider());
            meta(other.getMeta());
            return this;
        }

        /**
         * <p>Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.</p>
         * <p>Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("resource")
        public TextStage resource(@NotNull Resource resource) {
            this.resource = Objects.requireNonNull(resource, "resource must not be null");
            return this;
        }

        /**
         * <p>Natural language text to convert to FHIR resource</p>
         * <p>Natural language text to convert to FHIR resource</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("text")
        public _FinalStage text(@NotNull String text) {
            this.text = Objects.requireNonNull(text, "text must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage meta(FhirClientConfig meta) {
            this.meta = Optional.ofNullable(meta);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "meta", nulls = Nulls.SKIP)
        public _FinalStage meta(Optional<FhirClientConfig> meta) {
            this.meta = meta;
            return this;
        }

        /**
         * <p>FHIR provider to use for storing the resource</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage provider(Provider provider) {
            this.provider = Optional.ofNullable(provider);
            return this;
        }

        /**
         * <p>FHIR provider to use for storing the resource</p>
         */
        @java.lang.Override
        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public _FinalStage provider(Optional<Provider> provider) {
            this.provider = provider;
            return this;
        }

        @java.lang.Override
        public Lang2FhirAndCreateRequest build() {
            return new Lang2FhirAndCreateRequest(resource, text, provider, meta, additionalProperties);
        }
    }

    public static final class Resource {
        public static final Resource MEDICATIONREQUEST = new Resource(Value.MEDICATIONREQUEST, "medicationrequest");

        public static final Resource OBSERVATION_LAB = new Resource(Value.OBSERVATION_LAB, "observation-lab");

        public static final Resource QUESTIONNAIRERESPONSE =
                new Resource(Value.QUESTIONNAIRERESPONSE, "questionnaireresponse");

        public static final Resource VITAL_SIGNS = new Resource(Value.VITAL_SIGNS, "vital-signs");

        public static final Resource QUESTIONNAIRE = new Resource(Value.QUESTIONNAIRE, "questionnaire");

        public static final Resource CONDITION_PROBLEMS_HEALTH_CONCERNS =
                new Resource(Value.CONDITION_PROBLEMS_HEALTH_CONCERNS, "condition-problems-health-concerns");

        public static final Resource ENCOUNTER = new Resource(Value.ENCOUNTER, "encounter");

        public static final Resource SIMPLE_OBSERVATION = new Resource(Value.SIMPLE_OBSERVATION, "simple-observation");

        public static final Resource OBSERVATION_CLINICAL_RESULT =
                new Resource(Value.OBSERVATION_CLINICAL_RESULT, "observation-clinical-result");

        public static final Resource CAREPLAN = new Resource(Value.CAREPLAN, "careplan");

        public static final Resource COVERAGE = new Resource(Value.COVERAGE, "coverage");

        public static final Resource AUTO = new Resource(Value.AUTO, "auto");

        public static final Resource CONDITION_ENCOUNTER_DIAGNOSIS =
                new Resource(Value.CONDITION_ENCOUNTER_DIAGNOSIS, "condition-encounter-diagnosis");

        public static final Resource PATIENT = new Resource(Value.PATIENT, "patient");

        public static final Resource APPOINTMENT = new Resource(Value.APPOINTMENT, "appointment");

        public static final Resource PROCEDURE = new Resource(Value.PROCEDURE, "procedure");

        private final Value value;

        private final String string;

        Resource(Value value, String string) {
            this.value = value;
            this.string = string;
        }

        public Value getEnumValue() {
            return value;
        }

        @java.lang.Override
        @JsonValue
        public String toString() {
            return this.string;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            return (this == other) || (other instanceof Resource && this.string.equals(((Resource) other).string));
        }

        @java.lang.Override
        public int hashCode() {
            return this.string.hashCode();
        }

        public <T> T visit(Visitor<T> visitor) {
            switch (value) {
                case MEDICATIONREQUEST:
                    return visitor.visitMedicationrequest();
                case OBSERVATION_LAB:
                    return visitor.visitObservationLab();
                case QUESTIONNAIRERESPONSE:
                    return visitor.visitQuestionnaireresponse();
                case VITAL_SIGNS:
                    return visitor.visitVitalSigns();
                case QUESTIONNAIRE:
                    return visitor.visitQuestionnaire();
                case CONDITION_PROBLEMS_HEALTH_CONCERNS:
                    return visitor.visitConditionProblemsHealthConcerns();
                case ENCOUNTER:
                    return visitor.visitEncounter();
                case SIMPLE_OBSERVATION:
                    return visitor.visitSimpleObservation();
                case OBSERVATION_CLINICAL_RESULT:
                    return visitor.visitObservationClinicalResult();
                case CAREPLAN:
                    return visitor.visitCareplan();
                case COVERAGE:
                    return visitor.visitCoverage();
                case AUTO:
                    return visitor.visitAuto();
                case CONDITION_ENCOUNTER_DIAGNOSIS:
                    return visitor.visitConditionEncounterDiagnosis();
                case PATIENT:
                    return visitor.visitPatient();
                case APPOINTMENT:
                    return visitor.visitAppointment();
                case PROCEDURE:
                    return visitor.visitProcedure();
                case UNKNOWN:
                default:
                    return visitor.visitUnknown(string);
            }
        }

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public static Resource valueOf(String value) {
            switch (value) {
                case "medicationrequest":
                    return MEDICATIONREQUEST;
                case "observation-lab":
                    return OBSERVATION_LAB;
                case "questionnaireresponse":
                    return QUESTIONNAIRERESPONSE;
                case "vital-signs":
                    return VITAL_SIGNS;
                case "questionnaire":
                    return QUESTIONNAIRE;
                case "condition-problems-health-concerns":
                    return CONDITION_PROBLEMS_HEALTH_CONCERNS;
                case "encounter":
                    return ENCOUNTER;
                case "simple-observation":
                    return SIMPLE_OBSERVATION;
                case "observation-clinical-result":
                    return OBSERVATION_CLINICAL_RESULT;
                case "careplan":
                    return CAREPLAN;
                case "coverage":
                    return COVERAGE;
                case "auto":
                    return AUTO;
                case "condition-encounter-diagnosis":
                    return CONDITION_ENCOUNTER_DIAGNOSIS;
                case "patient":
                    return PATIENT;
                case "appointment":
                    return APPOINTMENT;
                case "procedure":
                    return PROCEDURE;
                default:
                    return new Resource(Value.UNKNOWN, value);
            }
        }

        public enum Value {
            AUTO,

            APPOINTMENT,

            CONDITION_ENCOUNTER_DIAGNOSIS,

            MEDICATIONREQUEST,

            CAREPLAN,

            CONDITION_PROBLEMS_HEALTH_CONCERNS,

            COVERAGE,

            ENCOUNTER,

            OBSERVATION_CLINICAL_RESULT,

            OBSERVATION_LAB,

            PATIENT,

            PROCEDURE,

            QUESTIONNAIRE,

            QUESTIONNAIRERESPONSE,

            SIMPLE_OBSERVATION,

            VITAL_SIGNS,

            UNKNOWN
        }

        public interface Visitor<T> {
            T visitAuto();

            T visitAppointment();

            T visitConditionEncounterDiagnosis();

            T visitMedicationrequest();

            T visitCareplan();

            T visitConditionProblemsHealthConcerns();

            T visitCoverage();

            T visitEncounter();

            T visitObservationClinicalResult();

            T visitObservationLab();

            T visitPatient();

            T visitProcedure();

            T visitQuestionnaire();

            T visitQuestionnaireresponse();

            T visitSimpleObservation();

            T visitVitalSigns();

            T visitUnknown(String unknownType);
        }
    }

    public static final class Provider {
        public static final Provider HAPI = new Provider(Value.HAPI, "hapi");

        public static final Provider CANVAS = new Provider(Value.CANVAS, "canvas");

        public static final Provider MEDPLUM = new Provider(Value.MEDPLUM, "medplum");

        public static final Provider GOOGLE_HEALTHCARE = new Provider(Value.GOOGLE_HEALTHCARE, "google_healthcare");

        private final Value value;

        private final String string;

        Provider(Value value, String string) {
            this.value = value;
            this.string = string;
        }

        public Value getEnumValue() {
            return value;
        }

        @java.lang.Override
        @JsonValue
        public String toString() {
            return this.string;
        }

        @java.lang.Override
        public boolean equals(Object other) {
            return (this == other) || (other instanceof Provider && this.string.equals(((Provider) other).string));
        }

        @java.lang.Override
        public int hashCode() {
            return this.string.hashCode();
        }

        public <T> T visit(Visitor<T> visitor) {
            switch (value) {
                case HAPI:
                    return visitor.visitHapi();
                case CANVAS:
                    return visitor.visitCanvas();
                case MEDPLUM:
                    return visitor.visitMedplum();
                case GOOGLE_HEALTHCARE:
                    return visitor.visitGoogleHealthcare();
                case UNKNOWN:
                default:
                    return visitor.visitUnknown(string);
            }
        }

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public static Provider valueOf(String value) {
            switch (value) {
                case "hapi":
                    return HAPI;
                case "canvas":
                    return CANVAS;
                case "medplum":
                    return MEDPLUM;
                case "google_healthcare":
                    return GOOGLE_HEALTHCARE;
                default:
                    return new Provider(Value.UNKNOWN, value);
            }
        }

        public enum Value {
            MEDPLUM,

            GOOGLE_HEALTHCARE,

            CANVAS,

            HAPI,

            UNKNOWN
        }

        public interface Visitor<T> {
            T visitMedplum();

            T visitGoogleHealthcare();

            T visitCanvas();

            T visitHapi();

            T visitUnknown(String unknownType);
        }
    }
}
