/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.tools.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.resources.tools.types.Lang2FhirAndCreateRequestResource;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Lang2FhirAndCreateRequest.Builder.class
)
public final class Lang2FhirAndCreateRequest {
  private final Optional<String> phenomlOnBehalfOf;

  private final Optional<String> phenomlFhirProvider;

  private final Lang2FhirAndCreateRequestResource resource;

  private final String text;

  private final Optional<String> provider;

  private final Map<String, Object> additionalProperties;

  private Lang2FhirAndCreateRequest(Optional<String> phenomlOnBehalfOf,
      Optional<String> phenomlFhirProvider, Lang2FhirAndCreateRequestResource resource, String text,
      Optional<String> provider, Map<String, Object> additionalProperties) {
    this.phenomlOnBehalfOf = phenomlOnBehalfOf;
    this.phenomlFhirProvider = phenomlFhirProvider;
    this.resource = resource;
    this.text = text;
    this.provider = provider;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
   * Must be in the format: Patient/{uuid} or Practitioner/{uuid}
   */
  @JsonIgnore
  public Optional<String> getPhenomlOnBehalfOf() {
    return phenomlOnBehalfOf;
  }

  /**
   * @return Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
   * Multiple FHIR provider integrations can be provided as comma-separated values.
   */
  @JsonIgnore
  public Optional<String> getPhenomlFhirProvider() {
    return phenomlFhirProvider;
  }

  /**
   * @return Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.
   */
  @JsonProperty("resource")
  public Lang2FhirAndCreateRequestResource getResource() {
    return resource;
  }

  /**
   * @return Natural language text to convert to FHIR resource
   */
  @JsonProperty("text")
  public String getText() {
    return text;
  }

  /**
   * @return FHIR provider ID - must be a valid UUID from existing FHIR providers. also supports provider by name (e.g. medplum)
   */
  @JsonProperty("provider")
  public Optional<String> getProvider() {
    return provider;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Lang2FhirAndCreateRequest && equalTo((Lang2FhirAndCreateRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Lang2FhirAndCreateRequest other) {
    return phenomlOnBehalfOf.equals(other.phenomlOnBehalfOf) && phenomlFhirProvider.equals(other.phenomlFhirProvider) && resource.equals(other.resource) && text.equals(other.text) && provider.equals(other.provider);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.phenomlOnBehalfOf, this.phenomlFhirProvider, this.resource, this.text, this.provider);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ResourceStage builder() {
    return new Builder();
  }

  public interface ResourceStage {
    /**
     * <p>Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.</p>
     */
    TextStage resource(@NotNull Lang2FhirAndCreateRequestResource resource);

    Builder from(Lang2FhirAndCreateRequest other);
  }

  public interface TextStage {
    /**
     * <p>Natural language text to convert to FHIR resource</p>
     */
    _FinalStage text(@NotNull String text);
  }

  public interface _FinalStage {
    Lang2FhirAndCreateRequest build();

    /**
     * <p>Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
     * Must be in the format: Patient/{uuid} or Practitioner/{uuid}</p>
     */
    _FinalStage phenomlOnBehalfOf(Optional<String> phenomlOnBehalfOf);

    _FinalStage phenomlOnBehalfOf(String phenomlOnBehalfOf);

    /**
     * <p>Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
     * Multiple FHIR provider integrations can be provided as comma-separated values.</p>
     */
    _FinalStage phenomlFhirProvider(Optional<String> phenomlFhirProvider);

    _FinalStage phenomlFhirProvider(String phenomlFhirProvider);

    /**
     * <p>FHIR provider ID - must be a valid UUID from existing FHIR providers. also supports provider by name (e.g. medplum)</p>
     */
    _FinalStage provider(Optional<String> provider);

    _FinalStage provider(String provider);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ResourceStage, TextStage, _FinalStage {
    private Lang2FhirAndCreateRequestResource resource;

    private String text;

    private Optional<String> provider = Optional.empty();

    private Optional<String> phenomlFhirProvider = Optional.empty();

    private Optional<String> phenomlOnBehalfOf = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Lang2FhirAndCreateRequest other) {
      phenomlOnBehalfOf(other.getPhenomlOnBehalfOf());
      phenomlFhirProvider(other.getPhenomlFhirProvider());
      resource(other.getResource());
      text(other.getText());
      provider(other.getProvider());
      return this;
    }

    /**
     * <p>Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.</p>
     * <p>Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("resource")
    public TextStage resource(@NotNull Lang2FhirAndCreateRequestResource resource) {
      this.resource = Objects.requireNonNull(resource, "resource must not be null");
      return this;
    }

    /**
     * <p>Natural language text to convert to FHIR resource</p>
     * <p>Natural language text to convert to FHIR resource</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    /**
     * <p>FHIR provider ID - must be a valid UUID from existing FHIR providers. also supports provider by name (e.g. medplum)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage provider(String provider) {
      this.provider = Optional.ofNullable(provider);
      return this;
    }

    /**
     * <p>FHIR provider ID - must be a valid UUID from existing FHIR providers. also supports provider by name (e.g. medplum)</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "provider",
        nulls = Nulls.SKIP
    )
    public _FinalStage provider(Optional<String> provider) {
      this.provider = provider;
      return this;
    }

    /**
     * <p>Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
     * Multiple FHIR provider integrations can be provided as comma-separated values.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage phenomlFhirProvider(String phenomlFhirProvider) {
      this.phenomlFhirProvider = Optional.ofNullable(phenomlFhirProvider);
      return this;
    }

    /**
     * <p>Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
     * Multiple FHIR provider integrations can be provided as comma-separated values.</p>
     */
    @java.lang.Override
    public _FinalStage phenomlFhirProvider(Optional<String> phenomlFhirProvider) {
      this.phenomlFhirProvider = phenomlFhirProvider;
      return this;
    }

    /**
     * <p>Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
     * Must be in the format: Patient/{uuid} or Practitioner/{uuid}</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage phenomlOnBehalfOf(String phenomlOnBehalfOf) {
      this.phenomlOnBehalfOf = Optional.ofNullable(phenomlOnBehalfOf);
      return this;
    }

    /**
     * <p>Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
     * Must be in the format: Patient/{uuid} or Practitioner/{uuid}</p>
     */
    @java.lang.Override
    public _FinalStage phenomlOnBehalfOf(Optional<String> phenomlOnBehalfOf) {
      this.phenomlOnBehalfOf = phenomlOnBehalfOf;
      return this;
    }

    @java.lang.Override
    public Lang2FhirAndCreateRequest build() {
      return new Lang2FhirAndCreateRequest(phenomlOnBehalfOf, phenomlFhirProvider, resource, text, provider, additionalProperties);
    }
  }
}
