/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.phenoml.api.resources.cohort;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.cohort.requests.CohortRequest;
import com.phenoml.api.resources.cohort.types.CohortResponse;

public class CohortClient {
  protected final ClientOptions clientOptions;

  private final RawCohortClient rawClient;

  public CohortClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawCohortClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawCohortClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Converts natural language text into structured FHIR search queries for patient cohort analysis
   */
  public CohortResponse analyze(CohortRequest request) {
    return this.rawClient.analyze(request).body();
  }

  /**
   * Converts natural language text into structured FHIR search queries for patient cohort analysis
   */
  public CohortResponse analyze(CohortRequest request, RequestOptions requestOptions) {
    return this.rawClient.analyze(request, requestOptions).body();
  }
}
