/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.fhir.fhiroperations;

import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.fhir.fhiroperations.requests.CreateRequest;
import com.phenoml.api.resources.fhir.fhiroperations.requests.DeleteRequest;
import com.phenoml.api.resources.fhir.fhiroperations.requests.ExecuteBundleRequest;
import com.phenoml.api.resources.fhir.fhiroperations.requests.PatchRequest;
import com.phenoml.api.resources.fhir.fhiroperations.requests.SearchRequest;
import com.phenoml.api.resources.fhir.fhiroperations.requests.UpsertRequest;
import com.phenoml.api.resources.fhir.fhiroperations.types.PatchRequestBodyItem;
import com.phenoml.api.resources.fhir.fhiroperations.types.SearchResponse;
import com.phenoml.api.resources.fhir.types.FhirBundle;
import com.phenoml.api.resources.fhir.types.FhirResource;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public class AsyncFhirOperationsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawFhirOperationsClient rawClient;

    public AsyncFhirOperationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawFhirOperationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawFhirOperationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves FHIR resources from the specified provider. Supports both individual resource retrieval and search operations based on the FHIR path and query parameters.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<SearchResponse> search(String fhirProviderId, String fhirPath) {
        return this.rawClient.search(fhirProviderId, fhirPath).thenApply(response -> response.body());
    }

    /**
     * Retrieves FHIR resources from the specified provider. Supports both individual resource retrieval and search operations based on the FHIR path and query parameters.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<SearchResponse> search(
            String fhirProviderId, String fhirPath, RequestOptions requestOptions) {
        return this.rawClient.search(fhirProviderId, fhirPath, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves FHIR resources from the specified provider. Supports both individual resource retrieval and search operations based on the FHIR path and query parameters.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<SearchResponse> search(String fhirProviderId, String fhirPath, SearchRequest request) {
        return this.rawClient.search(fhirProviderId, fhirPath, request).thenApply(response -> response.body());
    }

    /**
     * Retrieves FHIR resources from the specified provider. Supports both individual resource retrieval and search operations based on the FHIR path and query parameters.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<SearchResponse> search(
            String fhirProviderId, String fhirPath, SearchRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .search(fhirProviderId, fhirPath, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Creates a new FHIR resource on the specified provider. The request body should contain a valid FHIR resource in JSON format.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> create(String fhirProviderId, String fhirPath, FhirResource body) {
        return this.rawClient.create(fhirProviderId, fhirPath, body).thenApply(response -> response.body());
    }

    /**
     * Creates a new FHIR resource on the specified provider. The request body should contain a valid FHIR resource in JSON format.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> create(
            String fhirProviderId, String fhirPath, FhirResource body, RequestOptions requestOptions) {
        return this.rawClient
                .create(fhirProviderId, fhirPath, body, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Creates a new FHIR resource on the specified provider. The request body should contain a valid FHIR resource in JSON format.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> create(String fhirProviderId, String fhirPath, CreateRequest request) {
        return this.rawClient.create(fhirProviderId, fhirPath, request).thenApply(response -> response.body());
    }

    /**
     * Creates a new FHIR resource on the specified provider. The request body should contain a valid FHIR resource in JSON format.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> create(
            String fhirProviderId, String fhirPath, CreateRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .create(fhirProviderId, fhirPath, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Creates or updates a FHIR resource on the specified provider. If the resource exists, it will be updated; otherwise, it will be created.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> upsert(String fhirProviderId, String fhirPath, FhirResource body) {
        return this.rawClient.upsert(fhirProviderId, fhirPath, body).thenApply(response -> response.body());
    }

    /**
     * Creates or updates a FHIR resource on the specified provider. If the resource exists, it will be updated; otherwise, it will be created.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> upsert(
            String fhirProviderId, String fhirPath, FhirResource body, RequestOptions requestOptions) {
        return this.rawClient
                .upsert(fhirProviderId, fhirPath, body, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Creates or updates a FHIR resource on the specified provider. If the resource exists, it will be updated; otherwise, it will be created.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> upsert(String fhirProviderId, String fhirPath, UpsertRequest request) {
        return this.rawClient.upsert(fhirProviderId, fhirPath, request).thenApply(response -> response.body());
    }

    /**
     * Creates or updates a FHIR resource on the specified provider. If the resource exists, it will be updated; otherwise, it will be created.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> upsert(
            String fhirProviderId, String fhirPath, UpsertRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .upsert(fhirProviderId, fhirPath, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Deletes a FHIR resource from the specified provider.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<Map<String, Object>> delete(String fhirProviderId, String fhirPath) {
        return this.rawClient.delete(fhirProviderId, fhirPath).thenApply(response -> response.body());
    }

    /**
     * Deletes a FHIR resource from the specified provider.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<Map<String, Object>> delete(
            String fhirProviderId, String fhirPath, RequestOptions requestOptions) {
        return this.rawClient.delete(fhirProviderId, fhirPath, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes a FHIR resource from the specified provider.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<Map<String, Object>> delete(
            String fhirProviderId, String fhirPath, DeleteRequest request) {
        return this.rawClient.delete(fhirProviderId, fhirPath, request).thenApply(response -> response.body());
    }

    /**
     * Deletes a FHIR resource from the specified provider.
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<Map<String, Object>> delete(
            String fhirProviderId, String fhirPath, DeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .delete(fhirProviderId, fhirPath, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Partially updates a FHIR resource on the specified provider using JSON Patch operations as defined in RFC 6902.
     * <p>The request body should contain an array of JSON Patch operations. Each operation specifies:</p>
     * <ul>
     * <li><code>op</code>: The operation type (add, remove, replace, move, copy, test)</li>
     * <li><code>path</code>: JSON Pointer to the target location in the resource</li>
     * <li><code>value</code>: The value to use (required for add, replace, and test operations)</li>
     * </ul>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> patch(
            String fhirProviderId, String fhirPath, List<PatchRequestBodyItem> body) {
        return this.rawClient.patch(fhirProviderId, fhirPath, body).thenApply(response -> response.body());
    }

    /**
     * Partially updates a FHIR resource on the specified provider using JSON Patch operations as defined in RFC 6902.
     * <p>The request body should contain an array of JSON Patch operations. Each operation specifies:</p>
     * <ul>
     * <li><code>op</code>: The operation type (add, remove, replace, move, copy, test)</li>
     * <li><code>path</code>: JSON Pointer to the target location in the resource</li>
     * <li><code>value</code>: The value to use (required for add, replace, and test operations)</li>
     * </ul>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> patch(
            String fhirProviderId, String fhirPath, List<PatchRequestBodyItem> body, RequestOptions requestOptions) {
        return this.rawClient
                .patch(fhirProviderId, fhirPath, body, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Partially updates a FHIR resource on the specified provider using JSON Patch operations as defined in RFC 6902.
     * <p>The request body should contain an array of JSON Patch operations. Each operation specifies:</p>
     * <ul>
     * <li><code>op</code>: The operation type (add, remove, replace, move, copy, test)</li>
     * <li><code>path</code>: JSON Pointer to the target location in the resource</li>
     * <li><code>value</code>: The value to use (required for add, replace, and test operations)</li>
     * </ul>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> patch(String fhirProviderId, String fhirPath, PatchRequest request) {
        return this.rawClient.patch(fhirProviderId, fhirPath, request).thenApply(response -> response.body());
    }

    /**
     * Partially updates a FHIR resource on the specified provider using JSON Patch operations as defined in RFC 6902.
     * <p>The request body should contain an array of JSON Patch operations. Each operation specifies:</p>
     * <ul>
     * <li><code>op</code>: The operation type (add, remove, replace, move, copy, test)</li>
     * <li><code>path</code>: JSON Pointer to the target location in the resource</li>
     * <li><code>value</code>: The value to use (required for add, replace, and test operations)</li>
     * </ul>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirResource> patch(
            String fhirProviderId, String fhirPath, PatchRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .patch(fhirProviderId, fhirPath, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Executes a FHIR Bundle transaction or batch operation on the specified provider. This allows multiple FHIR resources to be processed in a single request.
     * <p>The request body should contain a valid FHIR Bundle resource with transaction or batch type.</p>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirBundle> executeBundle(String fhirProviderId, FhirBundle body) {
        return this.rawClient.executeBundle(fhirProviderId, body).thenApply(response -> response.body());
    }

    /**
     * Executes a FHIR Bundle transaction or batch operation on the specified provider. This allows multiple FHIR resources to be processed in a single request.
     * <p>The request body should contain a valid FHIR Bundle resource with transaction or batch type.</p>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirBundle> executeBundle(
            String fhirProviderId, FhirBundle body, RequestOptions requestOptions) {
        return this.rawClient
                .executeBundle(fhirProviderId, body, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Executes a FHIR Bundle transaction or batch operation on the specified provider. This allows multiple FHIR resources to be processed in a single request.
     * <p>The request body should contain a valid FHIR Bundle resource with transaction or batch type.</p>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirBundle> executeBundle(String fhirProviderId, ExecuteBundleRequest request) {
        return this.rawClient.executeBundle(fhirProviderId, request).thenApply(response -> response.body());
    }

    /**
     * Executes a FHIR Bundle transaction or batch operation on the specified provider. This allows multiple FHIR resources to be processed in a single request.
     * <p>The request body should contain a valid FHIR Bundle resource with transaction or batch type.</p>
     * <p>The request is proxied to the configured FHIR server with appropriate authentication headers.</p>
     */
    public CompletableFuture<FhirBundle> executeBundle(
            String fhirProviderId, ExecuteBundleRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .executeBundle(fhirProviderId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
