/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.summary.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SummaryGetTemplateResponse.Builder.class)
public final class SummaryGetTemplateResponse {
    private final Optional<Boolean> success;

    private final Optional<SummaryTemplate> template;

    private final Map<String, Object> additionalProperties;

    private SummaryGetTemplateResponse(
            Optional<Boolean> success, Optional<SummaryTemplate> template, Map<String, Object> additionalProperties) {
        this.success = success;
        this.template = template;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("success")
    public Optional<Boolean> getSuccess() {
        return success;
    }

    @JsonProperty("template")
    public Optional<SummaryTemplate> getTemplate() {
        return template;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SummaryGetTemplateResponse && equalTo((SummaryGetTemplateResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SummaryGetTemplateResponse other) {
        return success.equals(other.success) && template.equals(other.template);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.template);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> success = Optional.empty();

        private Optional<SummaryTemplate> template = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SummaryGetTemplateResponse other) {
            success(other.getSuccess());
            template(other.getTemplate());
            return this;
        }

        @JsonSetter(value = "success", nulls = Nulls.SKIP)
        public Builder success(Optional<Boolean> success) {
            this.success = success;
            return this;
        }

        public Builder success(Boolean success) {
            this.success = Optional.ofNullable(success);
            return this;
        }

        @JsonSetter(value = "template", nulls = Nulls.SKIP)
        public Builder template(Optional<SummaryTemplate> template) {
            this.template = template;
            return this;
        }

        public Builder template(SummaryTemplate template) {
            this.template = Optional.ofNullable(template);
            return this;
        }

        public SummaryGetTemplateResponse build() {
            return new SummaryGetTemplateResponse(success, template, additionalProperties);
        }
    }
}
